# json extender

OK, so we've got everything operational. ish.

What we're going to do now is run the theories on the entire set of responses. Then we can update the json files so that they contain all the relevant information.

In [1]:
import amati_bea as amati

In [2]:
import pandas as pd

from sklearn.metrics import f1_score, cohen_kappa_score

In [3]:
from operator import itemgetter
import pickle
import datetime
import re
import glob
import json

## Get the data

We'll just be able to pull out the relevant data from the saved theory.

with open(
    "/Users/alistair.willis/repos/bea-2026/3-way/theories/run_20260303/theory_64393e93-5585-42f9-ad22-ffa71219573b_2026-03-04_02:35:57.762552.pickle", "rb"
) as fIn:
    theory = pickle.load(fIn)

theory.keys()

Let's find a trial response. First, need to pull out the question for that theory:

theory["question_id"]

And then get the associated responses:

theory["all_responses_df"].query("`question_id`==@theory['question_id']").query(
    "`partition`=='trial'"
).head()

So let's just bag the first of those:

TEST_RESPONSE_ID = (
    theory["all_responses_df"]
    .query("`question_id`==@theory['question_id']")
    .query("`partition`=='trial'")
    .iloc[0, 0]
)

TEST_RESPONSE_ID

Reverse ferret, let's apply to the trial set:

def apply_trial_set(theory):

    question_id=theory["question_id"]
    original_question_id=theory["original_question_id"]

    question_ss = theory['all_questions_df'].set_index("original_question_id").T[
        original_question_id
    ]
    
    trial_responses_df = theory['all_responses_df'].query("`question_id`==@question_id").query(
        "`partition`=='trial'"
    )

    trial_texts_used = [
        question_id,
        question_ss["correct_id"],
        question_ss["partially_correct_id"],
        question_ss["incorrect_id"],
    ] + list(trial_responses_df["response_id"])

    trial_text_df = theory['all_text_df'].query("`id`.isin(@trial_texts_used)")[
        ["id", "i", "lemma"]
    ]

    results_df = amati.evaluate_theory(
        theory['theory'],
        responses_df=trial_responses_df,
        text_df=trial_text_df,
        rulesstring=theory['rules'],
        question_ss=question_ss,
    )

    compare_df = (
        trial_responses_df[["response_id", "score"]]
        .rename({"score": "actual"}, axis="columns")
        .set_index("response_id")
        .assign(
            prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")
        )
    )

    return {"theory": theory, "results": results_df, "compare": compare_df}

def get_rule_applications(theory):

    question_id=theory["question_id"]
    original_question_id=theory["original_question_id"]

    question_ss = theory['all_questions_df'].set_index("original_question_id").T[
        original_question_id
    ]
    
    trial_responses_df = theory['all_responses_df'].query("`question_id`==@question_id").query(
        "`partition`=='trial'"
    )

    trial_texts_used = [
        question_id,
        question_ss["correct_id"],
        question_ss["partially_correct_id"],
        question_ss["incorrect_id"],
    ] + list(trial_responses_df["response_id"])

    trial_text_df = theory['all_text_df'].query("`id`.isin(@trial_texts_used)")[
        ["id", "i", "lemma"]
    ]

    results_dict = amati.apply_theory(
        theory['theory'],
        responses_df=trial_responses_df,
        text_df=trial_text_df,
        rulesstring=theory['rules'],
        question_ss=question_ss,
    )

    """ compare_df = (
        trial_responses_df[["response_id", "score"]]
        .rename({"score": "actual"}, axis="columns")
        .set_index("response_id")
        .assign(
            prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")
        )
    ) """

    return {"theory": theory, "applications": results_dict}

In [4]:
def get_all_rule_applications(theory):
    "Don't restrict to trial"

    question_id=theory["question_id"]
    original_question_id=theory["original_question_id"]

    question_ss = theory['all_questions_df'].set_index("original_question_id").T[
        original_question_id
    ]
    
    trial_responses_df = theory['all_responses_df'].query("`question_id`==@question_id")

    trial_texts_used = [
        question_id,
        question_ss["correct_id"],
        question_ss["partially_correct_id"],
        question_ss["incorrect_id"],
    ] + list(trial_responses_df["response_id"])

    trial_text_df = theory['all_text_df'].query("`id`.isin(@trial_texts_used)")[
        ["id", "i", "lemma"]
    ]

    results_dict = amati.apply_theory(
        theory['theory'],
        responses_df=trial_responses_df,
        text_df=trial_text_df,
        rulesstring=theory['rules'],
        question_ss=question_ss,
    )

    """ compare_df = (
        trial_responses_df[["response_id", "score"]]
        .rename({"score": "actual"}, axis="columns")
        .set_index("response_id")
        .assign(
            prediction=results_df.ffill(axis="columns").iloc[:, -1].fillna("incorrect")
        )
    ) """

    return {"theory": theory, "applications": results_dict}

question_id = theory["question_id"]
original_question_id = theory["original_question_id"]

question_ss = (
    theory["all_questions_df"].set_index("original_question_id").T[original_question_id]
)

trial_responses_df = (
    theory["all_responses_df"]
    .query("`question_id`==@question_id")
    .query("`partition`=='trial'")
)

trial_texts_used = [
    question_id,
    question_ss["correct_id"],
    question_ss["partially_correct_id"],
    question_ss["incorrect_id"],
] + list(trial_responses_df["response_id"])

trial_text_df = theory["all_text_df"].query("`id`.isin(@trial_texts_used)")[
    ["id", "i", "lemma"]
]


d=apply_theory(
    theory["theory"],
    responses_df=trial_responses_df,
    rulesstring=theory["rules"],
    question_ss=question_ss,
    text_df=trial_text_df,
)
d


amati.apply_theory(
    theory["theory"],
    responses_df=trial_responses_df,
    rulesstring=theory["rules"],
    question_ss=question_ss,
    text_df=trial_text_df,
)

o=apply_trial_set(theory)

o['results']

t=get_rule_applications(theory)
t['applications']

t['applications']['r_1842']

## Apply to all theories

outputs_ls=[]

for f in glob.glob("theories/run_20260303/*")[:3]:
    print(f)
    with open(f, 'rb') as fIn:
        theory=pickle.load(fIn)
    outputs_ls.append(get_all_rule_applications(theory))

OK, so now we should be able to add that information to each of the jsons in the actual files:

Because I changed the format of the identifiers, I'll need to wrangle it back into a form that uses the original ids.

r=outputs_ls[2]

First, let's get an id mapper. We can do it for all IDs. Start with the response IDs:

id_mapper=r['theory']['all_responses_df'].set_index('response_id')[ 'original_response_id'].to_dict()

id_mapper

Then the question IDs:

id_mapper.update(r['theory']['all_questions_df'].set_index('question_id')[ 'original_question_id'].to_dict()
)

id_mapper

OK, good. So now we want to get a representation of what rule applies to each response.

r['applications'].keys()

rr=r['applications']['r_0115']
rr

len(rr)

We want a function which returns a json form of the rule it's been given.

In [5]:
def get_json_from_rule(rule):
    if rule["selected_rule"][0] == "rule1":
        return {
            "amati": {
                "literals": [
                    {
                        "pred": "contains",
                        "document": "student_response",
                        "lemma": [x[1] for x in rule["parameters"] if x[0] == 1][0],
                        "id": "@1",
                    }
                ],
                "prediction": rule["predicted_grade"][0],
            }
        }
    elif rule["selected_rule"][0] == "rule2":
        return {
            "amati": {
                "literals": [
                    {
                        "pred": "contains",
                        "document": "student_response",
                        "lemma": [x[1] for x in rule["parameters"] if x[0] == 1][0],
                        "id": "@1",
                    },
                    {
                        "pred": "contains",
                        "document": "student_response",
                        "lemma": [x[1] for x in rule["parameters"] if x[0] == 2][0],
                        "id": "@2",
                    },
                    {"pred": "precedes", "order": ["@1", "@2"]},
                ],
                "prediction": rule["predicted_grade"][0],
            }
        }
    elif rule["selected_rule"][0] == "rule3":
        return {
            "amati": {
                "literals": [
                    {
                        "pred": "contains",
                        "document": "student_response",
                        "lemma": [x[1] for x in rule["parameters"] if x[0] == 1][0],
                        "id": "@1",
                    },
                    {
                        "pred": "contains",
                        "document": "student_response",
                        "lemma": [x[1] for x in rule["parameters"] if x[0] == 2][0],
                        "id": "@2",
                    },
                ],
                "prediction": rule["predicted_grade"][0],
            }
        }
    elif rule["selected_rule"][0] == "ki_rule1":
        return {
            "amati": {
                "literals": [
                    {
                        "pred": "contains",
                        "document": "student_response",
                        "lemma": [x[1] for x in rule["parameters"] if x[0] == 1][0],
                        "id": "@1",
                    },
                    {
                        "pred": "contains",
                        "document": "reference_answer",
                        "lemma": [x[1] for x in rule["parameters"] if x[0] == 1][0],
                        "id": "@2",
                    },
                    {
                        "pred": "contains",
                        "negated":True,
                        "document": "question",
                        "lemma": [x[1] for x in rule["parameters"] if x[0] == 1][0],
                        "id": "@3",
                    },
                ],
                "prediction": rule["predicted_grade"][0],
            }
        }
    else:
        assert(False)

[
    (id, get_json_from_rule(rules[0]))
    for (id, rules) in r["applications"].items()
    if rules
] + [
    (id, {"amati": {"literals": {}, "prediction": "incorrect"}})
    for (id, rules) in r["applications"].items()
    if not rules
]

OK, the code is now a complete mess, but I can tidy up at a future date. Key thing at the moment is to get things into a usable state whereby we can actually do a trial run.

In [6]:
def get_amati_json_from_theory(filename):

    # Pull the theory out of the file
    with open(filename, "rb") as fIn:
        theory = pickle.load(fIn)

    # Build an id mapper
    id_mapper = (
        theory["all_responses_df"]
        .set_index("response_id")["original_response_id"]
        .to_dict()
    )

    id_mapper.update(
        theory["all_questions_df"]
        .set_index("question_id")["original_question_id"]
        .to_dict()
    )

    # Apply the theory to all the responses to that question
    applications_dict = get_all_rule_applications(theory)["applications"]

    amati_pairs_ls = [
        (id, get_json_from_rule(rules[0]))
        for (id, rules) in applications_dict.items()
        if rules
    ] + [
        (id, {"amati": {"literals": {}, "prediction": "incorrect"}})
        for (id, rules) in applications_dict.items()
        if not rules
    ]

    # And convert to a correctly mapped dictionary
    amati_dict = {
        id_mapper[response_id]: amati for (response_id, amati) in amati_pairs_ls
    }

    return amati_dict

OK, well let's see if that works. I'll run it on all the theories, and check that we end up with a complete set of responses.

Obviously save the output as json before doing anything rash...

In [7]:
outputs_ls=[]

for f in glob.glob("theories/run_20260303/*"):
    print(f)
    try:
        outputs_ls.append(get_amati_json_from_theory(f))
    except:
        continue

theories/run_20260303/theory_10d57539-7664-4f0f-afe2-51a749036f54_2026-03-03_22:57:43.893904.pickle
theories/run_20260303/theory_badc70b3-e8b8-4d54-8b1b-4c25d9b371da_2026-03-03_22:58:33.553917.pickle
theories/run_20260303/theory_93b2ea65-14e0-4a3b-bb50-bb4759c44a22_2026-03-03_19:07:29.031321.pickle
theories/run_20260303/theory_2ad4c4b0-5dfe-4667-b344-a00434eeccf1_2026-03-04_02:38:16.725370.pickle
theories/run_20260303/theory_52af038f-7137-4406-bcbb-fb5a0291fd25_2026-03-03_17:24:32.763687.pickle
theories/run_20260303/theory_0bf8fd8c-a68a-4491-ae28-be767f335729_2026-03-03_17:58:04.395918.pickle
theories/run_20260303/theory_741376db-a5f7-43a1-abc4-988ff40cf642_2026-03-03_22:35:10.945536.pickle
theories/run_20260303/theory_b8d67d94-9aeb-4b96-a3d1-d7eebd6a1b9a_2026-03-03_23:00:31.130305.pickle
theories/run_20260303/theory_bcded41e-7008-4fb7-a64f-701f41dd2ed8_2026-03-03_20:16:47.950977.pickle
theories/run_20260303/theory_6cc84feb-e8e1-4561-8057-452dce98bd65_2026-03-03_19:41:37.701232.pickle
theories/run_20260303/theory_4ba62250-a272-4b8f-bf28-eb531661fcc8_2026-03-03_21:20:18.283491.pickle
theories/run_20260303/theory_d74961fe-bfe5-4edc-9dbf-fa6f04c2437a_2026-03-03_23:34:52.604559.pickle
theories/run_20260303/theory_3ece7826-c379-4e51-b23d-ad50296f3a29_2026-03-03_21:15:03.991564.pickle
theories/run_20260303/theory_bc2d01c9-424c-428a-9909-7114819a31d9_2026-03-03_23:00:36.438050.pickle
theories/run_20260303/theory_ba753563-faa3-43c6-973d-320e5adc6979_2026-03-03_20:28:24.269279.pickle
theories/run_20260303/theory_366020b0-dde2-4af5-8e31-d9f4dc61c6ea_2026-03-03_22:57:58.446575.pickle
theories/run_20260303/theory_18fecb92-5da4-4e60-92cd-0040b817b3f1_2026-03-03_20:07:23.373485.pickle
theories/run_20260303/theory_72ec67ad-49f9-4aae-bd03-6efe95ec0947_2026-03-03_18:51:45.024355.pickle
theories/run_20260303/theory_93ed3f79-b3e9-41d2-8984-d8e2fa2143e8_2026-03-03_19:41:33.004708.pickle
theories/run_20260303/theory_838b4e27-f33d-439d-987b-57ddece063ad_2026-03-04_03:00:31.599342.pickle
theories/run_20260303/theory_faf4a6a7-85fd-4cb7-ab8e-1c21b4bbdec9_2026-03-03_17:58:09.637942.pickle
theories/run_20260303/theory_2517045e-4268-4a57-b953-89ab4040a1b5_2026-03-03_23:16:02.208138.pickle
theories/run_20260303/theory_863b0d4d-6f16-4ad1-9228-8806513ef605_2026-03-03_21:28:52.128397.pickle
theories/run_20260303/theory_1f3469d5-f6a8-49f4-85d0-d2e156e4cb0c_2026-03-03_18:51:51.818213.pickle
theories/run_20260303/theory_9f80f2c6-db27-4f50-b16b-e6f7b690d04a_2026-03-03_18:42:01.304383.pickle
theories/run_20260303/theory_1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe_2026-03-04_03:14:36.118905.pickle
theories/run_20260303/theory_f38d01cf-f8e1-4e68-a11f-162b9cb6f0c7_2026-03-03_19:37:39.659613.pickle
theories/run_20260303/theory_da9e0a6a-7fd4-47ad-aa6a-a0f91fda560e_2026-03-04_02:33:24.743833.pickle
theories/run_20260303/theory_f5537007-c811-4910-8a18-aaa3e61c39f2_2026-03-03_20:58:36.889531.pickle
theories/run_20260303/theory_4a79233b-2d16-4c6d-ba9f-53a7bedf49fc_2026-03-03_19:41:18.363181.pickle
theories/run_20260303/theory_e4b30945-ecea-4112-bc13-66fe78bb817d_2026-03-04_01:44:05.323908.pickle
theories/run_20260303/theory_e937d43d-23dd-49d7-a3c7-0f874e478b3c_2026-03-03_17:57:55.790482.pickle
theories/run_20260303/theory_0a3fd73f-2ab4-437d-b963-92b569f460bf_2026-03-03_21:15:06.368675.pickle
theories/run_20260303/theory_c7a7a954-e315-4ec2-90df-48e5a0940e25_2026-03-03_22:59:13.081883.pickle
theories/run_20260303/theory_90e1e345-e950-4273-8974-9ace5ff17925_2026-03-04_02:33:46.157770.pickle
theories/run_20260303/theory_45917d45-6b3e-40db-b32b-2a6913ae630b_2026-03-03_22:37:43.455372.pickle
theories/run_20260303/theory_64393e93-5585-42f9-ad22-ffa71219573b_2026-03-04_02:35:57.762552.pickle
theories/run_20260303/theory_09dcf4a4-4f9f-4b77-880e-ed14609ea218_2026-03-04_03:00:29.928798.pickle
theories/run_20260303/theory_650405c5-4f5b-4479-b0a4-7772b5fc2e49_2026-03-03_21:28:53.607065.pickle
theories/run_20260303/theory_aa16fbaa-d192-46b4-b338-395bfc6bc58b_2026-03-04_01:12:43.060106.pickle
theories/run_20260303/theory_b845b9f0-92af-4805-be05-b8faf5960dd1_2026-03-04_02:01:58.637839.pickle
theories/run_20260303/theory_46835724-b516-4a38-857e-5f46a31ef78a_2026-03-04_02:33:30.227210.pickle
theories/run_20260303/theory_5c0edfac-2536-455a-8078-3adceeecfa43_2026-03-03_22:57:31.456114.pickle
theories/run_20260303/theory_807991c9-2b51-4c91-88f7-86b0cbc129e3_2026-03-03_21:15:14.792846.pickle
theories/run_20260303/theory_37aa9003-c5d4-4d80-ad29-b63118bb9fba_2026-03-04_00:46:37.268815.pickle
theories/run_20260303/theory_fa5c7308-3e1f-40f7-a8e0-5d448551afc0_2026-03-04_02:51:37.155537.pickle
theories/run_20260303/theory_9ef2a4f6-8d72-42b1-a5af-6dc1e8bb74c5_2026-03-04_00:08:57.318159.pickle
theories/run_20260303/theory_9546e86e-5b8e-4b0c-8907-2d57551f43ad_2026-03-04_02:55:56.175923.pickle
theories/run_20260303/theory_b076d670-42c4-46fc-b4f4-07a2d617afd7_2026-03-03_18:51:49.914588.pickle
theories/run_20260303/theory_67c1649e-b694-4813-be49-abfd65a6798e_2026-03-03_21:21:46.029345.pickle
theories/run_20260303/theory_90d2761e-010d-4463-afe7-6b3fa2561dc2_2026-03-03_18:51:47.875672.pickle
theories/run_20260303/theory_ac4d6b7e-4579-4351-bd94-15086b0f9445_2026-03-03_22:57:56.458212.pickle
theories/run_20260303/theory_1f95fd0e-cd6d-4ae2-b8e8-add8adf9d343_2026-03-03_22:57:44.656799.pickle
theories/run_20260303/theory_c24f6093-2644-4fc4-b7c9-d798500f483f_2026-03-03_18:43:40.840013.pickle
theories/run_20260303/theory_7f600524-3002-4fff-8536-ccbdac8d8a93_2026-03-03_23:16:03.132968.pickle
theories/run_20260303/theory_be7e5fe8-bd7f-4b81-93d3-2d89cce152c7_2026-03-03_23:02:43.413708.pickle
theories/run_20260303/theory_e9e8d257-f86c-4ac9-8179-7fa3ce30b88f_2026-03-04_03:00:23.061599.pickle
theories/run_20260303/theory_81d2eaef-552d-4748-bad6-b38784de7303_2026-03-03_18:51:42.570907.pickle
theories/run_20260303/theory_e1a10534-6152-4082-aa3e-e0265fa89acb_2026-03-03_20:12:37.362943.pickle
theories/run_20260303/theory_81632115-0e90-4ec0-bea1-12a7f4b95bc0_2026-03-04_01:31:07.125344.pickle
theories/run_20260303/theory_4e3a3e06-40c4-479b-8882-36005aae1e4e_2026-03-03_18:51:48.597616.pickle
theories/run_20260303/theory_a1760d86-f7ff-4e7f-9c95-549896c04865_2026-03-03_19:37:17.197448.pickle
theories/run_20260303/theory_9a2e7fec-b8fe-49d5-853c-2c0a32c36285_2026-03-03_20:14:13.342066.pickle
theories/run_20260303/theory_738c833f-a6a6-473b-94c9-7793ae9ebc85_2026-03-03_23:34:48.580827.pickle
theories/run_20260303/theory_afe4a36a-bbce-40da-a70c-03158b57b6cb_2026-03-04_02:57:46.133134.pickle
theories/run_20260303/theory_3bc01472-a1c1-485a-8e3f-3f6a8fcd186d_2026-03-04_03:10:58.768112.pickle
theories/run_20260303/theory_dfeace94-8239-4f80-b769-1e0bebbc391f_2026-03-04_01:18:05.079539.pickle
theories/run_20260303/theory_ddadb678-ef4b-4f25-865b-82bda9262c1e_2026-03-04_02:57:40.851548.pickle
theories/run_20260303/theory_85280bfa-db74-4f0b-a996-35c0decc2185_2026-03-03_21:21:39.344577.pickle
theories/run_20260303/theory_4a38efeb-0a3c-4ff1-8320-2197abb410a3_2026-03-03_22:57:32.396140.pickle
theories/run_20260303/theory_442a4171-9f3a-40b2-b4b5-7c023bbfd4c4_2026-03-03_20:10:28.855108.pickle
theories/run_20260303/theory_669d1caf-b302-4e93-ac7a-aa969b61fb03_2026-03-04_01:08:00.471878.pickle
theories/run_20260303/theory_eed7925e-248b-4d88-a809-1d352d705f39_2026-03-03_22:57:09.179059.pickle
theories/run_20260303/theory_33385739-7e9d-4aa6-9118-62e6772f7eb1_2026-03-03_20:14:05.665090.pickle
theories/run_20260303/theory_526bc80e-e028-4e81-8f00-959804ed200f_2026-03-03_19:49:25.868922.pickle
theories/run_20260303/theory_e4989914-39f3-4ffb-9fe3-d744938d9983_2026-03-03_22:57:30.142238.pickle
theories/run_20260303/theory_75333f3a-c1c2-4729-8d61-146800f16532_2026-03-03_16:44:08.269430.pickle
theories/run_20260303/theory_826d0863-2521-45d8-aafe-6871679062b9_2026-03-03_23:34:53.879128.pickle

In [8]:
with open('test.json', 'w') as fOut:
    json.dump(outputs_ls, fOut)

In [10]:
d={}

for e in outputs_ls:
    d.update(e)

d

{'97fb8399-ecbc-4e6e-b9a4-fc6d0a3468b7': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"gehen"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 'cda9ad99-4da6-4090-bd58-5339e096812a': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"gehen"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 '0c6adcfe-852d-4c08-b7da-d08a90826772': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"umgekehrt"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 'f34b9087-697e-47f1-9813-0c3d1dea19de': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"graph"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 '67f3ffb6-8614-4a6f-aee4-3a9986764f4d': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"umgekehrt"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 'bc836c83-4013-4ae9-b3da-5f90e8eb0d47': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"gehen"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 '3ee5e5db-5ecb-4635-8019-25684ebcda96': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"graph"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 'fe2d4710-ecd0-48b3-b23d-fe567e1bd30f': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"umgekehrt"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 '9b2769ea-a4e3-468f-b43b-22ce36aaa83d': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '0f2154a5-2b4b-477e-a260-7eed36d9d35e': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '87a08bca-c2fd-4d0f-a3c5-d05b213ae871': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '8cf1fdc8-526f-44ef-8e12-05069aeb9dda': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '51f40c54-6604-4c4d-83d4-967e081c716b': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'd4bf2d58-325b-4abf-9a65-8280bcbb5316': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '6b51079b-9ec2-405b-8ba7-9f07bfc1baad': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '33a9bcb6-45ba-48ce-b12f-6fd875d1bc39': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'f8660f3e-4894-4f9f-a4aa-627dd71c7a37': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '5fe2975c-24ad-436e-8cb5-2ebd8c234518': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '03a13d03-6832-43a8-ae0c-44f50955eff7': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'f8c8f96f-93b5-4a29-b55d-fc85654ed47b': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'e4f18661-38ff-471d-b429-28f8687e6315': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"berg"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'correct'}},
 '0c9e6273-86f3-4e00-ba65-c2226993aa72': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"verausgaben"',
     'id': '@1'}],
   'prediction': 'correct'}},
 'bb98932d-bb19-4390-a46d-176c7d28b9b9': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"ausdauer"',
     'id': '@1'}],
   'prediction': 'partially_correct'}},
 'b4d5ad37-ac98-4d16-bffe-b9aca870f3fc': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"berg"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'correct'}},
 'f6a37433-0616-4752-8c7b-c3ccc00e79b5': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"abschnitt"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"hoch"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'incorrect'}},
 '7c7604fa-26e9-4fad-9301-6ab32f9dd824': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"ende"',
     'id': '@1'}],
   'prediction': 'correct'}},
 'a2d5080c-0868-49c7-a0c6-ab25df09c8a9': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"tempo"',
     'id': '@1'}],
   'prediction': 'partially_correct'}},
 '7b346ca1-22d7-4a8e-9dc8-052b0cfb4329': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"steigung"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"anfang"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'correct'}},
 '1bb90d19-07e1-4243-8885-5255f65e545a': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"berg"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'correct'}},
 '1501aa8f-fbef-48a6-bb72-ff871a2f9a5a': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"abschnitt"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'partially_correct'}},
 'f395863f-a0ff-4ecf-a2ce-f057188780d7': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"abschnitt"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'partially_correct'}},
 '9b3ef00c-ff99-492b-be7c-76b5c70977a2': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"berg"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'correct'}},
 '3bab11cf-35e1-4be3-9f8e-f7aa9af70d95': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"ende"',
     'id': '@1'}],
   'prediction': 'correct'}},
 '8ed9c5eb-c72f-424e-a25d-e89213dd5e7d': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"tempo"',
     'id': '@1'}],
   'prediction': 'partially_correct'}},
 '760911c4-b862-4216-8bca-866292415714': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"anstieg"',
     'id': '@1'}],
   'prediction': 'correct'}},
 'af635e9b-3234-41b8-8dfa-65358403eab6': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"achten"',
     'id': '@1'}],
   'prediction': 'partially_correct'}},
 'f81d731e-69e2-4a13-be4a-1b57334ca5a6': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"verausgaben"',
     'id': '@1'}],
   'prediction': 'correct'}},
 '6fc41f50-735a-4ebc-a5bf-db69c32cb8b6': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"berg"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'correct'}},
 '981ddcac-c164-469e-b259-3173c8c3997e': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"ende"',
     'id': '@1'}],
   'prediction': 'correct'}},
 '24328ad0-5363-4892-9e31-09c5085a61f3': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"abschnitt"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'partially_correct'}},
 '5359507c-3258-40b1-9525-6e5dc38eead1': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"abschnitt"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'partially_correct'}},
 'c63f8d0b-beb6-421e-b6f9-1697b02ab77f': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"ausdauer"',
     'id': '@1'}],
   'prediction': 'partially_correct'}},
 'af6232f1-d88e-4510-a619-4a8992c76dad': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"ende"',
     'id': '@1'}],
   'prediction': 'correct'}},
 '6410ebf3-c79b-4d00-bef9-41122eec1908': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"berg"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'correct'}},
 '49ef2bf6-7240-4aa1-bab2-26711d7ba9f1': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"ende"',
     'id': '@1'}],
   'prediction': 'correct'}},
 '77c4510c-e7b5-4484-a4e0-0b32c14bb9bd': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"genug"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'correct'}},
 '6e7479dc-222e-4cb2-bc8a-29920a0994c4': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"anstieg"',
     'id': '@1'}],
   'prediction': 'correct'}},
 'a64da8b5-d6f7-42aa-aed2-ba0d90189211': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"berg"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'correct'}},
 '7b731ecc-d6d4-4765-975a-eb6d981956d3': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"ende"',
     'id': '@1'}],
   'prediction': 'correct'}},
 '87990efe-50cf-4e31-ada2-a985a9dbd2f0': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"achten"',
     'id': '@1'}],
   'prediction': 'partially_correct'}},
 '1f949193-195b-4bd0-84dc-5fdd27876e19': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"tempo"',
     'id': '@1'}],
   'prediction': 'partially_correct'}},
 'c17ed65a-c781-4697-9170-b72a30f793e7': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"berg"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'correct'}},
 '3ec7f204-deb8-4880-a823-faa873cd515a': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"gegner"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 '9cee8bbf-1da4-4b2b-8c60-24b0facba0f6': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"ende"',
     'id': '@1'}],
   'prediction': 'correct'}},
 '95067f1b-451f-4dc9-8cb9-907b0154334b': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"ende"',
     'id': '@1'}],
   'prediction': 'correct'}},
 'f77e93b2-7d35-440c-b91f-c163dd65d39f': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"tempo"',
     'id': '@1'}],
   'prediction': 'partially_correct'}},
 '04973124-849e-4dce-a129-94353af6041b': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"abschnitt"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"hoch"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'incorrect'}},
 'bd5498f5-59a6-4213-8d11-835f50638577': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"tempo"',
     'id': '@1'}],
   'prediction': 'partially_correct'}},
 '33fe98db-b02c-4b99-9dae-af4cc19fb130': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"gegner"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 '8ede7e83-2142-442b-a8d7-9a13e1ee715a': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"gegner"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 '1901b682-c92d-4c97-bf14-d3b0f6c00493': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"abschnitt"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'partially_correct'}},
 '1bdebf34-079d-43a2-ab59-d55af6279fe1': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"ende"',
     'id': '@1'}],
   'prediction': 'correct'}},
 'c1d769a1-7f05-408e-9292-91cc9b1523d0': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"ende"',
     'id': '@1'}],
   'prediction': 'correct'}},
 'eda4c26c-bf5e-43ef-a4b9-06055102e93b': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"abschnitt"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'partially_correct'}},
 '20f341d1-b5bb-44ad-b15b-f8e4b6084095': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"ende"',
     'id': '@1'}],
   'prediction': 'correct'}},
 'c9f0a898-6bd1-4cc1-8e7c-110cfecc44b8': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"sparen"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"abschnitt"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'partially_correct'}},
 '9824bd8e-f564-4a8d-9a69-ffb485d0aae7': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"anstieg"',
     'id': '@1'}],
   'prediction': 'correct'}},
 '8dfa46ea-5e25-41f1-84b0-6362d3fd2aea': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"ende"',
     'id': '@1'}],
   'prediction': 'correct'}},
 '556fae77-3d55-483f-a87e-3e68a3ab81e3': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '14279077-17f8-47ba-9e6b-59dce7c2856b': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'd1e15b9e-b713-4d42-a03f-71dd19222e03': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'a903f00e-0551-4088-b3b1-da83873415bf': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '40b18791-01b9-4423-81a6-fe3b2da6ed3e': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '06e6065a-3635-4b18-8772-ca710dca362a': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '81afd3b9-14ce-4ffc-9700-939f165e9cce': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'd9886d82-7937-4e1e-bdde-dd9e230484ba': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '4fac94d1-47a3-432a-bfcc-9d81487a6477': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '209e99c4-2b12-4229-b11f-a80f0dc15b10': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '5ad2b555-3904-4d52-ac70-0b1c47caf509': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '43d56eaa-a13f-4c53-b0c7-62abdd3bb5eb': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'd727ff83-208c-4abe-9bf1-1422da0cf78e': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'afc31f2c-e6cc-438b-90e3-dd12f7a6785e': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '90d66015-7d58-4d48-add3-3c5d694d0ada': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'ef7a451e-a3db-427c-9e7d-b340b6edcea2': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '29d7970d-616b-4ce0-8aef-938680e1c3e9': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'e301dcf0-9c18-42f1-819c-7806f3a2015a': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '5fa6b13c-aa46-41c5-858b-9f358aef2f32': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '263b3e2f-6ac4-4b55-82e2-fde6dcbecc8d': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '25d6749e-31bb-4482-8ecc-b14b7d6ed1c8': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '5af0c089-0bd6-4fca-9b99-32e33b562574': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '6dd6bb2f-c1b5-42f4-8d20-5c68a6e3e2fb': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '2836d750-1671-4a3b-b371-deddd1125a46': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '5f7b9bcf-66b5-49ea-9550-e0715d819a2f': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'e5935cd7-6866-451a-b98d-22ccd0d85acf': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '0d05c3a0-8c2e-4d56-bad6-9f1f243d0efc': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '0235de6a-4835-40d8-ae75-0007bd229a71': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'ae0cde40-bd5f-4e80-a252-4b7d1ad9d0af': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'ef140e42-c42e-4d22-a97a-5178736daea0': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '987eb83e-09bf-42fa-952e-59780d79f66f': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '846980f5-7b34-4f10-bdc8-ef22f10b26fb': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '4969b0ed-ce6c-4316-984b-1e4895b65679': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 '047d81da-f98e-4b4d-9883-2462881e9154': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'ab3ae156-eaaa-4fcd-b76f-33d3c616ce37': {'amati': {'literals': {},
   'prediction': 'incorrect'}},
 'b35032de-b1cf-4b90-9916-80e33b002346': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"schaum"',
     'id': '@1'}],
   'prediction': 'correct'}},
 'ed2d0452-6bd0-46d0-ae03-a07f0e93be0a': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"schaumbildung"',
     'id': '@1'}],
   'prediction': 'correct'}},
 '8f28dc34-b525-4346-a5c9-6f4e42973c91': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"versuchsbeobachtungen"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"schäumen"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'correct'}},
 '2384d0d2-9f80-4b45-9c07-0345a685654b': {'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"vegleichende"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"wissen"',
     'id': '@2'},

In [11]:
len(d)

7765

Now we can add things to the original sets.

In [ ]:
with open('/Users/alistair.willis/repos/bea-2026/BEA Shared Task 2026 on Rubric-based Short Answer Scoring for German/updated/3way/ALICE_LP_train_3way__v2.json') as fIn:
    json_train_3=json.load(fIn)
    
json_train_3[0]

In [21]:
json_train_3_amati=[]
for j in json_train_3:
    if j['id'] in d:
        j.update(d[j['id']])
    json_train_3_amati.append(j)

In [22]:
json_train_3_amati[0]

{'id': '2a5d7d84-fd00-4cb1-859c-246604d8e522',
 'question_id': 'bc2d01c9-424c-428a-9909-7114819a31d9',
 'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
 'answer': 'Bei einem höheren Zerteilungsgrad ( hier das Zerteilen der Äpfel ) kommt es zu einer schnelleres Reaktionsgeschwindigkeit .\nDie hat man anhand unseres Modellversuches gesehen .\nAlso können wir feststellen , dass ein Stoff mit einem höheren Zerteilungsgrad einen Einfluss auf die Reaktionsgeschwindigkeit .\nSomit reagieren auch die zerschnittenden Äpfel schnelller .\n',
 'rubric': {'Incorrect': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
  'Partially correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.',
  'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
 'score': 'Incorrect',
 'amati': {'literals': [{'pred': 'contains',
    'document': 'student_response',
    'lemma': '"einfluss"',
    'id': '@1'}],
  'prediction': 'incorrect'}}

In [20]:
d['2a5d7d84-fd00-4cb1-859c-246604d8e522']

{'amati': {'literals': [{'pred': 'contains',
    'document': 'student_response',
    'lemma': '"einfluss"',
    'id': '@1'}],
  'prediction': 'incorrect'}}

In [23]:
with open('/Users/alistair.willis/repos/bea-2026/BEA Shared Task 2026 on Rubric-based Short Answer Scoring for German/updated/3way/ALICE_LP_trial_3way__v2.json') as fIn:
    json_trial_3=json.load(fIn)
    
json_trial_3[0]

{'id': '36646661-efef-4070-bcce-87273ca9a82b',
 'question_id': 'bc2d01c9-424c-428a-9909-7114819a31d9',
 'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
 'answer': 'Durch Zerteilen der Äpfel ändert sich das Verhältnis von Volumen zur Oberfläche .\nWenn die Stücke kleiner sind , ist die Oberfläche im Verhältnis zum Volumen größer .\nDadurch reagieren wiederum mehr Teilchen .\nDie Äpfel sollten also nicht zerschnitten werden , wenn eine lange Haltbarkeit erreicht werden soll .\n',
 'rubric': {'Incorrect': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
  'Partially correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.',
  'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
 'score': 'Incorrect'}

In [24]:
json_trial_3_amati=[]
for j in json_trial_3:
    if j['id'] in d:
        j.update(d[j['id']])
    json_trial_3_amati.append(j)

In [28]:
json_trial_3_amati[3]

{'id': '27bc7e48-c8d6-4c2d-a51d-9a28864eaab3',
 'question_id': 'bc2d01c9-424c-428a-9909-7114819a31d9',
 'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
 'answer': 'äpfel verderben schneller bei höheren temperaturen , weil die reaktionsgeschwindigkeit angehoben wird\n',
 'rubric': {'Incorrect': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
  'Partially correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.',
  'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
 'score': 'Incorrect',
 'amati': {'literals': [{'pred': 'contains',
    'document': 'student_response',
    'lemma': '"äpfel"',
    'id': '@1'},
   {'pred': 'contains',
    'document': 'student_response',
    'lemma': '"verderben"',
    'id': '@2'}],
  'prediction': 'correct'}}

In [62]:
with open('train_3way_with_prediction.json', 'w') as fOut:
    json.dump(json_train_3_amati, fOut)

with open('trial_3way_with_prediction.json', 'w') as fOut:
    json.dump(json_trial_3_amati, fOut)

In [57]:
df=pd.DataFrame([(j['id'],j['score']) for j in json_trial_3]).rename({0:'id', 1:'actual'}, axis='columns').set_index('id')

df['prediction']=pd.DataFrame([(j['id'],j['amati']['prediction']) for j in json_trial_3 if 'amati' in j]).set_index(0)

df['actual']=df['actual'].str.lower().str.replace("partially correct", 'partially_correct')

df

                                                 actual prediction
id
36646661-efef-4070-bcce-87273ca9a82b          incorrect  incorrect
962ea355-6849-46b5-ab50-c74e7c98da50            correct  incorrect
4f7f3884-963e-4c46-8458-a84c6014782e            correct  incorrect
27bc7e48-c8d6-4c2d-a51d-9a28864eaab3          incorrect    correct
8cd711d0-a0be-46af-832a-e9c30cc6ae03            correct  incorrect
...                                                 ...        ...
50ebd5ae-eb16-4284-b22e-ae3169e42058            correct  incorrect
0f922c54-3c13-4683-b7a6-353588b79677            correct    correct
483689d8-0601-4e4f-9971-53803def8af6          incorrect  incorrect
784320e2-1809-4514-a675-a2fc1b230aff  partially_correct  incorrect
d45da693-ca7a-45b1-8ea9-d536f82e8d5e          incorrect  incorrect

[827 rows x 2 columns]

In [60]:
df[df['prediction'].isna()]

                                                 actual prediction
id
725bffc4-89df-412a-a6fc-e7ac15e3d277            correct        NaN
83ab0d14-2a45-4fbb-a3d2-54a28b1b8969  partially_correct        NaN
08bd53b5-7ef5-4d08-aab0-ac14691f9ddf            correct        NaN
c03382c1-8dd6-4c50-8578-5282d8736153  partially_correct        NaN
ec64be94-04cf-47e2-be19-8a7e27c11f55            correct        NaN
8eca0fac-28ea-4c0f-aff9-624ae672fe8c  partially_correct        NaN
8774a3b2-6a6d-42ee-a69a-bc76f8c9153b  partially_correct        NaN
49817c87-8467-41ea-a653-bbe8da29867c            correct        NaN
c89445e1-d808-43c9-8306-c5ba973c9046            correct        NaN
9640a2fe-fd29-4518-9530-9172a716d310  partially_correct        NaN
28865570-4e10-455e-90c5-de18009bfd34            correct        NaN
88345ca2-64f2-4822-affa-8396e3b7e31a            correct        NaN
cb62b3ab-6053-4054-822d-04d64f37ac1e          incorrect        NaN
b4535a3e-926c-46de-8f6c-2cf31019fa07            correct        NaN