# Extractor

This will create a pickle file which contains the info needed for the learner and theory evaluator.

I don't think I need to add prolog/clingo clauses... that happens in the `amati_bea.py` program.

In [1]:
import pandas as pd

from pyrsistent import pmap

from itertools import count
from string import whitespace
import pickle

from compound_split import char_split, doc_split
import phunspell

## Part 1: load in the data

In [2]:
with open(
    '/Users/alistair.willis/repos/bea-2026/BEA Shared Task 2026 on Rubric-based Short Answer Scoring for German/updated/3way/ALICE_LP_train_3way__v2.json'
) as fIn:
    j1_df = pd.read_json(fIn)

j1_df["partition"] = "train"

j1_df.head()

,id,question_id,question,answer,rubric,score,partition
0,2a5d7d84-fd00-4cb1-859c-246604d8e522,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,Bei einem höheren Zerteilungsgrad ( hier das Z...,{'Incorrect': 'Die Schüler:innen beurteilen di...,Incorrect,train
1,9060ce69-53d7-4e47-8237-c939d11e9ef2,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Das Größte apfelstück , also das mildem gering...",{'Incorrect': 'Die Schüler:innen beurteilen di...,Correct,train
2,c5a42d7e-ae48-4c5b-87a3-2db32bbbb773,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,verderben schneller\n,{'Incorrect': 'Die Schüler:innen beurteilen di...,Incorrect,train
3,8207b3a1-675e-42c9-921f-e745cbcdf5f0,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,Durch zerteilen der Äpfel wird dessen oberfläc...,{'Incorrect': 'Die Schüler:innen beurteilen di...,Correct,train
4,7c2e3e09-c34a-44a6-aa43-fb614fbcd129,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Je größer die Oberfläche vom Apfel ist , desto...",{'Incorrect': 'Die Schüler:innen beurteilen di...,Partially correct,train

In [3]:
with open(
    "/Users/alistair.willis/repos/bea-2026/BEA Shared Task 2026 on Rubric-based Short Answer Scoring for German/updated/3way/ALICE_LP_trial_3way__v2.json"
) as fIn:
    j2_df = pd.read_json(fIn)

j2_df["partition"] = "trial"

j2_df.head()

,id,question_id,question,answer,rubric,score,partition
0,36646661-efef-4070-bcce-87273ca9a82b,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,Durch Zerteilen der Äpfel ändert sich das Verh...,{'Incorrect': 'Die Schüler:innen beurteilen di...,Incorrect,trial
1,962ea355-6849-46b5-ab50-c74e7c98da50,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,Zerteilter Apfel = höherer Zerteilungsgrad = h...,{'Incorrect': 'Die Schüler:innen beurteilen di...,Correct,trial
2,4f7f3884-963e-4c46-8458-a84c6014782e,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Je öfter der Apfel zerteilt wurde , desto höhe...",{'Incorrect': 'Die Schüler:innen beurteilen di...,Correct,trial
3,27bc7e48-c8d6-4c2d-a51d-9a28864eaab3,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,äpfel verderben schneller bei höheren temperat...,{'Incorrect': 'Die Schüler:innen beurteilen di...,Incorrect,trial
4,8cd711d0-a0be-46af-832a-e9c30cc6ae03,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Je kleiner die Äpfel geschnitten werden , dest...",{'Incorrect': 'Die Schüler:innen beurteilen di...,Correct,trial

In [4]:
j_df = pd.concat([j1_df, j2_df], ignore_index=True)

j_df

,id,question_id,question,answer,rubric,score,partition
0,2a5d7d84-fd00-4cb1-859c-246604d8e522,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,Bei einem höheren Zerteilungsgrad ( hier das Z...,{'Incorrect': 'Die Schüler:innen beurteilen di...,Incorrect,train
1,9060ce69-53d7-4e47-8237-c939d11e9ef2,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Das Größte apfelstück , also das mildem gering...",{'Incorrect': 'Die Schüler:innen beurteilen di...,Correct,train
2,c5a42d7e-ae48-4c5b-87a3-2db32bbbb773,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,verderben schneller\n,{'Incorrect': 'Die Schüler:innen beurteilen di...,Incorrect,train
3,8207b3a1-675e-42c9-921f-e745cbcdf5f0,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,Durch zerteilen der Äpfel wird dessen oberfläc...,{'Incorrect': 'Die Schüler:innen beurteilen di...,Correct,train
4,7c2e3e09-c34a-44a6-aa43-fb614fbcd129,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Je größer die Oberfläche vom Apfel ist , desto...",{'Incorrect': 'Die Schüler:innen beurteilen di...,Partially correct,train
...,...,...,...,...,...,...,...
7894,50ebd5ae-eb16-4284-b22e-ae3169e42058,67c1649e-b694-4813-be49-abfd65a6798e,Beschreibe Auffälligkeiten der dargestellten d...,Nicht bei jeder Kollision sind die Edukte zu e...,{'Incorrect': 'Die Schüler:innen beschreiben d...,Correct,trial
7895,0f922c54-3c13-4683-b7a6-353588b79677,67c1649e-b694-4813-be49-abfd65a6798e,Beschreibe Auffälligkeiten der dargestellten d...,Nicht alle Kollisionen der Edukt-Teilchen führ...,{'Incorrect': 'Die Schüler:innen beschreiben d...,Correct,trial
7896,483689d8-0601-4e4f-9971-53803def8af6,67c1649e-b694-4813-be49-abfd65a6798e,Beschreibe Auffälligkeiten der dargestellten d...,Hab ich doch in Aufgabe 2 gemacht\n,{'Incorrect': 'Die Schüler:innen beschreiben d...,Incorrect,trial
7897,784320e2-1809-4514-a675-a2fc1b230aff,67c1649e-b694-4813-be49-abfd65a6798e,Beschreibe Auffälligkeiten der dargestellten d...,Nicht immer führt eine Kollision zu einer Reak...,{'Incorrect': 'Die Schüler:innen beschreiben d...,Partially correct,trial
7898,d45da693-ca7a-45b1-8ea9-d536f82e8d5e,67c1649e-b694-4813-be49-abfd65a6798e,Beschreibe Auffälligkeiten der dargestellten d...,Farbe und Form der Elemente .\n,{'Incorrect': 'Die Schüler:innen beschreiben d...,Incorrect,trial

In [5]:
j_df['rubric'].apply(tuple).drop_duplicates()

0    (Incorrect, Partially correct, Correct)
Name: rubric, dtype: object

There's a `Correct`, `Incorrect` and `Partially correct` rubric for each question.

Let's tidy things up a bit so the ids are more readable.

In [6]:
question_ids = {
    q_id: f"q_{str(q1).zfill(2)}"
    for (q_id, q1) in zip(set(j_df["question_id"]), count())
}

question_ids

{'1f3469d5-f6a8-49f4-85d0-d2e156e4cb0c': 'q_00',
 '75333f3a-c1c2-4729-8d61-146800f16532': 'q_01',
 'dfeace94-8239-4f80-b769-1e0bebbc391f': 'q_02',
 '10d57539-7664-4f0f-afe2-51a749036f54': 'q_03',
 '4a79233b-2d16-4c6d-ba9f-53a7bedf49fc': 'q_04',
 'aa16fbaa-d192-46b4-b338-395bfc6bc58b': 'q_05',
 '807991c9-2b51-4c91-88f7-86b0cbc129e3': 'q_06',
 '5c0edfac-2536-455a-8078-3adceeecfa43': 'q_07',
 '838b4e27-f33d-439d-987b-57ddece063ad': 'q_08',
 'afe4a36a-bbce-40da-a70c-03158b57b6cb': 'q_09',
 'c7a7a954-e315-4ec2-90df-48e5a0940e25': 'q_10',
 '4ba62250-a272-4b8f-bf28-eb531661fcc8': 'q_11',
 'da9e0a6a-7fd4-47ad-aa6a-a0f91fda560e': 'q_12',
 '4e3a3e06-40c4-479b-8882-36005aae1e4e': 'q_13',
 'b845b9f0-92af-4805-be05-b8faf5960dd1': 'q_14',
 '33385739-7e9d-4aa6-9118-62e6772f7eb1': 'q_15',
 '4a38efeb-0a3c-4ff1-8320-2197abb410a3': 'q_16',
 'f38d01cf-f8e1-4e68-a11f-162b9cb6f0c7': 'q_17',
 '64393e93-5585-42f9-ad22-ffa71219573b': 'q_18',
 '741376db-a5f7-43a1-abc4-988ff40cf642': 'q_19',
 'e9e8d257-f86c-4ac9-8179-7fa3ce30b88f': 'q_20',
 'ddadb678-ef4b-4f25-865b-82bda9262c1e': 'q_21',
 '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe': 'q_22',
 '738c833f-a6a6-473b-94c9-7793ae9ebc85': 'q_23',
 '90e1e345-e950-4273-8974-9ace5ff17925': 'q_24',
 '650405c5-4f5b-4479-b0a4-7772b5fc2e49': 'q_25',
 '81d2eaef-552d-4748-bad6-b38784de7303': 'q_26',
 '3ece7826-c379-4e51-b23d-ad50296f3a29': 'q_27',
 '6cc84feb-e8e1-4561-8057-452dce98bd65': 'q_28',
 'faf4a6a7-85fd-4cb7-ab8e-1c21b4bbdec9': 'q_29',
 '1f95fd0e-cd6d-4ae2-b8e8-add8adf9d343': 'q_30',
 'bc2d01c9-424c-428a-9909-7114819a31d9': 'q_31',
 '81632115-0e90-4ec0-bea1-12a7f4b95bc0': 'q_32',
 '526bc80e-e028-4e81-8f00-959804ed200f': 'q_33',
 '45917d45-6b3e-40db-b32b-2a6913ae630b': 'q_34',
 '9ef2a4f6-8d72-42b1-a5af-6dc1e8bb74c5': 'q_35',
 'eed7925e-248b-4d88-a809-1d352d705f39': 'q_36',
 '2517045e-4268-4a57-b953-89ab4040a1b5': 'q_37',
 'e937d43d-23dd-49d7-a3c7-0f874e478b3c': 'q_38',
 'e4b30945-ecea-4112-bc13-66fe78bb817d': 'q_39',
 'a1760d86-f7ff-4e7f-9c95-549896c04865': 'q_40',
 '72ec67ad-49f9-4aae-bd03-6efe95ec0947': 'q_41',
 'd74961fe-bfe5-4edc-9dbf-fa6f04c2437a': 'q_42',
 'badc70b3-e8b8-4d54-8b1b-4c25d9b371da': 'q_43',
 '7f600524-3002-4fff-8536-ccbdac8d8a93': 'q_44',
 'b8d67d94-9aeb-4b96-a3d1-d7eebd6a1b9a': 'q_45',
 '669d1caf-b302-4e93-ac7a-aa969b61fb03': 'q_46',
 'bcded41e-7008-4fb7-a64f-701f41dd2ed8': 'q_47',
 '9f80f2c6-db27-4f50-b16b-e6f7b690d04a': 'q_48',
 'e1a10534-6152-4082-aa3e-e0265fa89acb': 'q_49',
 'fa5c7308-3e1f-40f7-a8e0-5d448551afc0': 'q_50',
 '863b0d4d-6f16-4ad1-9228-8806513ef605': 'q_51',
 '0a3fd73f-2ab4-437d-b963-92b569f460bf': 'q_52',
 '93ed3f79-b3e9-41d2-8984-d8e2fa2143e8': 'q_53',
 '3bc01472-a1c1-485a-8e3f-3f6a8fcd186d': 'q_54',
 '46835724-b516-4a38-857e-5f46a31ef78a': 'q_55',
 '37aa9003-c5d4-4d80-ad29-b63118bb9fba': 'q_56',
 '85280bfa-db74-4f0b-a996-35c0decc2185': 'q_57',
 '93b2ea65-14e0-4a3b-bb50-bb4759c44a22': 'q_58',
 'c24f6093-2644-4fc4-b7c9-d798500f483f': 'q_59',
 'b076d670-42c4-46fc-b4f4-07a2d617afd7': 'q_60',
 '09dcf4a4-4f9f-4b77-880e-ed14609ea218': 'q_61',
 '67c1649e-b694-4813-be49-abfd65a6798e': 'q_62',
 'ac4d6b7e-4579-4351-bd94-15086b0f9445': 'q_63',
 '52af038f-7137-4406-bcbb-fb5a0291fd25': 'q_64',
 '826d0863-2521-45d8-aafe-6871679062b9': 'q_65',
 '9546e86e-5b8e-4b0c-8907-2d57551f43ad': 'q_66',
 '18fecb92-5da4-4e60-92cd-0040b817b3f1': 'q_67',
 'e4989914-39f3-4ffb-9fe3-d744938d9983': 'q_68',
 '366020b0-dde2-4af5-8e31-d9f4dc61c6ea': 'q_69',
 '0bf8fd8c-a68a-4491-ae28-be767f335729': 'q_70',
 'be7e5fe8-bd7f-4b81-93d3-2d89cce152c7': 'q_71',
 '90d2761e-010d-4463-afe7-6b3fa2561dc2': 'q_72',
 '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4': 'q_73',
 '2ad4c4b0-5dfe-4667-b344-a00434eeccf1': 'q_74',
 '9a2e7fec-b8fe-49d5-853c-2c0a32c36285': 'q_75',
 'ba753563-faa3-43c6-973d-320e5adc6979': 'q_76',
 'f5537007-c811-4910-8a18-aaa3e61c39f2': 'q_77'}

In [7]:
response_ids = {
    r_id: f"r_{str(r1).zfill(4)}" for (r_id, r1) in zip(set(j_df["id"]), count())
}

response_ids

{'4af8c054-8dd8-4333-aa1a-c5811bb117c5': 'r_0000',
 '25ee90a6-f0dc-4367-9dcf-a8a26a4ff856': 'r_0001',
 '06de3578-9de7-43a9-9d70-bd6ad41684af': 'r_0002',
 '9f9c3b10-8d37-49d4-9e53-8a66067ffeee': 'r_0003',
 '6dacc962-fb14-4022-beb0-46f167bced0c': 'r_0004',
 '7460d293-b13a-4ff5-8cb9-f19cc78d28ff': 'r_0005',
 '57753aa2-cd69-49ff-b6f9-bd2869eaab57': 'r_0006',
 '84f30c8a-9238-4ab6-aa1e-6a402f45e30c': 'r_0007',
 'a8ec06e5-6e7f-472d-8a55-6681642e59ec': 'r_0008',
 '5ead86aa-f1d7-48bc-bd8c-a3cea79c24a0': 'r_0009',
 'eb827966-2bc5-4b6a-b1d7-3ab688d22d05': 'r_0010',
 '5b082d98-ac17-4162-9907-1404fa4925e3': 'r_0011',
 '02295bcf-1718-4644-9c04-393205285b2f': 'r_0012',
 'eddcdbf0-b2e8-48e1-a2df-061b9a39d969': 'r_0013',
 '61c4de77-ad4f-41af-9ef7-f334a786aebe': 'r_0014',
 '20e8be9d-3114-45f4-bacf-8d84b29ef884': 'r_0015',
 '50b33ec3-0e3c-468e-bda9-263a2d762659': 'r_0016',
 '1701d0f1-9e3e-4b94-bdfd-ec630a5cbfec': 'r_0017',
 '1cc1dd01-7472-46ac-bae4-7e02e6a3e5fb': 'r_0018',
 '3b8e297e-e57d-42f1-878c-de5149e701a9': 'r_0019',
 'cab6e6a3-ec2d-417d-abf6-d58466df1e63': 'r_0020',
 'c5b91747-a5a1-4fb4-886b-70bf8b096b13': 'r_0021',
 '5c91f6fe-1b31-4116-ba85-58d1f1419cb9': 'r_0022',
 'c4d2a88d-45a7-4795-9a79-f6798d4e24b0': 'r_0023',
 'fc35dba7-cd38-4e09-b674-099783b36c0f': 'r_0024',
 'fa87ad04-7a6f-4b4b-a59d-ab6bdb307655': 'r_0025',
 'aa2ade57-c797-4b71-a93b-6402eced60f8': 'r_0026',
 '11d18cc0-b3e2-486f-9b06-3377d98de1b6': 'r_0027',
 '858f2cab-1ac7-4153-8db0-5d5cd5d0d28e': 'r_0028',
 '963f1463-4fef-4c8b-9d27-e4e3ccb0f034': 'r_0029',
 '794e4437-c579-4876-bd5b-eb26b54a23d9': 'r_0030',
 'cad76f0f-1123-422d-948d-2a93fbfc7fac': 'r_0031',
 '5564d8b8-a3ec-4fd1-9184-95fd81b6dd80': 'r_0032',
 'fcaea542-9cc1-4eb1-b718-f3c822a67fea': 'r_0033',
 '100be5b8-0f8d-4107-9fc6-737f4f20be97': 'r_0034',
 '355f1cf7-828f-4d57-9d1a-42ccad76d8bf': 'r_0035',
 'de652ccf-8448-4cdb-98b4-ac13d2176b93': 'r_0036',
 '7192e935-80e6-40ac-8fd2-0d01ebc1031b': 'r_0037',
 'f23c1bdc-29c2-4a2c-8393-f445cc23d2ef': 'r_0038',
 'd8a8e799-4e28-4f57-9b89-281464d6a3a5': 'r_0039',
 'bb3900f8-40a5-488c-bac9-f98e911a3639': 'r_0040',
 'b39d636e-97e0-46b5-9665-f559676364c5': 'r_0041',
 'f990f99c-4a8f-4cea-b2c4-d0f90a5b0205': 'r_0042',
 'd54853f8-8348-4fa4-ba21-b6fef3b5246a': 'r_0043',
 'f04962b5-ba76-4a95-b134-e99ed3364fa6': 'r_0044',
 'a1a1a687-a819-4b0a-abfd-716c52f5bd1f': 'r_0045',
 'ab4ddb76-eb44-42fb-a289-3ad9b05cd3c4': 'r_0046',
 'be3e575d-a251-4713-8fe8-072413ff5760': 'r_0047',
 '19cc03a7-1d5d-4e4f-979d-d381257093a0': 'r_0048',
 '7f9d7b28-6ca9-478c-aeea-9d76da83ef8b': 'r_0049',
 '0f82fd2c-7534-4b57-864b-293c2846b1c0': 'r_0050',
 '459aeb7d-d603-4f03-8de9-604063a139ad': 'r_0051',
 '9418eddb-c7eb-4f9f-8372-dba599d86107': 'r_0052',
 '31c61d88-edb3-476c-8614-dbd4b4fb0ee8': 'r_0053',
 '38f89f7b-ca9a-4d14-8a1d-684d64f82bf1': 'r_0054',
 'a47e3341-759b-43a7-af60-d7d7b5ad5374': 'r_0055',
 '2530946d-22de-4ff4-bd41-5982b6a54c61': 'r_0056',
 '905b5de0-75a7-4d95-a1e8-882c09e2b6fe': 'r_0057',
 '79db0f2b-8257-4d91-82f1-223fd0289d18': 'r_0058',
 'd64bf08d-7098-4162-8a0d-a3ea49c8dc21': 'r_0059',
 '9e148b59-2569-45e2-9f17-e2c5d121e635': 'r_0060',
 'f4935f9c-cf08-40f8-9825-5d3b6606d73b': 'r_0061',
 '42f9c01f-49c5-4438-b36b-3202fa620930': 'r_0062',
 'd05a536a-00fd-49a2-9b7e-e758040226be': 'r_0063',
 '2bb17505-452e-4ddb-a628-38b5ca521d35': 'r_0064',
 'fbf35cb7-050c-4328-aa2a-60ce65ff9054': 'r_0065',
 '7ff5f816-ab97-47e5-a273-677c8fba21f3': 'r_0066',
 '0da49043-53cb-4e00-ba49-ee3a2938cd72': 'r_0067',
 '7f039cea-ede0-47c1-8cdd-f20de56a6120': 'r_0068',
 '80dbb947-3e6e-493a-ad0d-5565c52a3402': 'r_0069',
 '96325c51-3190-4e11-9862-e50e313c9194': 'r_0070',
 '1212d910-31f7-4461-9693-8999aa16d63e': 'r_0071',
 '38bc3a03-5961-4180-b43d-b706aa3611aa': 'r_0072',
 '0827c16c-f24e-49fe-b2e6-d52d167c0808': 'r_0073',
 'f5014255-0229-423c-8053-3fcb167046db': 'r_0074',
 '8ed79fda-4468-4c68-9517-05418807bbcd': 'r_0075',
 '802f8ca5-81ed-469b-b116-0e16baef9ac6': 'r_0076',
 '066674d2-5230-4f8d-b8d5-5f465ebded00': 'r_0077',
 'd0d2ebec-61ee-41d6-8dd2-cf4616c82f71': 'r_0078',
 '180f164a-092a-4ab5-b07f-8eb4db0040f7': 'r_0079',
 'ba0d5927-a7b5-4ff4-a977-c3f716a0876d': 'r_0080',
 'ffc726ff-693e-4c69-b781-0e0fb579350d': 'r_0081',
 'f46ebb66-a8ba-4e0c-9f71-0dd0a7f71ced': 'r_0082',
 '537929c1-eda4-45b1-96e2-aff0cf9681d4': 'r_0083',
 '74690b87-40bc-4520-ba01-fbb688c0d2b1': 'r_0084',
 '66cd8590-8a36-4a8f-9d42-8bfa4529ae8d': 'r_0085',
 'd57cb3c2-48e6-4bec-be2d-06c094a3ebc5': 'r_0086',
 '4898b037-70d6-43ea-a14a-b6b0001a32af': 'r_0087',
 '68002eed-8d1e-4035-bc18-fd35f69bc9ed': 'r_0088',
 '64073433-7571-483b-be4b-0cf7c3c154fc': 'r_0089',
 'f6fa3e2f-d126-43dd-9e6b-8e74a04b16b9': 'r_0090',
 '665d6781-718f-46b4-9f00-60564d0416dc': 'r_0091',
 'b431cfe7-cb36-4b18-86bd-08b228a9ff69': 'r_0092',
 '6abf0ae6-c655-42ac-85cf-a8aa446844eb': 'r_0093',
 '958fb7d7-6db3-4cb3-b6c9-0d482c6a7255': 'r_0094',
 '84109dde-e558-4cad-9fa2-c13e272da0eb': 'r_0095',
 '116f68e6-a181-4dca-988c-c7dc874a4dd5': 'r_0096',
 '34d0888a-8d78-4a49-a5b8-cba59b99bb5a': 'r_0097',
 '27536134-a7e3-4162-9d48-a1bec7cfb3e6': 'r_0098',
 '0d18b702-dbb6-4cb2-a7e6-ac2e46e0e7cc': 'r_0099',
 'f18f9a9b-62e8-4d93-b011-423c81590a70': 'r_0100',
 '3286a673-b723-4b66-ac52-06bb3d19585c': 'r_0101',
 '3e25b068-2dac-408e-b788-117a7807d985': 'r_0102',
 'b928f496-97db-4013-8df7-475ea87adb88': 'r_0103',
 'f02738fe-4a75-4dea-88e2-7a40ea84d786': 'r_0104',
 'b5adf630-278b-45e3-aa12-fc56b9b69297': 'r_0105',
 '5cc5a53d-4b50-4e3a-8d97-68dab2e971a7': 'r_0106',
 '00d7bbd8-cb2d-4de2-b7a7-00b18485f4ba': 'r_0107',
 'd418d5d4-b349-46b6-b814-a8b23e7b6106': 'r_0108',
 '103b21fe-75a0-4146-be41-968525b618a4': 'r_0109',
 '685528f1-8ec4-424a-a13b-6e111f651886': 'r_0110',
 'd8e74bed-f815-4f18-86c9-2ab2c79115f3': 'r_0111',
 'c0ba3b10-24de-4bcb-a943-bc8f9b105ecb': 'r_0112',
 'a7649280-be04-4531-a4c5-e321bb71bae1': 'r_0113',
 'b5c71e85-b027-4fb4-8f3e-fd005483f8a6': 'r_0114',
 'b35032de-b1cf-4b90-9916-80e33b002346': 'r_0115',
 '65c4eb3a-4cee-49ae-a9fd-60b79434cdd1': 'r_0116',
 '2337f2cb-2557-44df-a00e-77005f382322': 'r_0117',
 '7e078797-9cb2-4719-a664-9eb9855e52da': 'r_0118',
 'ed2d0452-6bd0-46d0-ae03-a07f0e93be0a': 'r_0119',
 '136d3665-8e05-474d-9242-a2427f3911bc': 'r_0120',
 'cd425d16-9818-4887-a7cc-736acf36e0ba': 'r_0121',
 '9292f8be-50f2-45c0-bc01-1e3d43c0948e': 'r_0122',
 '2e36a01f-6c46-428e-bd3d-8b62b7517431': 'r_0123',
 'a6e7682f-89b5-4a44-af6a-d2ef7e83fc1e': 'r_0124',
 'c30a49b2-5ca5-4bf6-a6d3-1ae5aafb05a4': 'r_0125',
 '538d9ea3-3bea-4254-8798-49c9a8d7570d': 'r_0126',
 '7573280a-f014-4836-98ce-73adfd8352f7': 'r_0127',
 '9408453f-9852-4a9e-86a0-cffb0dfd0229': 'r_0128',
 'ec9c3b1b-4304-46f4-bc43-2e29cfa2154b': 'r_0129',
 '29186c17-bf88-4b20-99fc-33a588d5aeba': 'r_0130',
 '5bf1fb93-2474-4b6c-b517-f4370c797e4b': 'r_0131',
 '4d24138b-1843-45a4-baa0-5f72f1ac44f3': 'r_0132',
 '92b82cac-9ada-41a2-9764-71cf97b03e27': 'r_0133',
 'd6180f6e-c0b2-4e28-9d02-a48375ac7114': 'r_0134',
 '23eca215-116e-4f1d-b433-89549b6ce364': 'r_0135',
 '9cf06d4b-6479-4be0-849d-29b9270a78a6': 'r_0136',
 'e5eb5c54-8482-49c1-a31e-bae7bf0c87fe': 'r_0137',
 '55d69721-39b2-40d0-b504-35129c4b1817': 'r_0138',
 'c4087296-99bd-47bc-96ca-f5e5515887fa': 'r_0139',
 'b433eee0-195f-4348-bea2-3b3c1a8e4ca1': 'r_0140',
 'e4f18661-38ff-471d-b429-28f8687e6315': 'r_0141',
 'bd65ae6c-d5b8-46f8-a4cb-78bae989f385': 'r_0142',
 '20287567-b9c1-41c5-b3fa-40363dca39b0': 'r_0143',
 '7fe9fb32-169e-41af-875b-c48e0c690e3b': 'r_0144',
 '1009f6ae-fb94-4a14-a3d5-100041ff42fc': 'r_0145',
 'd0901618-e484-45b9-87c7-7789b70ad418': 'r_0146',
 'a0602231-3446-41e2-ba82-6502912dde39': 'r_0147',
 '97ffa4d3-17be-428c-8e66-25039036cd4f': 'r_0148',
 'c4638d2f-25d2-4364-b61a-f6da3570b792': 'r_0149',
 '6a7b0157-ba2d-4196-a0fc-b2b6d92e5e92': 'r_0150',
 '07fed870-0d89-4d9d-93c6-201a30599107': 'r_0151',
 '2f8b48a4-d7a7-4e5d-bfc1-6c7e6c2cb7cc': 'r_0152',
 '46a79fb9-4038-4534-98e3-fb3fd18d47f2': 'r_0153',
 '8afdc3eb-c8b1-4254-b07f-66e42cb15624': 'r_0154',
 'b92bd0e9-dd0b-4bde-9354-b25bf1b5c8c8': 'r_0155',
 'c51287a5-555b-4a58-9174-59aa32173057': 'r_0156',
 '4f6b3e05-a6b7-44ee-8a6c-ba12ac24062e': 'r_0157',
 'b59c37c5-b680-45e2-9758-0a3e6f63d72d': 'r_0158',
 'b65f7a08-ff51-46ef-a033-ae67d8cf42fd': 'r_0159',
 'f763e9ea-4ac6-4746-a025-5d6bea47a657': 'r_0160',
 '4ff5c031-3a5c-4ff0-93eb-d05d20910c65': 'r_0161',
 'ba40f7cb-f64b-4faa-8546-1d5c04df164e': 'r_0162',
 '52259c6a-66a0-46bb-80ad-7a9619508566': 'r_0163',
 '3cee8243-ae9e-411e-bb67-e5eb66a8a931': 'r_0164',
 'bb08d5f4-73aa-4014-9ca5-35694f4bed5f': 'r_0165',
 '0ede0159-afc6-48a0-8ee5-b0aba3799f1c': 'r_0166',
 '9f792e45-4e81-44ac-9d8e-dfd2a472c043': 'r_0167',
 '566a8a9d-ebff-4dea-b054-f7bfdcabdd7d': 'r_0168',
 'e588b65c-e782-4a8e-9502-371ebf3b9635': 'r_0169',
 'c605f166-0f54-4939-89a6-39e19dc68a96': 'r_0170',
 '4af46f19-3f5f-40ab-a66f-ec929fd110a3': 'r_0171',
 'fcd3d2e9-4511-4bb2-869c-2bbc84852611': 'r_0172',
 '03c92dda-1ef1-42bb-9617-25c572ca67b1': 'r_0173',
 '5fc57581-224b-4d45-aee0-48fe839660fd': 'r_0174',
 '360fe0c3-89c7-4139-9073-c8dc67f04f39': 'r_0175',
 '12590b77-bda4-4d47-a638-7aaf5507328b': 'r_0176',
 '6e6446ca-d5d9-46b5-82b8-90e2407d22a7': 'r_0177',
 'f6c99278-c92a-4ab9-943b-5b203f47c263': 'r_0178',
 'fc783e91-f400-4123-9619-1120dfc48358': 'r_0179',
 'a262cd7c-b7d7-4dd2-baf1-4e9396717041': 'r_0180',
 'd8cdbfd8-bb48-4cee-bd81-c50e0b90f579': 'r_0181',
 '2ca7d813-c887-4f92-b2a8-9845ec75306b': 'r_0182',
 'c4b7fad8-3bb6-4ed0-bf3e-1d8208307bb0': 'r_0183',
 'fbfbb081-d031-4cb7-8b18-bb70db9d0fe3': 'r_0184',
 '082b9d68-a2ea-4b18-8bf8-9cb49b7e5680': 'r_0185',
 '6decd5e0-8c33-4741-a8eb-d3e9dda067f3': 'r_0186',
 'aecc08b8-46ed-4a7a-a793-e46978144b6b': 'r_0187',
 '4b312568-90d8-4925-ac5e-31a6631b01ec': 'r_0188',
 '86e920e9-42eb-4a75-8b47-9e326f8b9a89': 'r_0189',
 'b7a34c03-2a08-44c0-a320-a911f29c1f41': 'r_0190',
 '45a633c4-1381-46e1-8408-5cf4e0626af6': 'r_0191',
 '210ef737-a1f9-449e-8612-55bbb1da6dab': 'r_0192',
 '3eb72055-943b-4a35-964b-e851ea7ba1c4': 'r_0193',
 '97ce9fb6-0b4e-41e3-8e9c-95959b4eeaac': 'r_0194',
 '6a928603-6987-4a45-9148-814f114a4ad7': 'r_0195',
 'c480d9f5-c18f-4c67-9121-69c7412b8c88': 'r_0196',
 '644417de-a9f0-4bc3-a117-8053bca985a8': 'r_0197',
 '04ecb025-11bd-4352-b1ce-f8e0d6e4f528': 'r_0198',
 '4ae6c495-44c2-4040-9d22-f6502e3b46e2': 'r_0199',
 '9e965d3d-fafb-499f-a3c9-4a1fc1e3b616': 'r_0200',
 '6aad3700-8886-49b5-9717-98fe79d0f134': 'r_0201',
 'e367815e-5dc2-44ca-912f-4832130b73eb': 'r_0202',
 '2a57415a-d7f3-4309-bb79-117c1b4d0aa7': 'r_0203',
 '423ea3a0-db86-4b0f-99aa-c40fead6ad70': 'r_0204',
 'f0881f71-1640-4950-be39-1eaa34b45d85': 'r_0205',
 'e3755948-5332-49b6-870c-719606b6091b': 'r_0206',
 'a27af107-38be-4cfe-b69d-6de9871a1d05': 'r_0207',
 '0ef44da9-7317-4719-97a5-e758ccdebf01': 'r_0208',
 'ce264ce3-5c72-4a7d-abb3-70be79b57380': 'r_0209',
 '5179dedb-afd1-4f0d-a535-a6e1a9c69bee': 'r_0210',
 '4c11ea70-a440-457d-a487-0b85c73c7709': 'r_0211',
 '81b64f46-8903-4eb1-8557-4121584aa7dc': 'r_0212',
 'bc605ab7-3cfb-4a56-bd0b-249309e2929c': 'r_0213',
 '13bdd7d7-70fd-4291-9523-34e41273c076': 'r_0214',
 '65e2af44-835c-445a-b12a-7b7247be9bf8': 'r_0215',
 '047d81da-f98e-4b4d-9883-2462881e9154': 'r_0216',
 '4deacff2-b894-4aa6-b6e4-43709808c8d1': 'r_0217',
 '548483ba-b295-4d24-bcfe-36d6fec7ba32': 'r_0218',
 'd54d20c6-16cf-46a6-8b7c-13c5f836a73f': 'r_0219',
 '5f47a3c6-d5e3-4655-8e03-d86224a0e93d': 'r_0220',
 '93b1fabf-9e7a-45ba-913e-68579f92b401': 'r_0221',
 '813fdc8d-06c8-4e26-9a9d-1b78b66bad9a': 'r_0222',
 '3215b4ea-5ae3-4aeb-bb3d-036fca1f5e3d': 'r_0223',
 'dda2c8d5-aa9e-4fb5-a492-330afa9575cf': 'r_0224',
 '0f7eef8f-bcc7-4ceb-a959-c59b7bf43690': 'r_0225',
 '382c3373-60d6-4abf-8319-c64de7390e14': 'r_0226',
 '5f7ac0ca-a621-49e6-aa6c-8713240514ed': 'r_0227',
 '752bf74a-7891-4e1f-903e-61441abea9d6': 'r_0228',
 '961762c5-5035-48bc-9556-b7ac39fe3f46': 'r_0229',
 'e172b860-dab4-4966-92bc-f82424c2baa9': 'r_0230',
 '29ce46b7-eddf-4eab-9af2-6f37390cb245': 'r_0231',
 '47ca670a-4bd2-4c07-8ba9-4bc0529f6bec': 'r_0232',
 '4609aa80-771d-48f8-b447-51ee123599b0': 'r_0233',
 'c15500cf-dcf7-4a69-afc6-b41e8b54cac1': 'r_0234',
 '2cfefcee-ceb8-4a89-a577-005a627213dd': 'r_0235',
 'c17a2e08-db50-4912-9887-51a5f26bcffe': 'r_0236',
 'c50a18c4-4e9c-4139-ba40-49c8fbf32a21': 'r_0237',
 'ac42abb9-5a19-4621-a01b-b8f445baf3f3': 'r_0238',
 '843e0c75-e8bf-4934-bd6e-d149bec66fdd': 'r_0239',
 '0d7ec820-6277-4232-91e9-0980927ba1af': 'r_0240',
 'f67c36b3-34fb-4546-a09e-e7225463d911': 'r_0241',
 'c4f0b5fe-673d-46bf-ad03-a7000c8e27e8': 'r_0242',
 '9db4686d-938d-4cce-9d7a-0ca567f650b0': 'r_0243',
 'c8fcf015-d8c0-4822-b8d1-1bde818fe164': 'r_0244',
 '08a26a6b-88fd-46be-a7f4-304e46c0f81d': 'r_0245',
 '99839a93-a325-4e9f-841e-db75079ec4be': 'r_0246',
 '67554676-6dc6-4777-940d-452bc1653e16': 'r_0247',
 '0a13697d-3c32-41c9-b8e8-d4f697925f9c': 'r_0248',
 'a3349be8-ea96-4555-a40f-03f1f5536ffd': 'r_0249',
 'f401b509-49fc-45bd-b1fa-9de461b0567b': 'r_0250',
 '374045c3-06a0-4609-abe1-e879cabcfef5': 'r_0251',
 '4006206e-1277-4450-aff3-4e962d4aa35f': 'r_0252',
 '77f6ec4e-ece1-4cb2-a8bb-80c7557febab': 'r_0253',
 'e53bf604-403f-4987-aae1-025387686365': 'r_0254',
 '8f241a6e-8138-49dc-8573-bfbf6ee1c4cd': 'r_0255',
 '6c139ecb-b9b1-46a3-95dd-47eb09186a34': 'r_0256',
 '291703fa-186c-4469-8536-e8a70d001200': 'r_0257',
 'a665e92b-6d89-429e-83a2-d8fad5e71dcf': 'r_0258',
 '0c9e6273-86f3-4e00-ba65-c2226993aa72': 'r_0259',
 '8d601a41-f667-4f2a-b4ef-9ddf511924c8': 'r_0260',
 'b62b022b-4657-4c5f-af43-4a3be94b6906': 'r_0261',
 'd4de6905-3ae9-43a6-b75f-3a66dd3a861a': 'r_0262',
 '89fd61ae-1439-484b-88be-8ffb49958707': 'r_0263',
 '7651b1b0-c3fd-4e1b-84d5-471972581b0b': 'r_0264',
 'f3555c0f-26b5-458f-9f36-fc66270b50aa': 'r_0265',
 '0051ae3d-4e49-4327-ae24-8753658e1a36': 'r_0266',
 '15d1a934-f01b-4084-8a28-3e87580503c7': 'r_0267',
 'c3815932-6715-443f-8629-d56e4c182b63': 'r_0268',
 '860a639a-aeca-4975-b245-e9db165345b1': 'r_0269',
 'bf1aa05b-c2bb-4e34-839c-93ba6589179e': 'r_0270',
 '0e04f3cd-841b-4398-b9a7-691faa96603a': 'r_0271',
 '5354d35f-5479-4643-a56d-00b546b8c4e7': 'r_0272',
 '5b061223-5a43-40f9-b013-8cded5f2a4b8': 'r_0273',
 'a251e88f-378f-4155-8ce8-eefe189fddc7': 'r_0274',
 'aa4bf911-958a-4ddb-af91-3147aae270a3': 'r_0275',
 '81b85afb-7e1a-450f-a6c9-08ffb5358319': 'r_0276',
 '7f649874-a9cc-4a65-8490-b83a1c6bd322': 'r_0277',
 '8f28dc34-b525-4346-a5c9-6f4e42973c91': 'r_0278',
 '161c999b-638d-4ebf-946b-115ee6a14e83': 'r_0279',
 '45727d5e-4488-42ea-8be6-a64a3537cdd6': 'r_0280',
 '3341f446-cae4-4103-94ac-e5ded56aa63e': 'r_0281',
 '1fbad034-5ce0-4a56-873f-3c127783a48a': 'r_0282',
 'bd268f2a-6fdb-45b2-aae2-bbfbfae4ac35': 'r_0283',
 '49b6c703-49c5-4ade-a46f-2aa6fd2b113a': 'r_0284',
 'b8a6703c-90d8-45d2-84ca-497d5629cd6c': 'r_0285',
 'cb82ca07-5c34-49f6-a32e-91fedf50c2dc': 'r_0286',
 'b2d1a6ea-c22c-49c2-912d-6a59f9da21e0': 'r_0287',
 'fed1fdf9-f7c9-4b4e-98e4-5079f09ddf36': 'r_0288',
 'aa9440ae-e02e-445b-b212-7a33da489269': 'r_0289',
 '121a185a-e946-4ca3-af2d-e54f712e1fae': 'r_0290',
 'b9fa63ab-9722-4e9d-b8a5-150d269d183d': 'r_0291',
 'e21d6de5-5af4-4337-baee-a52602b5ceec': 'r_0292',
 '49714d60-6147-474f-91ef-048c7e30c9df': 'r_0293',
 '8dfbaee0-2807-4c10-88b5-4f9a079d2afa': 'r_0294',
 'efbb2ac2-cc34-4c4f-857a-f885146833a5': 'r_0295',
 '59c94e11-72b5-413a-bba8-d1b3ad0ddea2': 'r_0296',
 '2621e1ab-4e20-49ea-b195-1aa211693792': 'r_0297',
 'ed9953dd-c3d1-436e-92e8-67b834087a8d': 'r_0298',
 'eca60de8-7b44-42a7-97b2-12486180dcbb': 'r_0299',
 '511694f8-789d-4e73-b985-cf881ae8d979': 'r_0300',
 '84e57f15-5064-44bd-a4ef-973262092df2': 'r_0301',
 '86cfc67b-9134-4db7-9f10-07dd6f24ba63': 'r_0302',
 '753848d6-b7a3-4076-a2d2-88364b6e824c': 'r_0303',
 'b2a963b7-569f-424a-9d00-e7280b6ca7fb': 'r_0304',
 'c44a7366-60f3-4e27-b0e6-4213b22cdb55': 'r_0305',
 'c0458ca5-b686-49dc-b674-9b0ba6e47baf': 'r_0306',
 '5e1abbf6-ebab-4622-b9cd-cdcc1990b2a9': 'r_0307',
 '3e645dda-28f9-45b6-9e8c-2ed7e510dea3': 'r_0308',
 '73beb94e-8f61-44c5-a128-3b330dd37ccf': 'r_0309',
 '9d34d0a7-1dde-4643-8396-8e9fdec3dfe6': 'r_0310',
 '6233d743-9887-4077-aeb6-d6c6a5b0fdf7': 'r_0311',
 '20377784-b01c-4c50-a990-53a8e963860c': 'r_0312',
 '6fa6bcf6-384a-4bbe-8afe-89ace72b89ba': 'r_0313',
 'f3920375-6ac5-4b9e-8a77-0a55827a131a': 'r_0314',
 'd35f8f22-0150-49f2-b23d-94468540a8b5': 'r_0315',
 'cad50136-f0ce-4f36-9470-2c6c39a70323': 'r_0316',
 '05885a2d-6bd6-4cbe-be16-7f9e8949907a': 'r_0317',
 '7ed106fd-b3b8-4c2b-a4d6-907e359088d1': 'r_0318',
 'b711286f-316e-4b09-a042-6c22d8cd75ab': 'r_0319',
 '3e9f3d48-ea96-40c7-865c-60d69367e593': 'r_0320',
 'c35a6b1c-ea70-4229-9da1-d2e4624a3980': 'r_0321',
 '9142cfca-8268-4752-bc81-ee3c3a2304a7': 'r_0322',
 '9f35bc11-14de-4811-9827-7b599574ca86': 'r_0323',
 '6497593e-4f9c-463e-aa9d-8df3721f733c': 'r_0324',
 'c8865990-9fd3-4baf-a648-6546663db0c1': 'r_0325',
 '8029c569-6d39-4cd7-a131-109ce15a2e81': 'r_0326',
 '3ffedb84-b918-4f4c-b63f-01548a27302a': 'r_0327',
 'b4338232-4d0b-4b13-b4da-52e6c91d44e3': 'r_0328',
 '36fe340b-b829-4b53-94a5-096c6bf05d6f': 'r_0329',
 '9a3fa743-b5ad-4e3f-85cc-46911139287d': 'r_0330',
 'f98729fe-3b46-48ce-9416-0c13ca48f88c': 'r_0331',
 '13491e9f-882b-4b90-82f6-eaa8eed0e26c': 'r_0332',
 'e1aa9b98-61b0-40ff-8211-9fa8b186bf5b': 'r_0333',
 'ecbe70cc-b81a-44bd-bdc4-a49182648194': 'r_0334',
 'f9b9e767-4447-49dd-9698-1b33784f95bb': 'r_0335',
 '688ac456-1bcb-4db7-97de-4775ab97fe5f': 'r_0336',
 'dea95b47-448c-4e92-8b48-d400612f74b7': 'r_0337',
 'b1bb214f-24e2-497a-b26c-80e1cda608cd': 'r_0338',
 '5905957a-dbbe-4800-9914-f76620021fed': 'r_0339',
 '78c2994e-c023-4ab1-b480-6f2fc8fc26bc': 'r_0340',
 '1ca06bbc-19bf-4712-a63f-a16e5b4b5e91': 'r_0341',
 'f8147fd0-8ee0-49d1-9699-4642d340d6d5': 'r_0342',
 'a4747a39-64ab-41a3-a645-f539648ecde6': 'r_0343',
 '6b2d9f96-c6e4-46b6-a5a9-6138ae4aec20': 'r_0344',
 'a3b75375-dd8c-4022-a4c4-c7c4dfdb971a': 'r_0345',
 '3f8641e9-e457-40d9-b2ac-e76f2514e7e0': 'r_0346',
 '2d573a2a-0b7c-488f-bac4-c076c511d235': 'r_0347',
 'efb17bd5-45a2-4606-a347-9744a6d115a2': 'r_0348',
 '947236a8-3bed-4fb1-836d-7021214efd19': 'r_0349',
 '4fae6aca-b22e-46fc-a7c8-4698f95eed11': 'r_0350',
 'fc8684da-1eef-4848-b4e8-e78286c20658': 'r_0351',
 '2253c92f-b438-4c0b-afa9-98b33e8f1631': 'r_0352',
 '841d120c-6b85-4b06-838b-8ea186437297': 'r_0353',
 'b4837301-829a-4875-afa1-20640588c02b': 'r_0354',
 '288f5dd7-4e58-4db8-942b-a20e11933743': 'r_0355',
 '430a7b65-be75-4c6b-997a-2a6fa202a42d': 'r_0356',
 '7e036cba-8e18-4860-94d6-52d81477e5ae': 'r_0357',
 '7dd7e99f-9c01-4921-b7f1-87bdd8915bfa': 'r_0358',
 'c9ee5639-45ab-45ac-a367-ea6bab7b5a86': 'r_0359',
 'd3ced6f9-5b79-44a2-980f-6080a910e189': 'r_0360',
 '2e29e0a0-930d-4023-ab48-a1c66dc89495': 'r_0361',
 'c98474a5-851b-455c-9973-5694d8578bbb': 'r_0362',
 '25439874-a8c1-4d87-8a57-f889c86359fa': 'r_0363',
 '4a11c672-78ee-421c-8f49-dbe0993bc20f': 'r_0364',
 '5e97ed83-e7e3-45aa-81b0-ebbafdbbc110': 'r_0365',
 '90e2414f-868d-4976-a2a3-b2d5a792497f': 'r_0366',
 '7a7541af-4cd1-4460-8f40-2096908cdb32': 'r_0367',
 '35dc4cb5-210c-411e-8876-89c4878a0711': 'r_0368',
 '7952b997-a41a-4f23-858f-e4d150643455': 'r_0369',
 '82a0fc49-b72a-45f3-9282-b25042ccf98e': 'r_0370',
 'e6274832-0f14-45de-95d2-24653c4b38ff': 'r_0371',
 '21e7fd02-5c0d-450e-9dda-db493e5c0319': 'r_0372',
 'bc497797-9a0d-46a0-9318-43a81d5e0a6a': 'r_0373',
 'c528afb7-fd9f-4c10-bfcb-eb498cb8cf45': 'r_0374',
 '556fae77-3d55-483f-a87e-3e68a3ab81e3': 'r_0375',
 'bb98932d-bb19-4390-a46d-176c7d28b9b9': 'r_0376',
 'dcc4fdeb-0dd2-49ec-87c5-788af0d38c0f': 'r_0377',
 '3239564d-2856-4d46-9d38-eeb86a426a5a': 'r_0378',
 '07cf8c34-4a35-4d99-8ad4-8e1358fbd089': 'r_0379',
 '28c5e857-e515-4323-9150-a7e4564a8e79': 'r_0380',
 '2384d0d2-9f80-4b45-9c07-0345a685654b': 'r_0381',
 '3eff5c32-7e9a-4510-9774-cf8156e86c8b': 'r_0382',
 'fc66da2d-9b12-4e59-a0c8-f654f55c52db': 'r_0383',
 'c7638b4e-9b0e-4608-9d63-222d1238de44': 'r_0384',
 'ba4b8200-fff2-4bed-9e32-1fe40a637a8a': 'r_0385',
 '51cca083-50f1-4d41-81d7-2c3554bff7ef': 'r_0386',
 '2b66d5d4-73ec-40a7-8c88-84ec6b74d8f2': 'r_0387',
 'fbbb020d-392b-4075-a8b4-d24de63f7029': 'r_0388',
 'be050787-b5ad-4e70-b390-92d5f46d101f': 'r_0389',
 '5bf058b5-aa21-41f2-8b38-05cb01c3d5c3': 'r_0390',
 'c11a43d6-8837-4776-95d4-f2ec9595633e': 'r_0391',

In [8]:
id_mapper = pmap(question_ids).update(response_ids)
id_mapper["67c1649e-b694-4813-be49-abfd65a6798e"]

'q_62'

I'm going to convert the score to lower case as it'll make everything easier in clingo. Also need to replace 'partially correct' with 'partially_correct' so that there's a single atom.

In [9]:
# Note to students: don't write code like this!

bea_3way_data_df = (
    j_df.rename(
        {
            "id": "original_response_id",
            "question_id": "original_question_id",
            "answer": "response",
            "score": "capitalised_score",
        },
        axis="columns",
    )
    .assign(
        response_id=j_df["id"].map(id_mapper),
        question_id=j_df["question_id"].map(id_mapper),
        correct=j_df["rubric"].apply(lambda x: x["Correct"]),
        incorrect=j_df["rubric"].apply(lambda x: x["Incorrect"]),
        partially_correct=j_df["rubric"].apply(lambda x: x["Partially correct"]),
        score=j_df["score"].str.lower().str.replace('partially correct', 'partially_correct'),
    )
    .drop(["rubric", "capitalised_score"], axis="columns")
)

bea_3way_data_df

,original_response_id,original_question_id,question,response,partition,response_id,question_id,correct,incorrect,partially_correct,score
0,2a5d7d84-fd00-4cb1-859c-246604d8e522,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,Bei einem höheren Zerteilungsgrad ( hier das Z...,train,r_4856,q_31,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,incorrect
1,9060ce69-53d7-4e47-8237-c939d11e9ef2,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Das Größte apfelstück , also das mildem gering...",train,r_3158,q_31,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,correct
2,c5a42d7e-ae48-4c5b-87a3-2db32bbbb773,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,verderben schneller\n,train,r_1090,q_31,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,incorrect
3,8207b3a1-675e-42c9-921f-e745cbcdf5f0,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,Durch zerteilen der Äpfel wird dessen oberfläc...,train,r_3214,q_31,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,correct
4,7c2e3e09-c34a-44a6-aa43-fb614fbcd129,bc2d01c9-424c-428a-9909-7114819a31d9,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Je größer die Oberfläche vom Apfel ist , desto...",train,r_6138,q_31,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,partially_correct
...,...,...,...,...,...,...,...,...,...,...,...
7894,50ebd5ae-eb16-4284-b22e-ae3169e42058,67c1649e-b694-4813-be49-abfd65a6798e,Beschreibe Auffälligkeiten der dargestellten d...,Nicht bei jeder Kollision sind die Edukte zu e...,trial,r_6276,q_62,Die Schüler:innen beschreiben die dargestellte...,Die Schüler:innen beschreiben die dargestellte...,Die Schüler:innen beschreiben die dargstellte ...,correct
7895,0f922c54-3c13-4683-b7a6-353588b79677,67c1649e-b694-4813-be49-abfd65a6798e,Beschreibe Auffälligkeiten der dargestellten d...,Nicht alle Kollisionen der Edukt-Teilchen führ...,trial,r_7420,q_62,Die Schüler:innen beschreiben die dargestellte...,Die Schüler:innen beschreiben die dargestellte...,Die Schüler:innen beschreiben die dargstellte ...,correct
7896,483689d8-0601-4e4f-9971-53803def8af6,67c1649e-b694-4813-be49-abfd65a6798e,Beschreibe Auffälligkeiten der dargestellten d...,Hab ich doch in Aufgabe 2 gemacht\n,trial,r_4984,q_62,Die Schüler:innen beschreiben die dargestellte...,Die Schüler:innen beschreiben die dargestellte...,Die Schüler:innen beschreiben die dargstellte ...,incorrect
7897,784320e2-1809-4514-a675-a2fc1b230aff,67c1649e-b694-4813-be49-abfd65a6798e,Beschreibe Auffälligkeiten der dargestellten d...,Nicht immer führt eine Kollision zu einer Reak...,trial,r_0880,q_62,Die Schüler:innen beschreiben die dargestellte...,Die Schüler:innen beschreiben die dargestellte...,Die Schüler:innen beschreiben die dargstellte ...,partially_correct
7898,d45da693-ca7a-45b1-8ea9-d536f82e8d5e,67c1649e-b694-4813-be49-abfd65a6798e,Beschreibe Auffälligkeiten der dargestellten d...,Farbe und Form der Elemente .\n,trial,r_2274,q_62,Die Schüler:innen beschreiben die dargestellte...,Die Schüler:innen beschreiben die dargestellte...,Die Schüler:innen beschreiben die dargstellte ...,incorrect

In [10]:
questions_df = bea_3way_data_df[
    ["original_question_id",
        "question_id",
        "question",
        "correct",
        "partially_correct",
        "incorrect",
    ]
]

questions_df = questions_df.assign(
    correct_id=questions_df["question_id"].replace(r"q(.*)", r"c\1", regex=True),
    partially_correct_id=questions_df["question_id"].replace(r"q(.*)", r"p\1", regex=True),
    incorrect_id=questions_df["question_id"].replace(r"q(.*)", r"i\1", regex=True),
)

questions_df = questions_df.drop_duplicates().sort_values(
    "question_id", ignore_index=True
)
questions_df

,original_question_id,question_id,question,correct,partially_correct,incorrect,correct_id,partially_correct_id,incorrect_id
0,1f3469d5-f6a8-49f4-85d0-d2e156e4cb0c,q_00,"Erkläre kurz, warum du dich für wahr oder fals...",Die SuS beschreiben die Steigung des Graphen a...,Die SuS beschreiben entweder die Steigung des ...,Die SuS beschreiben weder die Steigung des Gra...,c_00,p_00,i_00
1,75333f3a-c1c2-4729-8d61-146800f16532,q_01,Beschreibe die oben dargstellten Phänomene in ...,Die Schüler:innen beschreiben den Ablauf der R...,Die Schüler:innen beschreiben den Ablauf der R...,Die Schüler:innen beschreiben weder die Reakti...,c_01,p_01,i_01
2,dfeace94-8239-4f80-b769-1e0bebbc391f,q_02,Begründe deine Auswahl.,Die Schüler:innen stellen einen Zusammenhang z...,Die Schüler:innen stellen einen Zusammenhang z...,Die Schüler:innen stellen keinen Zusammenhang ...,c_02,p_02,i_02
3,10d57539-7664-4f0f-afe2-51a749036f54,q_03,"Erläutere, warum du (Wahr) oder (Falsch) angek...",Die SuS beschreiben die Unabhängigkeit des Ans...,Die SuS beschreiben entweder die Unabhängigkei...,Die SuS beschreiben weder die Unabhängigkeit d...,c_03,p_03,i_03
4,4a79233b-2d16-4c6d-ba9f-53a7bedf49fc,q_04,Es wird jeweils nur ein Teil der Eingangsleist...,"Die SuS beschreiben, dass die restliche Energi...","Die SuS nutzen Umwandlung, ohne auf die thermi...",Die SuS beschreiben die Umwandlung (in thermis...,c_04,p_04,i_04
...,...,...,...,...,...,...,...,...,...
73,442a4171-9f3a-40b2-b4b5-7c023bbfd4c4,q_73,Formuliere selbst eine Fragestellung.,Die SuS beschreiben die durchschnittliche Gesc...,Die SuS beschreiben entweder die durchschnittl...,Die SuS beschreiben weder die durchschnittlich...,c_73,p_73,i_73
74,2ad4c4b0-5dfe-4667-b344-a00434eeccf1,q_74,Stelle eine Hypothese zum Einfluss der Tempera...,Die Hypothese stellt eine überprüfbare Vermutu...,Die Hypothese stellt eine überprüfbare Vermutu...,Die Hypothese stellt keine überprüfbare Vermut...,c_74,p_74,i_74
75,9a2e7fec-b8fe-49d5-853c-2c0a32c36285,q_75,Wie strukturierst Du den Versuchsablauf? Besch...,Die Schüler:innen beschreiben und begründen ei...,Die Schüler:innen beschreiben eine systematisc...,Die Schüler:innen beschreiben und begründen ei...,c_75,p_75,i_75
76,ba753563-faa3-43c6-973d-320e5adc6979,q_76,Öffne das Material für deine Gruppe! Schaue di...,Die SuS beschreiben korrekt ...\nwie sich die ...,Die SuS beschreiben korrekt ...\nwie sich die ...,Die SuS beschreiben die Daten aus beiden Becke...,c_76,p_76,i_76
77,f5537007-c811-4910-8a18-aaa3e61c39f2,q_77,Vergleiche mit Hinblick auf die Temperatur die...,Die MB-Verteilung wird aufgabenbezogen korrekt...,Die MB-Verteilung wird aufgabenbezogen korrekt...,Die MB-Verteilung wird weder aufgabenbezogen k...,c_77,p_77,i_77

In [11]:
responses_df = bea_3way_data_df[
    ["original_response_id", "response_id", "question_id", "response", "score", "partition"]
].sort_values(["question_id", "partition", "response_id"], ignore_index=True)


responses_df

,original_response_id,response_id,question_id,response,score,partition
0,4af8c054-8dd8-4333-aa1a-c5811bb117c5,r_0000,q_00,"Ich habe mich für Ja entschieden , weil man ja...",incorrect,train
1,25ee90a6-f0dc-4367-9dcf-a8a26a4ff856,r_0001,q_00,"Ich habe mich für wahr entschieden , weil die ...",partially_correct,train
2,27536134-a7e3-4162-9d48-a1bec7cfb3e6,r_0098,q_00,Man kann es mit einer Formel berechnen\n,incorrect,train
3,b5c71e85-b027-4fb4-8f3e-fd005483f8a6,r_0114,q_00,"Ich habe mich für wahr entschieden , weil man ...",partially_correct,train
4,d6180f6e-c0b2-4e28-9d02-a48375ac7114,r_0134,q_00,"Ich habe mich für wahr entschieden , weil man ...",partially_correct,train
...,...,...,...,...,...,...
7894,e5eaa402-742d-4adc-9514-adde1b84ea59,r_3908,q_77,Beantwortung der Impulsfrage Mögliche Darstell...,incorrect,trial
7895,7c1f732f-9dc8-4db7-960a-de57f101550d,r_5695,q_77,Beantwortung der Impulsfrage Mögliche Darstell...,incorrect,trial
7896,dc27d04b-87b9-4d8c-b7f1-77664c043f03,r_5893,q_77,Beantwortung der Impulsfrage Mögliche Darstell...,correct,trial
7897,87ee9a44-34cc-4b0e-a60b-3a92681eb686,r_7192,q_77,Beantwortung der Impulsfrage Mögliche Darstell...,incorrect,trial
7898,db207d9a-9072-4cf7-9900-220642617782,r_7715,q_77,Beantwortung der Impulsfrage Mögliche Darstell...,partially_correct,trial

## Part 2: Extract lemmata with SpaCy

We will use SpaCy to convert the sentences into a usable form.

In [12]:
import spacy
import contextualSpellCheck

In [13]:
nlp = spacy.load("de_core_news_md")

# The spell check is causing issues at the moment. I'll return to this later...
# contextualSpellCheck.add_to_pipe(nlp)

In [14]:
de = nlp("junge reicht auch langsam mal")
de

junge reicht auch langsam mal

Don't need to be particularly finnicky with this in the first instance. We have essentially four types of sentence: question, correct answer, incorrect "answer", and response. We've indexed them differently, so we can just (?) bung them all into a big DataFrame:

In [15]:
# Again, stern note to students: don't write code like this!!

text_df = pd.concat(
    [
        questions_df[["question_id", "question"]].rename(
            {"question_id": "id", "question": "text"}, axis="columns"
        ),
        questions_df[["correct_id", "correct"]].rename(
            {"correct": "text", "correct_id": "id"}, axis="columns"
        ),
        questions_df[["partially_correct_id", "partially_correct"]].rename(
            {"partially_correct": "text", "partially_correct_id": "id"}, axis="columns"
        ),
        questions_df[["incorrect_id", "incorrect"]].rename(
            {"incorrect": "text", "incorrect_id": "id"}, axis="columns"
        ),
        responses_df[["response_id", "response"]].rename(
            {"response_id": "id", "response": "text"}, axis="columns"
        ),
    ],
    ignore_index=True,
)

text_df

          id                                               text
0       q_00  Erkläre kurz, warum du dich für wahr oder fals...
1       q_01  Beschreibe die oben dargstellten Phänomene in ...
2       q_02                            Begründe deine Auswahl.
3       q_03  Erläutere, warum du (Wahr) oder (Falsch) angek...
4       q_04  Es wird jeweils nur ein Teil der Eingangsleist...
...      ...                                                ...
8206  r_3908  Beantwortung der Impulsfrage Mögliche Darstell...
8207  r_5695  Beantwortung der Impulsfrage Mögliche Darstell...
8208  r_5893  Beantwortung der Impulsfrage Mögliche Darstell...
8209  r_7192  Beantwortung der Impulsfrage Mögliche Darstell...
8210  r_7715  Beantwortung der Impulsfrage Mögliche Darstell...

[8211 rows x 2 columns]

OK, so now we can apply SpaCy to each of the texts to get the appropriate data:

In [16]:
text_df = text_df.assign(spacy=text_df["text"].apply(nlp))
text_df

,id,text,spacy
0,q_00,"Erkläre kurz, warum du dich für wahr oder fals...","(Erkläre, kurz, ,, warum, du, dich, für, wahr,..."
1,q_01,Beschreibe die oben dargstellten Phänomene in ...,"(Beschreibe, die, oben, dargstellten, Phänomen..."
2,q_02,Begründe deine Auswahl.,"(Begründe, deine, Auswahl, .)"
3,q_03,"Erläutere, warum du (Wahr) oder (Falsch) angek...","(Erläutere, ,, warum, du, (, Wahr, ), oder, (,..."
4,q_04,Es wird jeweils nur ein Teil der Eingangsleist...,"(Es, wird, jeweils, nur, ein, Teil, der, Einga..."
...,...,...,...
8206,r_3908,Beantwortung der Impulsfrage Mögliche Darstell...,"(Beantwortung, der, Impulsfrage, Mögliche, Dar..."
8207,r_5695,Beantwortung der Impulsfrage Mögliche Darstell...,"(Beantwortung, der, Impulsfrage, Mögliche, Dar..."
8208,r_5893,Beantwortung der Impulsfrage Mögliche Darstell...,"(Beantwortung, der, Impulsfrage, Mögliche, Dar..."
8209,r_7192,Beantwortung der Impulsfrage Mögliche Darstell...,"(Beantwortung, der, Impulsfrage, Mögliche, Dar..."
8210,r_7715,Beantwortung der Impulsfrage Mögliche Darstell...,"(Beantwortung, der, Impulsfrage, Mögliche, Dar..."

I'm putting all the lemmata into lower case... I suspect this is naughty, but I'm going to see how it goes first.

In [17]:
text_df = text_df.explode("spacy", ignore_index=True)
text_df = text_df.assign(
    i=text_df["spacy"].apply(lambda x: x.i),
    lemma=text_df["spacy"].apply(lambda x: x.lemma_.lower()),
    word_text=text_df["spacy"].apply(lambda x: x.text),
)
text_df

,id,text,spacy,i,lemma,word_text
0,q_00,"Erkläre kurz, warum du dich für wahr oder fals...",Erkläre,0,erkläre,Erkläre
1,q_00,"Erkläre kurz, warum du dich für wahr oder fals...",kurz,1,kurz,kurz
2,q_00,"Erkläre kurz, warum du dich für wahr oder fals...",",",2,--,","
3,q_00,"Erkläre kurz, warum du dich für wahr oder fals...",warum,3,warum,warum
4,q_00,"Erkläre kurz, warum du dich für wahr oder fals...",du,4,du,du
...,...,...,...,...,...,...
275450,r_7715,Beantwortung der Impulsfrage Mögliche Darstell...,Energie,32,energie,Energie
275451,r_7715,Beantwortung der Impulsfrage Mögliche Darstell...,erreicht,33,erreichen,erreicht
275452,r_7715,Beantwortung der Impulsfrage Mögliche Darstell...,hat,34,haben,hat
275453,r_7715,Beantwortung der Impulsfrage Mögliche Darstell...,.,35,--,.
275454,r_7715,Beantwortung der Impulsfrage Mögliche Darstell...,\n,36,\n,\n

I think I'm also going to remove any cases where the lemma is just whitespace.

In [18]:
def whitespace_str(str_in):
    return all([c in whitespace for c in str_in])


assert whitespace_str(
    """    
                      
                                """
)
assert not whitespace_str("slkdjf  s")

In [19]:
text_df = text_df[-text_df["lemma"].apply(whitespace_str)]

-----------------------------

In [20]:
questions_df

,original_question_id,question_id,question,correct,partially_correct,incorrect,correct_id,partially_correct_id,incorrect_id
0,1f3469d5-f6a8-49f4-85d0-d2e156e4cb0c,q_00,"Erkläre kurz, warum du dich für wahr oder fals...",Die SuS beschreiben die Steigung des Graphen a...,Die SuS beschreiben entweder die Steigung des ...,Die SuS beschreiben weder die Steigung des Gra...,c_00,p_00,i_00
1,75333f3a-c1c2-4729-8d61-146800f16532,q_01,Beschreibe die oben dargstellten Phänomene in ...,Die Schüler:innen beschreiben den Ablauf der R...,Die Schüler:innen beschreiben den Ablauf der R...,Die Schüler:innen beschreiben weder die Reakti...,c_01,p_01,i_01
2,dfeace94-8239-4f80-b769-1e0bebbc391f,q_02,Begründe deine Auswahl.,Die Schüler:innen stellen einen Zusammenhang z...,Die Schüler:innen stellen einen Zusammenhang z...,Die Schüler:innen stellen keinen Zusammenhang ...,c_02,p_02,i_02
3,10d57539-7664-4f0f-afe2-51a749036f54,q_03,"Erläutere, warum du (Wahr) oder (Falsch) angek...",Die SuS beschreiben die Unabhängigkeit des Ans...,Die SuS beschreiben entweder die Unabhängigkei...,Die SuS beschreiben weder die Unabhängigkeit d...,c_03,p_03,i_03
4,4a79233b-2d16-4c6d-ba9f-53a7bedf49fc,q_04,Es wird jeweils nur ein Teil der Eingangsleist...,"Die SuS beschreiben, dass die restliche Energi...","Die SuS nutzen Umwandlung, ohne auf die thermi...",Die SuS beschreiben die Umwandlung (in thermis...,c_04,p_04,i_04
...,...,...,...,...,...,...,...,...,...
73,442a4171-9f3a-40b2-b4b5-7c023bbfd4c4,q_73,Formuliere selbst eine Fragestellung.,Die SuS beschreiben die durchschnittliche Gesc...,Die SuS beschreiben entweder die durchschnittl...,Die SuS beschreiben weder die durchschnittlich...,c_73,p_73,i_73
74,2ad4c4b0-5dfe-4667-b344-a00434eeccf1,q_74,Stelle eine Hypothese zum Einfluss der Tempera...,Die Hypothese stellt eine überprüfbare Vermutu...,Die Hypothese stellt eine überprüfbare Vermutu...,Die Hypothese stellt keine überprüfbare Vermut...,c_74,p_74,i_74
75,9a2e7fec-b8fe-49d5-853c-2c0a32c36285,q_75,Wie strukturierst Du den Versuchsablauf? Besch...,Die Schüler:innen beschreiben und begründen ei...,Die Schüler:innen beschreiben eine systematisc...,Die Schüler:innen beschreiben und begründen ei...,c_75,p_75,i_75
76,ba753563-faa3-43c6-973d-320e5adc6979,q_76,Öffne das Material für deine Gruppe! Schaue di...,Die SuS beschreiben korrekt ...\nwie sich die ...,Die SuS beschreiben korrekt ...\nwie sich die ...,Die SuS beschreiben die Daten aus beiden Becke...,c_76,p_76,i_76
77,f5537007-c811-4910-8a18-aaa3e61c39f2,q_77,Vergleiche mit Hinblick auf die Temperatur die...,Die MB-Verteilung wird aufgabenbezogen korrekt...,Die MB-Verteilung wird aufgabenbezogen korrekt...,Die MB-Verteilung wird weder aufgabenbezogen k...,c_77,p_77,i_77

In [21]:
responses_df

,original_response_id,response_id,question_id,response,score,partition
0,4af8c054-8dd8-4333-aa1a-c5811bb117c5,r_0000,q_00,"Ich habe mich für Ja entschieden , weil man ja...",incorrect,train
1,25ee90a6-f0dc-4367-9dcf-a8a26a4ff856,r_0001,q_00,"Ich habe mich für wahr entschieden , weil die ...",partially_correct,train
2,27536134-a7e3-4162-9d48-a1bec7cfb3e6,r_0098,q_00,Man kann es mit einer Formel berechnen\n,incorrect,train
3,b5c71e85-b027-4fb4-8f3e-fd005483f8a6,r_0114,q_00,"Ich habe mich für wahr entschieden , weil man ...",partially_correct,train
4,d6180f6e-c0b2-4e28-9d02-a48375ac7114,r_0134,q_00,"Ich habe mich für wahr entschieden , weil man ...",partially_correct,train
...,...,...,...,...,...,...
7894,e5eaa402-742d-4adc-9514-adde1b84ea59,r_3908,q_77,Beantwortung der Impulsfrage Mögliche Darstell...,incorrect,trial
7895,7c1f732f-9dc8-4db7-960a-de57f101550d,r_5695,q_77,Beantwortung der Impulsfrage Mögliche Darstell...,incorrect,trial
7896,dc27d04b-87b9-4d8c-b7f1-77664c043f03,r_5893,q_77,Beantwortung der Impulsfrage Mögliche Darstell...,correct,trial
7897,87ee9a44-34cc-4b0e-a60b-3a92681eb686,r_7192,q_77,Beantwortung der Impulsfrage Mögliche Darstell...,incorrect,trial
7898,db207d9a-9072-4cf7-9900-220642617782,r_7715,q_77,Beantwortung der Impulsfrage Mögliche Darstell...,partially_correct,trial

Quickly drop the `spacy` column, as that isn't picklable.

In [22]:
text_df.drop('spacy', axis='columns')

,id,text,i,lemma,word_text
0,q_00,"Erkläre kurz, warum du dich für wahr oder fals...",0,erkläre,Erkläre
1,q_00,"Erkläre kurz, warum du dich für wahr oder fals...",1,kurz,kurz
2,q_00,"Erkläre kurz, warum du dich für wahr oder fals...",2,--,","
3,q_00,"Erkläre kurz, warum du dich für wahr oder fals...",3,warum,warum
4,q_00,"Erkläre kurz, warum du dich für wahr oder fals...",4,du,du
...,...,...,...,...,...
275449,r_7715,Beantwortung der Impulsfrage Mögliche Darstell...,31,benötigt,benötigte
275450,r_7715,Beantwortung der Impulsfrage Mögliche Darstell...,32,energie,Energie
275451,r_7715,Beantwortung der Impulsfrage Mögliche Darstell...,33,erreichen,erreicht
275452,r_7715,Beantwortung der Impulsfrage Mögliche Darstell...,34,haben,hat
275453,r_7715,Beantwortung der Impulsfrage Mögliche Darstell...,35,--,.

There's one other wrinkle: some of the lemmata contain quotation marks, which screws up the training file. As an interim hacky solution, I'll simply swap any instances of `"` for `'`. I think that the `"` appear in code, so it's not a sensible switch, but it'll do for the moment.

In [23]:
text_df=text_df.drop('lemma', axis='columns').assign(lemma=text_df['lemma'].str.replace('"', "'"))
                                                    
text_df.query("""
              `word_text`.str.contains('"')"""
              
              
              ).sort_values('word_text')

,id,text,spacy,i,word_text,lemma
149,q_10,Leitet auf Grundlage der Muster und der Messwe...,"""",9,"""",--
195735,r_3563,"Der Versuchsaufbau unterscheidet sich darin , ...","""",46,"""",--
196464,r_4175,Beide Reaktionsansätze sind fast gleich aufgeb...,"""",46,"""",--
196466,r_4175,Beide Reaktionsansätze sind fast gleich aufgeb...,"""",48,"""",--
201023,r_6949,"Je mehr Edukte es gibt , desto höher ist die C...","""",33,"""",--
...,...,...,...,...,...,...
273700,r_5135,Beantwortung der Impulsfrage Mögliche Darstell...,"id=""MathJax-Element-1-Frame",22,"id=""MathJax-Element-1-Frame",id='mathjax-element-1-fram
271947,r_1816,Beantwortung der Impulsfrage Mögliche Darstell...,"role=""presentation",24,"role=""presentation",role='presentation
273706,r_5135,Beantwortung der Impulsfrage Mögliche Darstell...,"role=""presentation",28,"role=""presentation",role='presentation
273702,r_5135,Beantwortung der Impulsfrage Mögliche Darstell...,"tabindex=""0",24,"tabindex=""0",tabindex='0
271943,r_1816,Beantwortung der Impulsfrage Mögliche Darstell...,"tabindex=""0",20,"tabindex=""0",tabindex='0

OK, and I think that those are in the format that I can export them.

In [24]:
with open("bea_3way_data.pickle", 'wb') as fOut:
    pickle.dump({'questions':questions_df, 'responses':responses_df, 'text':text_df.drop('spacy', axis='columns')}, fOut)