# Applicator

**This is for the 2-way task**

I want to apply a theory to a response. In principle, the response should just be a sentence, but it needs to have been read and SpaCy'd first. So for the moment, I'll just assume that we're applying to sentences from the data file. Which, fortunately, is all encoded in the theory object, having been extracted from `bea_2way_data_pickle`.

Want two outputs: one of the results, one of the applications.

The theory itself will be the output from `bea_2way_theory_generator.ipynb/induce_theory`.

Want `apply_theory(theory, original_response_id)`.

Actually, a better plan might be to just have a function which applies the theory to the embedded trial set.

`apply_trial_set(theory)`

In [1]:
THEORY_ROOT_DIR='/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318'

In [2]:
import amati_bea as amati

In [3]:
import pandas as pd

from sklearn.metrics import f1_score, cohen_kappa_score

In [4]:
from operator import itemgetter
import pickle
import datetime
import re
import glob
import json
import os

## Get the data

Start off by getting the data we're applying the theory to:

In [5]:
JSON_DATA_FILE = "/Users/alistair.willis/repos/bea-2026/BEA Shared Task 2026 on Rubric-based Short Answer Scoring for German/updated/2way/ALICE_LP_train_2way__v2.json"

with open(JSON_DATA_FILE) as fIn:
    bea_data = json.load(fIn)

bea_data_with_amati = []

In [6]:
bea_data

[{'id': '73b0b485-5e89-40d8-ae68-4a650d4670c4',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Bei einem höheren Zerteilungsgrad ( hier das Zerteilen der Äpfel ) kommt es zu einer schnelleres Reaktionsgeschwindigkeit .\nDie hat man anhand unseres Modellversuches gesehen .\nAlso können wir feststellen , dass ein Stoff mit einem höheren Zerteilungsgrad einen Einfluss auf die Reaktionsgeschwindigkeit .\nSomit reagieren auch die zerschnittenden Äpfel schnelller .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': '0c46f560-fcb4-4ea4-a540-cc2b96512b1c',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Das Größte apfelstück , also das mildem geringsten Zerteilungsgrad bleibt am längsten in einem relativ frischen Zustand .\nJe höher der Zerteilungsgrad wird , desto schneller verdirbt das Stück Apfel .\nDies hängt mit der Fläche die mit der Luft in Kontakt kommt und dem Volumen vom Apfelstück zusammen .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Correct'},
 {'id': '467514d6-45d6-4f33-a1aa-dab58cadb9a7',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'verderben schneller\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': 'b570cf0d-d29d-4add-bc9a-53156bb68003',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Durch zerteilen der Äpfel wird dessen oberfläche erhöht . dadurch wird auch die Reaktionsgeschwindigkeit aller chemischer reaktionen höher und der Apfel verdirbt schneller !\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Correct'},
 {'id': '64d40458-107c-403e-bc30-f51ff3b09495',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Je größer die Oberfläche vom Apfel ist , desto mehr können Stoffe an der Oberfläche reagieren , zb oxidieren ( also Braun werden ) .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': '7ac68634-48a9-48d5-9ed7-dea8ccf5b3e2',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Je höher der Zerteilungsgrad der Äpfel desto höher ist die Reaktionsgeschwindigkeit und somit der Verderblichkeitsprozess .\nDurch die Zerteilung liegt eine größere Oberfläche vor , sodass megr Teilchen mit anderen Teilchen reagieren können , und somit die Reaktion schneller abläuft .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Correct'},
 {'id': 'e3ef99a8-eac1-4d8b-a931-118e5df07bfc',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Umso kleiner die Apfel zerschnitten sind , umso mehr Oberfläche liegt frei , um zu reagieren .\nDabei Oxidiert die Oberfläche und der Apfel wird braun .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': '43aad239-c10b-4e7d-96a7-f09d7167a77a',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Wenn wie den apfel zerteilen vergrözern wir seine oberfläche und somit steigt die zerfallsrafte\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': 'a0cdc779-6a08-467a-9fe3-f0efc818cc93',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Je kleiner Zerteilt ein Apfel ist desto höher ist die Fläche an der zb. Luft und Bakterien auftreten können .\nDurch die höherer Angriffsfläche sind auf generell mehr Teilchen vorhandene die reagieren können .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': 'aa1f1fe1-3f87-42a7-b14b-4f8e33fee87f',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': '- Apfel kann unter kühlen Bedingungen länger haltbar bleiben und verdirbt nicht so schnell , da die Reaktionsteilnehmer mit geringerer Geschwindigkeit bewegen\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': 'f3456c74-8193-4942-b66d-c4c1dde62a3f',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Das Zerteilen der Äpfel führt zu einer schnelleren Verderbung der Äpfel .\nDie Äpfel bieten anderen Reaktaten mehr Fläche durch die zerteilte Form .\nEs ist logisch , da mehr Fläche bei selben Volumen durch das Zerteilen entsteht .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': '46361fa0-d6b6-477f-8e70-2c7245b9de17',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Wenn man einen Apfel zerteilt , verdirbt er schneller .\nDie Reaktionsgeschwindigkeit steigt .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': '18360f3c-ac1e-480e-8c98-ae19791426cc',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'durch das zerteilen gibt man eine grössere oberfläche frei wo die kälte aufgenommen werden kann\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': '99c899cf-5168-4616-9991-8b9986d53d2f',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Wie in den vorherigen Feldern bereits angegeben denke ich , dass das Zerteilen der Äpfel dafür sorgt , dass diese deutlich schneller verderben .\nDies liegt zum Einen am Fehlen der schützenden Schale und zum Anderen an der Tatsache , dass nun z. B. Sauerstoff in den Apfel gelangt .\nDieser kann zur Oxidation von einzelnen Bestandteilen des Apfels führen .\nDa ein Apfel sehr zuckerreich ist stellt er einen energiereichen Nährboden für Pilze oder Bakterien dar .\nIn Kombination mit dem zugeführten Sauerstoff können aerobe Organismen ebenfalls den Apfel befallen .\nDiese zersetzen den Apfel dann in verschiedene Abbauprodukte , die unter Umständen für den Menschen schädlich sind .\nMutmaßlich wird der Apfel auch teilweise vergoren .\nDiese Abbauprodukte riechen für den Menschen unangenehm .\nDiese Folgen sind nur ( fundierte ) Spekulation , ich habe keine weiteren Quellen genutzt .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Correct'},
 {'id': 'a32595a6-fa4b-4236-9c01-122337da9934',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Wenn man möglichst lange etwas von den Äpfeln haben will , sollte man sie nicht stark zerkleinern , da so die Reaktionsgeschwindigkeit zunimmt .\nUmso kleiner das Teilchen , desto größer die " Angriffsfläche " für Stoffe , die den Prozess des Verderbens so beschleunigen .\nWenn Teile ( natürlich mit einer gewissen Kraft ) aufeinander treffen , entstehen die Produkte .\nBei dem Zerkleinerjngskraft ist es schon mitten in der anderen Flüssigkeit verteilt und so müssen sie sich nicht erst finden .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Correct'},
 {'id': '0b8eecc3-d333-4215-89d9-58ddc840226b',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Das Zerteilen von Äpfeln kann den Verderblichkeitsprozess beschleunigen , da dabei mehr Oberfläche des Fruchtfleisches freigelegt wird , was zu einem verstärkten Kontakt mit Sauerstoff führt .\nDies kann zu einer Oxidation von Enzymen und Nährstoffen führen , was das Verderben beschleunigt .\nDie Zerteilen von Äpfeln kann also dazu führen , dass sie schneller verderben , insbesondere wenn sie nicht sofort gegessen oder gekühlt werden .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Correct'},
 {'id': '8fe73c5b-6778-4ed8-a085-ec471994c6ed',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Wie im Vorherigen Versuch war es so , dass umso kleiner das Produkt wird umso schnell reagiert es .\nBeim Apfel ist es so , dass wenn er geschnitten wurde wird die Fläche des Äpfeln Größer wodurch er schneller verderbt .\nJedoch sind auch die äußeren Einflüsse wichtig , wie zum Beispiel die Temperatur oder ob das stück Apfel in der Sonne liegt .\nDurch wärme und Sonne wird Wasser aus dem Apfel entzogen , wodurch er die Reaktionsgeschwindigkeit zunimmt .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': '53db6745-6e91-4239-a05a-9811931777b3',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Je kleiner der Apfel zerteilt ist desto schneller verdirbt er\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': 'c5b0f1b5-e96d-42ea-8d7f-3acf6e7caa24',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Umso kleiner die Äpfel geschnitten sind ( umso höher der Zerteilungsgrad ) , desto schneller verderben die Äpfel\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Correct'},
 {'id': 'd29d7b5f-4e03-4c98-b029-eb2dd1cd8b7f',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',

The test run in this case will apply the theory to a set of responses in json format, then create a new json file with the applied rule information in place.

We'll just be able to pull out the relevant data from the saved theory.

In [7]:
with open(
    "/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_0f235f9a-64f8-4790-917d-23e0a15077c5_2026-03-18_15:10:43.190962.pickle",
    "rb",
) as fIn:
    theory = pickle.load(fIn)

In [8]:
theory.keys()

dict_keys(['theory', 'original_question_id', 'question_id', 'all_questions_df', 'all_responses_df', 'all_text_df', 'rules'])

Let's find a trial response. First, need to pull out the question for that theory:

In [9]:
theory["question_id"]

'q_36'

And then get the associated responses:

In [10]:
theory["all_responses_df"].query("`question_id`==@theory['question_id']").query(
    "`partition`=='trial'"
).head()

,original_response_id,response_id,question_id,response,score,partition
3682,bff5b4ff-1376-4df0-820a-e2b8ad294555,r_1939,q_36,Die Teilchen haben die Eigenschaft bei kältere...,incorrect,trial
3683,c76a5fe9-d18d-40d6-917a-367c57aca94a,r_2043,q_36,Durch die Kühlung bewegen sich die Teilchen la...,incorrect,trial
3684,84535d1e-0014-49f8-9dfa-fc6b445d1fe3,r_2105,q_36,Niedrigere Temperatur- &gt; Niedrigerere Teilc...,incorrect,trial
3685,ef1fb3a9-00ae-445b-8e32-83e342601b99,r_4243,q_36,Allgemeine chemische Prozesse werden durch ein...,correct,trial
3686,3d0317b9-904b-4718-9ec5-88406a9951c8,r_4852,q_36,"Kühlung ist ein Vorgang , bei dem einem System...",incorrect,trial

OK, so now we should be able to pull out the cases we want to apply the theory to.

In [11]:
responses_json_ls = [
    x for x in bea_data if x["question_id"] == theory["original_question_id"]
]

responses_json_ls

[{'id': '639771c5-241b-4c35-921b-087896099ce8',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Die Gärung oder das verfaulen ist auch eine Art Reaktion .\nDurch die niedrigen Temperaturen gibt es im verwahrten Produkt weniger Reaktionen , da die Geschwindigkeit der Teilchen viel niedriger ist .\nAußerdem sind kalte Räume für viele Bakterien und Schädlinge kein guter Lebensraum\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Correct'},
 {'id': 'cd4634a4-929a-4690-8cd3-aedcaa1a3f28',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'da Reaktionen bei höheren Temperaturen schneller Ablaufen , kann bei einer Verminderung der Termperatur die Reaktion , welche das Verderben von lebensmitteln herbeiführt , verlangsamt werden\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect'},
 {'id': '28eea373-3e58-48b2-a320-205719462e85',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Durch die Kühlung finden chemische Prozesse verlangsamt statt , und Pilze , wie Schimmel sind gelähmt und können sich nicht so schnell ausbreiten .\nAuf der Ebene der Kollisionstheorie bedeutet die Kälte eine geringe Anzahl von Teilchen , die sich auch nicht so schnell bewegen , wodurch die Möglichkeiten von Reaktionen beschränkt sind .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect'},
 {'id': '24b4d6b5-d4fb-4d72-8a08-d2e54379010c',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Durch das Kühlen wird die Aktivität und die Teilchenbewegung herabgesenkt .\nDadurch wird die Reaktionsgeschwindigkeit herabgesenkt und so werden Reaktionen , die zum Verderb von Lebensmitteln führen , verlangsamt .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect'},
 {'id': 'e493139c-ee28-4ec5-b3eb-6c95403a2218',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'bei kalten temperaturen bewegen sich die Teilchen nicht so schnelll und das Lebensmittel verdirbt langsamer .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect'},
 {'id': '96474d44-9008-4f55-baf8-cfb7bff089e1',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Durch die niedrige Temperatur die durch die Kühlung entsteht , werden die Prozesse des Verderbens verlangsamt das sie weniger Energie bekommen und somit sich auhc nicht so schnelle bewgenen können .\nAußerdem können Bakterien bei niedriger Temperatur schwieriger überleben .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Correct'},
 {'id': 'ff425e57-8c29-4df3-83de-8a4a7806c2e4',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Die Kühlung sorgt dafür , dass die chemischen Reaktionen an dem Obst langsamer vonstatten gehen .\nBei niedrigen Temperaturen sind Teilchen langsamer und besitzen eine niedrigere Stoßwahrscheinlichkeit , was dazu führt , dass das Obst länger hält .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Correct'},
 {'id': 'c17f289b-0750-4fa6-b67c-27641c18baa2',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Die gesenkte Temperatur hemmt Reaktionen der Lebensmittel mit ihrer Umwelt , wie z. B Sauerstoff oder Bakterien .\nAuch innere Prozesse , wie das Auslösen von Faulen durch verschiedene Botenstoffe im Lebensmittel werden eherausgezögert .\nDadurch bleiben die Lebensmittel länger frisch .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect'},
 {'id': '441d85c0-19eb-40fd-b50e-245f2fba1a23',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Wenn eine Frucht beginnt zu gären laufen dabei verschiedenen chemische Prozesse ab .\nBei einer niedrigen Temperatur Läufen diese langsamer ab also bei einer warmen dadurch hat ein Kühlschrank sozusagen eine konservierende Wirkung .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect'},
 {'id': '65b0e1eb-7d17-4482-817c-e2e84ad69483',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Wenn die Temperatur niedriger ist , bewegen sich die Teilchen nicht so schnell und haben nicht alle die Mindestenergie .\nDeswegen kann man auf makroskopisch er Eben3 erkennen , dass das Produkt nicht so schnéll schlecht wird und auf submikroskopischer dass die Reaktionsgeschwindigkeit und Reaktionsrate nicht so hoch ist\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Correct'},
 {'id': '6905eb11-951f-4670-a593-1a3016a2d106',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Durch eine Kühlung der Lebensmittel vermeidet man eine schnelle Reaktion der Lebensmittel , die diese nicht mehr genießbar machen würde .\nWenn man als Beispiel die Milch nimmt , so muss diese gekühlt werden , da ansonsten es schneller zu einer Reaktion kommen würde , der diese Milch sauer machen würde .\nDurch eine niedrigere Temperatur wird die Mindestenerdie für eine REaktion oftmals nicht erreicht oder hinausgezogert .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect'},
 {'id': 'dec325b1-9e7e-4717-b0f6-be29dfc3e412',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Auf reaktionskinetischer Ebene bewirkt die Kühlung eines Produktes die Verlangsamung der chemischen Reaktionen durch die Verlangsamung der Teilchen .\nDie Stoßwahrscheinlichkeiten in einer bestimmten Zeit werden somit verringert .\nEs dauert somit länger bis der Apfel ungenießbar wird .\nAuf makroskopischer Ebene bedeutet dies , dass es länger dauert bis ein Verderben des Apfels zu erkennen ist .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Correct'},
 {'id': '68a276c1-5d54-4864-8a20-38bd25de6cdc',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Da die Temperatur in einem Kühlschrank sehr kalt ist , beeinflusst diese Kälte die Reaktionsgeschwindigkeit .\nDie Teilchen werden langsamer , weshalb es nur sehr langsam und selten zu einem effektiven Zusammenstoß kommt .\nDies liegt daran , dass die Teilchen eine zu unterschiedliche Geschwindigkeit mit sich bringen und die Aktivierungsenergie nicht besitzen .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Correct'},
 {'id': '20e37023-d935-4de5-b478-0bfcfcf2392f',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Die Temperatur ist niedrig und somit kommt es nur zu langsameren effektiven Zusammenstößen\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect'},
 {'id': '80539cd0-06d8-4450-a788-3448ab64d2dc',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Die Kühlung verlangsamt die Reaktionen .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect'},
 {'id': 'd9f4e071-5e55-477d-b1f0-1cb65a0efcb7',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Auf submikroskopischer Ebene bewegen sich die Teilchen immer Essen immer langsamer , sodass eine Reaktion / Fermentierung sehr langsam verläuft .\nDie Stoßwahrscheinlichkeit der Teilchen ist sehr gering .\nDadurch bleibt das essen länger erhalten\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect'},
 {'id': '7d41932d-4375-47be-919d-ad029c5ff0df',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Durch die niedrige Temperatur wird die Geschwindigkeit der Reaktion bzw. des Verderbens vermindert .\nDie Früchte verderben also langsamer , weil die Temperatur und somit auch die Reaktionsgeschwindigkeit und Stoßwahrscheinlichkeit durch die niedrige Temperatur auch niedriger wird .\nDies führt zu weniger effektiven Zusammenstößen in einem Zeitraum .\nSomit sind die Lebensmittel länger haltbar .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Correct'},
 {'id': '7c2a6c6f-7fb5-4286-903c-5526165a856e',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',

Now we need to get the data into the right form to apply the theory.

I'm going to apply the theory to all the possible cases (ie. training and trial data).

And we can get the dataframe version of the data from the theory structure:

In [12]:
application_question_ss = (
    theory["all_questions_df"]
    .set_index("original_question_id")
    .T[theory["original_question_id"]]
)
application_question_ss

question_id                                                    q_36
question          Erläutere die konservierende Wirkung einer Küh...
correct           Die Schüler:innen eklären den konservierenden ...
incorrect_1       Die Schüler:innen erklären den konservierenden...
incorrect_2       Die Scüler:innen erklären den konservierenden ...
correct_id                                                     c_36
incorrect_1_id                                                 i_36
incorrect_2_id                                                 j_36
Name: 0f235f9a-64f8-4790-917d-23e0a15077c5, dtype: object

In [13]:
application_responses_df = theory["all_responses_df"][
    theory["all_responses_df"]["question_id"] == application_question_ss["question_id"]
]

application_responses_df

,original_response_id,response_id,question_id,response,score,partition
3574,d49e5db1-8757-4718-8b51-7ec94f328fc5,r_0013,q_36,Durch die Kälte finden Biochemische Reaktionen...,incorrect,train
3575,98fa8dc4-1c7e-4faa-b618-f553ce0b8a49,r_0078,q_36,Durch das kühlen der Apfel ist die Reaktion ( ...,correct,train
3576,a4d97e5f-b2cf-484f-855b-ef248aa5e287,r_0110,q_36,"Durch die Lagerung im kühleren Medium , kann d...",incorrect,train
3577,80539cd0-06d8-4450-a788-3448ab64d2dc,r_0208,q_36,Die Kühlung verlangsamt die Reaktionen .\n,incorrect,train
3578,77b3a36c-dc5e-466a-b85b-44bba5abbb8f,r_0311,q_36,"Dadurch , dass man Lebensmittel kühlt , bleibt...",incorrect,train
...,...,...,...,...,...,...
3690,e9628083-3a17-4725-96b1-42f2728945fd,r_6075,q_36,Da die Temperatur im Kühlschrank geringer ist ...,correct,trial
3691,0dd6baad-11e7-47a1-ac9e-18249682cf7d,r_6897,q_36,"Die Reaktion der Teilchen läuft langsamer ab ,...",correct,trial
3692,ff3417b1-32e5-4daa-8be8-b573be533ba2,r_7405,q_36,Die Temperaturabnahme verringert die Reaktions...,incorrect,trial
3693,d5c7db2f-b5a8-4b99-80ad-abc0c5d44b6b,r_7679,q_36,Durch die Kühlung bewegen sich die Teilchen ni...,incorrect,trial
3694,c68922cb-71d0-4607-b77b-4fa380ac7319,r_7740,q_36,"Aufgrund der niedrigeren Temperatur , bewegen ...",incorrect,trial

In [14]:
application_texts_used = [
    application_question_ss["question_id"],
    application_question_ss["correct_id"],
    application_question_ss["incorrect_1_id"],
    application_question_ss["incorrect_2_id"],
] + list(application_responses_df["response_id"])

application_text_df = theory["all_text_df"].query("`id`.isin(@application_texts_used)")[
    ["id", "i", "lemma"]
]

application_text_df

            id   i          lemma
871       q_36   0       erläuter
872       q_36   1            der
873       q_36   2  konservierend
874       q_36   3        wirkung
875       q_36   4            ein
...        ...  ..            ...
128990  r_7740  31        niedrig
128991  r_7740  32      gehaltend
128992  r_7740  33     temperatur
128993  r_7740  34   verlangsamen
128994  r_7740  35             --

[5644 rows x 3 columns]

And now we should be able to apply the learner to this data. Let's see what happens...

In [15]:
evaluation_results_df = amati.evaluate_theory(
    theory["theory"],
    responses_df=application_responses_df,
    text_df=application_text_df,
    rulesstring=theory["rules"],
    question_ss=application_question_ss,
)

In [16]:
application_results_dict = amati.apply_theory(
    theory["theory"],
    responses_df=application_responses_df,
    text_df=application_text_df,
    rulesstring=theory["rules"],
    question_ss=application_question_ss,
)

In [17]:
evaluation_results_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
response_id,,,,,,,,,,,,,,,,,,,,
r_0013,NaN,NaN,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_0078,NaN,correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_0110,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_0208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_0311,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
r_6075,NaN,correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_6897,NaN,correct,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,incorrect,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_7405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_7679,NaN,NaN,NaN,correct,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
r_7740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

OK, now to get the rules in the right form, we want a function for converting a rule description into a Python dict:

In [18]:
def get_json_from_rule(rule):
    if rule["selected_rule"][0] == "rule1":
        return {
            "amati": {
                "literals": [
                    {
                        "pred": "contains",
                        "document": "student_response",
                        "lemma": [x[1] for x in rule["parameters"] if x[0] == 1][0],
                        "id": "@1",
                    }
                ],
                "prediction": rule["predicted_grade"][0],
            }
        }
    elif rule["selected_rule"][0] == "rule2":
        return {
            "amati": {
                "literals": [
                    {
                        "pred": "contains",
                        "document": "student_response",
                        "lemma": [x[1] for x in rule["parameters"] if x[0] == 1][0],
                        "id": "@1",
                    },
                    {
                        "pred": "contains",
                        "document": "student_response",
                        "lemma": [x[1] for x in rule["parameters"] if x[0] == 2][0],
                        "id": "@2",
                    },
                    {"pred": "precedes", "order": ["@1", "@2"]},
                ],
                "prediction": rule["predicted_grade"][0],
            }
        }
    elif rule["selected_rule"][0] == "rule3":
        return {
            "amati": {
                "literals": [
                    {
                        "pred": "contains",
                        "document": "student_response",
                        "lemma": [x[1] for x in rule["parameters"] if x[0] == 1][0],
                        "id": "@1",
                    },
                    {
                        "pred": "contains",
                        "document": "student_response",
                        "lemma": [x[1] for x in rule["parameters"] if x[0] == 2][0],
                        "id": "@2",
                    },
                ],
                "prediction": rule["predicted_grade"][0],
            }
        }
    
    
    # elif rule["selected_rule"][0] == "ki_rule1":
    #     return {
    #         "amati": {
    #             "literals": [
    #                 {
    #                     "pred": "contains",
    #                     "document": "student_response",
    #                     "lemma": [x[1] for x in rule["parameters"] if x[0] == 1][0],
    #                     "id": "@1",
    #                 },
    #                 {
    #                     "pred": "contains",
    #                     "document": "reference_answer",
    #                     "lemma": [x[1] for x in rule["parameters"] if x[0] == 1][0],
    #                     "id": "@2",
    #                 },
    #                 {
    #                     "pred": "contains",
    #                     "negated": True,
    #                     "document": "question",
    #                     "lemma": [x[1] for x in rule["parameters"] if x[0] == 1][0],
    #                     "id": "@3",
    #                 },
    #             ],
    #             "prediction": rule["predicted_grade"][0],
    #         }
    #     }
        
    elif rule["selected_rule"][0] == "ki_rule1":
        return {
            "amati": {
                "literals": [],
                "prediction": rule["predicted_grade"][0],
            }
        }




    else:
        assert False

In [19]:
#get_json_from_rule(application_results_dict["r_0320"][0])
application_results_dict["r_6897"][0]

{'result': 'SATISFIABLE',
 'selected_rule': ('rule1', 'selected_rule(rule1)'),
 'predicted_grade': ('correct', 'predicted_grade(correct)'),
 'parameters': [(1, '"zusammenstoß"', 'parameter(1,"zusammenstoß")'),
  (2, '"teilche"', 'parameter(2,"teilche")')],
 'positive_covered': ['r_0078',
  'r_0473',
  'r_0650',
  'r_0805',
  'r_1929',
  'r_2106',
  'r_2236',
  'r_2536',
  'r_2568',
  'r_2769',
  'r_2825',
  'r_3147',
  'r_3957',
  'r_5553',
  'r_5984',
  'r_6092',
  'r_6421',
  'r_6699',
  'r_6753',
  'r_7117'],
 'negative_covered': ['r_3793', 'r_6492', 'r_6593'],
 'evaluations': {'precision': 86,
  'compression': 17,
  'coverage': 17,
  'accuracy': 86},
 'positive_df':     response_id question_id      score  covered
 0        r_0013        q_36  incorrect    False
 1        r_0078        q_36    correct     True
 3        r_0208        q_36  incorrect    False
 5        r_0321        q_36  incorrect    False
 6        r_0350        q_36  incorrect    False
 ..          ...         ...        ...      ...
 101      r_7097        q_36  incorrect    False
 102      r_7117        q_36    correct     True
 104      r_7418        q_36    correct    False
 105      r_7621        q_36  incorrect    False
 107      r_7837        q_36  incorrect    False

 [90 rows x 4 columns],
 'negative_df':     response_id question_id      score  covered
 0        r_0013        q_36    correct    False
 1        r_0078        q_36  incorrect    False
 2        r_0110        q_36    correct    False
 3        r_0208        q_36    correct    False
 4        r_0311        q_36    correct    False
 ..          ...         ...        ...      ...
 103      r_7156        q_36    correct    False
 104      r_7418        q_36  incorrect    False
 105      r_7621        q_36    correct    False
 106      r_7628        q_36    correct    False
 107      r_7837        q_36    correct    False

 [108 rows x 4 columns]}

So for the complete set, we need to decide whether we're using the first applied rule or the final applied rule (we're using the first, as it's more intuitive to go with the first application), and what the default is. In this case, the default will be incorrect, and the `amati` feature will have  an empty set as the value.

So let's now run through the json dictionary and add the `amati` feature to each response in the file:

In [20]:
bea_data

[{'id': '73b0b485-5e89-40d8-ae68-4a650d4670c4',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Bei einem höheren Zerteilungsgrad ( hier das Zerteilen der Äpfel ) kommt es zu einer schnelleres Reaktionsgeschwindigkeit .\nDie hat man anhand unseres Modellversuches gesehen .\nAlso können wir feststellen , dass ein Stoff mit einem höheren Zerteilungsgrad einen Einfluss auf die Reaktionsgeschwindigkeit .\nSomit reagieren auch die zerschnittenden Äpfel schnelller .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': '0c46f560-fcb4-4ea4-a540-cc2b96512b1c',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Das Größte apfelstück , also das mildem geringsten Zerteilungsgrad bleibt am längsten in einem relativ frischen Zustand .\nJe höher der Zerteilungsgrad wird , desto schneller verdirbt das Stück Apfel .\nDies hängt mit der Fläche die mit der Luft in Kontakt kommt und dem Volumen vom Apfelstück zusammen .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Correct'},
 {'id': '467514d6-45d6-4f33-a1aa-dab58cadb9a7',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'verderben schneller\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': 'b570cf0d-d29d-4add-bc9a-53156bb68003',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Durch zerteilen der Äpfel wird dessen oberfläche erhöht . dadurch wird auch die Reaktionsgeschwindigkeit aller chemischer reaktionen höher und der Apfel verdirbt schneller !\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Correct'},
 {'id': '64d40458-107c-403e-bc30-f51ff3b09495',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Je größer die Oberfläche vom Apfel ist , desto mehr können Stoffe an der Oberfläche reagieren , zb oxidieren ( also Braun werden ) .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': '7ac68634-48a9-48d5-9ed7-dea8ccf5b3e2',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Je höher der Zerteilungsgrad der Äpfel desto höher ist die Reaktionsgeschwindigkeit und somit der Verderblichkeitsprozess .\nDurch die Zerteilung liegt eine größere Oberfläche vor , sodass megr Teilchen mit anderen Teilchen reagieren können , und somit die Reaktion schneller abläuft .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Correct'},
 {'id': 'e3ef99a8-eac1-4d8b-a931-118e5df07bfc',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Umso kleiner die Apfel zerschnitten sind , umso mehr Oberfläche liegt frei , um zu reagieren .\nDabei Oxidiert die Oberfläche und der Apfel wird braun .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': '43aad239-c10b-4e7d-96a7-f09d7167a77a',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Wenn wie den apfel zerteilen vergrözern wir seine oberfläche und somit steigt die zerfallsrafte\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': 'a0cdc779-6a08-467a-9fe3-f0efc818cc93',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Je kleiner Zerteilt ein Apfel ist desto höher ist die Fläche an der zb. Luft und Bakterien auftreten können .\nDurch die höherer Angriffsfläche sind auf generell mehr Teilchen vorhandene die reagieren können .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': 'aa1f1fe1-3f87-42a7-b14b-4f8e33fee87f',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': '- Apfel kann unter kühlen Bedingungen länger haltbar bleiben und verdirbt nicht so schnell , da die Reaktionsteilnehmer mit geringerer Geschwindigkeit bewegen\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': 'f3456c74-8193-4942-b66d-c4c1dde62a3f',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Das Zerteilen der Äpfel führt zu einer schnelleren Verderbung der Äpfel .\nDie Äpfel bieten anderen Reaktaten mehr Fläche durch die zerteilte Form .\nEs ist logisch , da mehr Fläche bei selben Volumen durch das Zerteilen entsteht .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': '46361fa0-d6b6-477f-8e70-2c7245b9de17',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Wenn man einen Apfel zerteilt , verdirbt er schneller .\nDie Reaktionsgeschwindigkeit steigt .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': '18360f3c-ac1e-480e-8c98-ae19791426cc',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'durch das zerteilen gibt man eine grössere oberfläche frei wo die kälte aufgenommen werden kann\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': '99c899cf-5168-4616-9991-8b9986d53d2f',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Wie in den vorherigen Feldern bereits angegeben denke ich , dass das Zerteilen der Äpfel dafür sorgt , dass diese deutlich schneller verderben .\nDies liegt zum Einen am Fehlen der schützenden Schale und zum Anderen an der Tatsache , dass nun z. B. Sauerstoff in den Apfel gelangt .\nDieser kann zur Oxidation von einzelnen Bestandteilen des Apfels führen .\nDa ein Apfel sehr zuckerreich ist stellt er einen energiereichen Nährboden für Pilze oder Bakterien dar .\nIn Kombination mit dem zugeführten Sauerstoff können aerobe Organismen ebenfalls den Apfel befallen .\nDiese zersetzen den Apfel dann in verschiedene Abbauprodukte , die unter Umständen für den Menschen schädlich sind .\nMutmaßlich wird der Apfel auch teilweise vergoren .\nDiese Abbauprodukte riechen für den Menschen unangenehm .\nDiese Folgen sind nur ( fundierte ) Spekulation , ich habe keine weiteren Quellen genutzt .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Correct'},
 {'id': 'a32595a6-fa4b-4236-9c01-122337da9934',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Wenn man möglichst lange etwas von den Äpfeln haben will , sollte man sie nicht stark zerkleinern , da so die Reaktionsgeschwindigkeit zunimmt .\nUmso kleiner das Teilchen , desto größer die " Angriffsfläche " für Stoffe , die den Prozess des Verderbens so beschleunigen .\nWenn Teile ( natürlich mit einer gewissen Kraft ) aufeinander treffen , entstehen die Produkte .\nBei dem Zerkleinerjngskraft ist es schon mitten in der anderen Flüssigkeit verteilt und so müssen sie sich nicht erst finden .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Correct'},
 {'id': '0b8eecc3-d333-4215-89d9-58ddc840226b',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Das Zerteilen von Äpfeln kann den Verderblichkeitsprozess beschleunigen , da dabei mehr Oberfläche des Fruchtfleisches freigelegt wird , was zu einem verstärkten Kontakt mit Sauerstoff führt .\nDies kann zu einer Oxidation von Enzymen und Nährstoffen führen , was das Verderben beschleunigt .\nDie Zerteilen von Äpfeln kann also dazu führen , dass sie schneller verderben , insbesondere wenn sie nicht sofort gegessen oder gekühlt werden .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Correct'},
 {'id': '8fe73c5b-6778-4ed8-a085-ec471994c6ed',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Wie im Vorherigen Versuch war es so , dass umso kleiner das Produkt wird umso schnell reagiert es .\nBeim Apfel ist es so , dass wenn er geschnitten wurde wird die Fläche des Äpfeln Größer wodurch er schneller verderbt .\nJedoch sind auch die äußeren Einflüsse wichtig , wie zum Beispiel die Temperatur oder ob das stück Apfel in der Sonne liegt .\nDurch wärme und Sonne wird Wasser aus dem Apfel entzogen , wodurch er die Reaktionsgeschwindigkeit zunimmt .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': '53db6745-6e91-4239-a05a-9811931777b3',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Je kleiner der Apfel zerteilt ist desto schneller verdirbt er\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Incorrect'},
 {'id': 'c5b0f1b5-e96d-42ea-8d7f-3acf6e7caa24',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',
  'question': 'Beurteile das Zerteilen der Äpfel hinsichlich der Geschwindigkeit des Verderblichkeitsprozesses (Hinweis: wenn Du fachliche Informationen zu chemischen Abläufen des Verderbens einbeziehen möchtest, kannst Du diese unter Angabe der Quellen recherchieren und einbinden).',
  'answer': 'Umso kleiner die Äpfel geschnitten sind ( umso höher der Zerteilungsgrad ) , desto schneller verderben die Äpfel\n',
  'rubric': {'Incorrect': ['Die Schüler:innen beurteilen die Verderblichkeit der Äpfel nicht auf Basis des Kollisionsmodells',
    'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel teilweise auf Basis des Kollisionsmodells.'],
   'Correct': 'Die Schüler:innen beurteilen die Verderblichkeit der Äpfel umfassend auf Basis des Kollisionsmodells.'},
  'score': 'Correct'},
 {'id': 'd29d7b5f-4e03-4c98-b029-eb2dd1cd8b7f',
  'question_id': '920df344-fe5c-4f48-ae64-a8458e8db40a',

In [21]:
DEFAULT_GRADE = "incorrect"

for response_id, applications in application_results_dict.items():

    original_response_id = (
        theory["all_responses_df"]
        .set_index("response_id")
        .loc[response_id, "original_response_id"]
    )

    if not applications:
        amati_dict = {"amati": {'literals':[], "prediction": DEFAULT_GRADE}}
    else:
        amati_dict = get_json_from_rule(application_results_dict[response_id][0])

    for c in bea_data:
        if c["id"] == original_response_id:
            c.update(amati_dict)
            bea_data_with_amati.append(c)

In [22]:
bea_data_with_amati

[{'id': 'd49e5db1-8757-4718-8b51-7ec94f328fc5',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Durch die Kälte finden Biochemische Reaktionen weniger bis garnicht statt .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect',
  'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"kälte"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 {'id': '98fa8dc4-1c7e-4faa-b618-f553ce0b8a49',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Durch das kühlen der Apfel ist die Reaktion ( Das verwesen ) sehr stark verlangsamt . da die energie der einzelnen Teilchen so gesenkt wird das auch bei einem aufeinanderprallen der teilchen die wahrscheinlichkeit auf einen erfolgreichen Zusammenstoß recht gering ist .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Correct',
  'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"zusammenstoß"',
     'id': '@1'}],
   'prediction': 'correct'}},
 {'id': 'a4d97e5f-b2cf-484f-855b-ef248aa5e287',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Durch die Lagerung im kühleren Medium , kann der Flüssigkeitsgehalt nicht sinken , da das Wasser so nicht verdampfen kann .\nSomit bleiben Lebensmittel länger frisch .\nBei gefrorenen Lebensmitteln wird die Haltbarkeit deutlich verlängert .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect',
  'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"bleiben"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 {'id': '80539cd0-06d8-4450-a788-3448ab64d2dc',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Die Kühlung verlangsamt die Reaktionen .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect',
  'amati': {'literals': [], 'prediction': 'incorrect'}},
 {'id': '77b3a36c-dc5e-466a-b85b-44bba5abbb8f',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Dadurch , dass man Lebensmittel kühlt , bleibt der Wassergehalt der Lebensmittel erhalten .\nDadurch werden die Lebensmittel nicht so schnell schlecht , da im Kühlschrank keine Wärmeenergie vorhanden ist , die dafür sorgen könnte , dass der Wassergehalt der Lebensmittel sinkt .\nDazu kann man auf makroskopischer und submikroskopischer Ebene Beobachtungen anführen , um zu erkennen wie zum Beispiel die Teilchen sich verhalten und wie sich die Form des Nahrungsmittel verändert .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect',
  'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"bleiben"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 {'id': 'c0b536a3-8c85-44dd-8072-d6c257fc9376',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Wenn Lebensmittel gekühlt werden , halten diese sich länger .\nDie Teilchenbewegung wird von der Temperatur beeinflusst und diese bewegen sich langsamer , je geringer die Temperatur ist .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect',
  'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"halten"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"langsam"',
     'id': '@2'}],
   'prediction': 'incorrect'}},
 {'id': '6905eb11-951f-4670-a593-1a3016a2d106',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Durch eine Kühlung der Lebensmittel vermeidet man eine schnelle Reaktion der Lebensmittel , die diese nicht mehr genießbar machen würde .\nWenn man als Beispiel die Milch nimmt , so muss diese gekühlt werden , da ansonsten es schneller zu einer Reaktion kommen würde , der diese Milch sauer machen würde .\nDurch eine niedrigere Temperatur wird die Mindestenerdie für eine REaktion oftmals nicht erreicht oder hinausgezogert .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect',
  'amati': {'literals': [], 'prediction': 'incorrect'}},
 {'id': 'd3c3cb05-c342-4cdf-b3e3-9f3a78e8ccba',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Durch die Kühlung von Lebensmitteln sinkt die Temperatur bei den Lebensmitteln .\nJe niedriger die Temperatur , desto langsamer ist die Reaktionsgeschwindigkeit , da die Teilchen sich langsamer bewegen .\nSomit kommt es zu weniger effektiven Zusammenstößen und der chemische Prozess wird verlängert .\nDie Lebensmittel halten länger .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Correct',
  'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"zusammenstoß"',
     'id': '@1'}],
   'prediction': 'correct'}},
 {'id': '4f6d3cd5-3d6b-4a11-9bc4-37b9e41987c4',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Kühlung führt zu niedrigen Temperaturen .\nJe niedriger die Temperatur ist , desto langsamer ist die Reaktionsgeschwindigkeit , da die Teilchen , wenn man sie auf submikroskopischer Ebene betrachtet , sich langsamer bewegen .\nDeswegen bringen wenige ausreichend Energie auf und es kommt seltener zu effektiven Zusammestößen .\nIndem man also die Temperatur verringert , verlangsamt man chemische Prozesse .\nDies schließt auch die Prozesse ein , die für das Verderben von Lebensmitteln verantwortlich sind , wodurch die Lebensmittel länger haltbar sind .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Correct',
  'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"reaktionsgeschwindigkeit"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"bewegen"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'correct'}},
 {'id': 'b377a99d-752d-4ca6-9380-c01a5ef9633a',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Da eine höhere Temperatur die Tielchenbewegung erhöht und viel mehr die mindet NEergie aufbringen , sollte iene kühlung das genaue Gegenteil bewikren und die REaktion verlangsamen wodurch die Produkte länger haltbar sind\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect',
  'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"aufbringen"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 {'id': '54bb785d-763f-4600-9f96-c651cf517f8c',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Bei großer Hitze laufen Reaktionen schneller ab . der Umkehrschluss davon ist , dass sie bei kälte deutlich langsamer ablaufen und so Verderbungsprozesse verlangsamt werden können .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect',
  'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"kälte"',
     'id': '@1'}],
   'prediction': 'incorrect'}},
 {'id': '3caed02b-6520-45e4-92d8-ecc20abde242',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Die kalten Temperaturen verlangsamen die Reaktionsgeschwindigkeiten der Reaktionen , die zum Verderben führen , Auf submikroskopischer Ebene kann man sich Teilchen vorstellen , die sich sehr langsam bewegen , weshalb es weniger effektive Zusammenstöße in einem Zeitraum gibt .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Correct',
  'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"zusammenstoß"',
     'id': '@1'}],
   'prediction': 'correct'}},
 {'id': '3d2554c3-e29e-4405-ac40-7a50a28603af',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Da die niedrige Temperatur die Aktivirungsenergie herrunterschraubt haben die Teilchen nicht mehr genügend Energie um efizient zu Reagieren .\nDurch die verlangsamte Reaktionsgeschwindigkeit verlangsamt sich auch der ganze Reaktionsablauf der Gärung . daher ist es hilfreich wenn Lebensmittel im Kühlen gelagert werden , denn dann wird die Reaktion in ihrem inneren verlangsamt .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Correct',
  'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"lagern"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"reaktion"',
     'id': '@2'},
    {'pred': 'precedes', 'order': ['@1', '@2']}],
   'prediction': 'correct'}},
 {'id': '935d424b-626e-4a08-a83b-8422f3e27852',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Die Lebensmittel halten sich länger , da bei kühleren Temperaturen die Teilchen verlangsamt sind und somit eine Reaktion deutlich langsamer von statten geht .\nSomit halten die Lebensmittel länger und werden nicht so schnell schlecht .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],
   'Correct': 'Die Schüler:innen eklären den konservierenden Effekt der Kühlung aus reaktionskintischer Perspektve un wenden kinetisches Wissen umfassend auf das konkrete Phänomen an.'},
  'score': 'Incorrect',
  'amati': {'literals': [{'pred': 'contains',
     'document': 'student_response',
     'lemma': '"halten"',
     'id': '@1'},
    {'pred': 'contains',
     'document': 'student_response',
     'lemma': '"langsam"',
     'id': '@2'}],
   'prediction': 'incorrect'}},
 {'id': '102068e0-5126-42cb-9412-64e5530dad03',
  'question_id': '0f235f9a-64f8-4790-917d-23e0a15077c5',
  'question': 'Erläutere die konservierende Wirkung einer Kühlung aus reaktionskinetischer Perspektive und beziehe Dich auch hierbei auf die unterschiedlichen Betrachtungsebenen der Chemie.',
  'answer': 'Da die Reaktionsgeschwindigkeit steigt , je höher die umgebenden Temperaturen sind , sorgt eine Kühlung für die Verlangsamung von Prozessen des Verderbens .\nDas liegt daran , dass die geringe Temperatur die Geschwindigkeit der Teilchen verringert und somit die Wahrscheinlichkeit auf einen effektiven Zusammenstoß verringert wird .\nDie Kollisionen sind jedoch notwendig , damit bspw. Ein Apfel verderben kann .\n',
  'rubric': {'Incorrect': ['Die Schüler:innen erklären den konservierenden Effekt der Kühlung nicht aus reaktionskinetischer Perspektive.',
    'Die Scüler:innen erklären den konservierenden Effekt der Kühlung aus reaktionskinetischer Perspektive, wenden kinetisches Wissen aber nur teilweise (wenigstens ein Aspekt) auf das konkrete Phänomen an.'],

OK, that seems to be working OK (fingers crossed).

So now let's apply to the whole set of theories. I'll need to do this twice: once for the training data and once for the trial data.

## Training data

In [23]:
JSON_DATA_FILE = "/Users/alistair.willis/repos/bea-2026/BEA Shared Task 2026 on Rubric-based Short Answer Scoring for German/updated/2way/ALICE_LP_train_2way__v2.json"

with open(JSON_DATA_FILE) as fIn:
    bea_data = json.load(fIn)

bea_data_with_amati = []

In [25]:
for filename in glob.glob(os.path.join(THEORY_ROOT_DIR, "*.pickle")):
    print(filename)

    with open(filename, "rb") as fIn:
        theory = pickle.load(fIn)

    application_question_ss = (
        theory["all_questions_df"]
        .set_index("original_question_id")
        .T[theory["original_question_id"]]
    )

    application_responses_df = theory["all_responses_df"][
        theory["all_responses_df"]["question_id"]
        == application_question_ss["question_id"]
    ]

    application_texts_used = [
        application_question_ss["question_id"],
        application_question_ss["correct_id"],
        application_question_ss["incorrect_1_id"],
        application_question_ss["incorrect_2_id"],
    ] + list(application_responses_df["response_id"])

    application_text_df = theory["all_text_df"].query(
        "`id`.isin(@application_texts_used)"
    )[["id", "i", "lemma"]]

   
    application_results_dict = amati.apply_theory(
    theory["theory"],
    responses_df=application_responses_df,
    text_df=application_text_df,
    rulesstring=theory["rules"],
    question_ss=application_question_ss,
)
    

    DEFAULT_GRADE = "incorrect"

    for response_id, applications in application_results_dict.items():

        original_response_id = (
        theory["all_responses_df"]
        .set_index("response_id")
        .loc[response_id, "original_response_id"]
    )

        if not applications:
            amati_dict = {"amati": {'literals':[], "prediction": DEFAULT_GRADE}}
        else:
            amati_dict = get_json_from_rule(application_results_dict[response_id][0])

        for c in bea_data:
            if c["id"] == original_response_id:
                c.update(amati_dict)
                bea_data_with_amati.append(c)

/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_5f7bd982-606b-45e4-bf39-89db6714a621_2026-03-18_12:52:28.028319.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_35d897f0-c1b4-422c-9a33-43e7da1ffe27_2026-03-18_12:57:35.168998.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_52f6e329-eea6-423b-8d6a-047448d02c3f_2026-03-18_15:45:58.021429.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_c405c4a8-83f2-4ddf-b0cf-941a3356b251_2026-03-18_16:59:35.923009.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_0235896f-1570-418a-a34d-7bc3ea0f82b9_2026-03-18_14:07:56.575271.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_920df344-fe5c-4f48-ae64-a8458e8db40a_2026-03-18_15:24:00.591946.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_c51b89a6-0219-4eee-bb89-b2b5168998f5_2026-03-18_14:12:46.706850.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_0f036c26-4a47-48ba-b913-f27487286ac7_2026-03-18_12:23:14.044820.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_48071573-9e44-4ae9-b08c-2b19b6ee58d6_2026-03-18_12:27:26.893725.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_dad43e50-3167-41d6-996c-5b6e5f200c07_2026-03-18_13:59:21.119527.pickle
/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260318/theory_b85b1a95-35ba-473e-a164-4602a4a13a2f_2026-03-18_16:01:01.534496.pickle

KeyError: 'Witnesses'

In [ ]:
with open('train_2way_with_prediction.json', 'w') as fOut:
    json.dump(bea_data_with_amati, fOut)

## Trial data

In [ ]:
JSON_DATA_FILE = "/Users/alistair.willis/repos/bea-2026/BEA Shared Task 2026 on Rubric-based Short Answer Scoring for German/updated/2way/ALICE_LP_trial_2way___v2.json"

with open(JSON_DATA_FILE) as fIn:
    bea_data = json.load(fIn)

bea_data_with_amati = []

In [ ]:
for filename in glob.glob(
    "/Users/alistair.willis/repos/bea-2026/2-way/theories/run_20260316/*.pickle"
):

    print(filename)

    with open(filename, "rb") as fIn:
        theory = pickle.load(fIn)

    application_question_ss = (
        theory["all_questions_df"]
        .set_index("original_question_id")
        .T[theory["original_question_id"]]
    )

    application_responses_df = theory["all_responses_df"][
        theory["all_responses_df"]["question_id"]
        == application_question_ss["question_id"]
    ]

    application_texts_used = [
        application_question_ss["question_id"],
        application_question_ss["correct_id"],
        application_question_ss["incorrect_1_id"],
        application_question_ss["incorrect_2_id"],
    ] + list(application_responses_df["response_id"])

    application_text_df = theory["all_text_df"].query(
        "`id`.isin(@application_texts_used)"
    )[["id", "i", "lemma"]]

    application_results_dict = amati.apply_theory(
        theory["theory"],
        responses_df=application_responses_df,
        text_df=application_text_df,
        rulesstring=theory["rules"],
        question_ss=application_question_ss,
    )

    DEFAULT_GRADE = "incorrect"

    for response_id, applications in application_results_dict.items():

        original_response_id = (
            theory["all_responses_df"]
            .set_index("response_id")
            .loc[response_id, "original_response_id"]
        )

        if not applications:
            amati_dict = {"amati": {"literals": [], "prediction": DEFAULT_GRADE}}
        else:
            amati_dict = get_json_from_rule(application_results_dict[response_id][0])

        for c in bea_data:
            if c["id"] == original_response_id:
                c.update(amati_dict)
                bea_data_with_amati.append(c)

In [ ]:
with open('trial_2way_with_prediction.json', 'w') as fOut:
    json.dump(bea_data_with_amati, fOut)