# Extractor

This will create a pickle file which contains the info needed for the learner and theory evaluator.

I don't think I need to add prolog/clingo clauses... that happens in the `amati_bea.py` program.

In [1]:
import pandas as pd

from pyrsistent import pmap

from itertools import count
from string import whitespace
import pickle

from compound_split import char_split, doc_split
import phunspell

## Part 1: load in the data

In [2]:
with open(
    "//Users/alistair.willis/repos/bea-2026/BEA Shared Task 2026 on Rubric-based Short Answer Scoring for German/updated/2way/ALICE_LP_train_2way__v2.json"
) as fIn:
    j1_df = pd.read_json(fIn)

j1_df["partition"] = "train"

j1_df.head()

,id,question_id,question,answer,rubric,score,partition
0,73b0b485-5e89-40d8-ae68-4a650d4670c4,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,Bei einem höheren Zerteilungsgrad ( hier das Z...,{'Incorrect': ['Die Schüler:innen beurteilen d...,Incorrect,train
1,0c46f560-fcb4-4ea4-a540-cc2b96512b1c,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Das Größte apfelstück , also das mildem gering...",{'Incorrect': ['Die Schüler:innen beurteilen d...,Correct,train
2,467514d6-45d6-4f33-a1aa-dab58cadb9a7,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,verderben schneller\n,{'Incorrect': ['Die Schüler:innen beurteilen d...,Incorrect,train
3,b570cf0d-d29d-4add-bc9a-53156bb68003,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,Durch zerteilen der Äpfel wird dessen oberfläc...,{'Incorrect': ['Die Schüler:innen beurteilen d...,Correct,train
4,64d40458-107c-403e-bc30-f51ff3b09495,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Je größer die Oberfläche vom Apfel ist , desto...",{'Incorrect': ['Die Schüler:innen beurteilen d...,Incorrect,train

In [3]:
with open(
    "/Users/alistair.willis/repos/bea-2026/BEA Shared Task 2026 on Rubric-based Short Answer Scoring for German/updated/2way/ALICE_LP_trial_2way___v2.json"
) as fIn:
    j2_df = pd.read_json(fIn)

j2_df["partition"] = "trial"

j2_df.head()

,id,question_id,question,answer,rubric,score,partition
0,f069275a-e786-4ba5-8c15-4349c138c15e,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,Durch Zerteilen der Äpfel ändert sich das Verh...,{'Incorrect': ['Die Schüler:innen beurteilen d...,Incorrect,trial
1,659094ae-3233-4a20-9da7-200b3eed9738,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,Zerteilter Apfel = höherer Zerteilungsgrad = h...,{'Incorrect': ['Die Schüler:innen beurteilen d...,Correct,trial
2,52fb2775-9aed-46c4-8388-d4bb4076cc7e,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Je öfter der Apfel zerteilt wurde , desto höhe...",{'Incorrect': ['Die Schüler:innen beurteilen d...,Correct,trial
3,ad9c1e35-0ac1-4b17-9032-b052d77da325,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,äpfel verderben schneller bei höheren temperat...,{'Incorrect': ['Die Schüler:innen beurteilen d...,Incorrect,trial
4,b8ce1bd1-3d2b-4c0b-8da3-96534539b9cc,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Je kleiner die Äpfel geschnitten werden , dest...",{'Incorrect': ['Die Schüler:innen beurteilen d...,Correct,trial

In [4]:
j_df = pd.concat([j1_df, j2_df], ignore_index=True)

j_df

,id,question_id,question,answer,rubric,score,partition
0,73b0b485-5e89-40d8-ae68-4a650d4670c4,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,Bei einem höheren Zerteilungsgrad ( hier das Z...,{'Incorrect': ['Die Schüler:innen beurteilen d...,Incorrect,train
1,0c46f560-fcb4-4ea4-a540-cc2b96512b1c,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Das Größte apfelstück , also das mildem gering...",{'Incorrect': ['Die Schüler:innen beurteilen d...,Correct,train
2,467514d6-45d6-4f33-a1aa-dab58cadb9a7,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,verderben schneller\n,{'Incorrect': ['Die Schüler:innen beurteilen d...,Incorrect,train
3,b570cf0d-d29d-4add-bc9a-53156bb68003,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,Durch zerteilen der Äpfel wird dessen oberfläc...,{'Incorrect': ['Die Schüler:innen beurteilen d...,Correct,train
4,64d40458-107c-403e-bc30-f51ff3b09495,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Je größer die Oberfläche vom Apfel ist , desto...",{'Incorrect': ['Die Schüler:innen beurteilen d...,Incorrect,train
...,...,...,...,...,...,...,...
7894,d9702059-4d24-4e5e-bb24-7a66cbb57547,e71649c1-57e4-4cf6-a5fe-c55b8568add3,Beschreibe Auffälligkeiten der dargestellten d...,Nicht bei jeder Kollision sind die Edukte zu e...,{'Incorrect': ['Die Schüler:innen beschreiben ...,Correct,trial
7895,240f6b33-a928-4604-9b5f-03b25e40c432,e71649c1-57e4-4cf6-a5fe-c55b8568add3,Beschreibe Auffälligkeiten der dargestellten d...,Nicht alle Kollisionen der Edukt-Teilchen führ...,{'Incorrect': ['Die Schüler:innen beschreiben ...,Correct,trial
7896,874dd924-a661-4cad-a6bb-8649c0f2b51f,e71649c1-57e4-4cf6-a5fe-c55b8568add3,Beschreibe Auffälligkeiten der dargestellten d...,Hab ich doch in Aufgabe 2 gemacht\n,{'Incorrect': ['Die Schüler:innen beschreiben ...,Incorrect,trial
7897,af90be9a-a1fd-4cd2-9ac3-45ff308d429a,e71649c1-57e4-4cf6-a5fe-c55b8568add3,Beschreibe Auffälligkeiten der dargestellten d...,Nicht immer führt eine Kollision zu einer Reak...,{'Incorrect': ['Die Schüler:innen beschreiben ...,Incorrect,trial
7898,654660ed-7a20-420c-9a71-9a14342bd3f4,e71649c1-57e4-4cf6-a5fe-c55b8568add3,Beschreibe Auffälligkeiten der dargestellten d...,Farbe und Form der Elemente .\n,{'Incorrect': ['Die Schüler:innen beschreiben ...,Incorrect,trial

In [5]:
j_df["rubric"].apply(tuple).drop_duplicates()

0    (Incorrect, Correct)
Name: rubric, dtype: object

There's a `Correct` and an `Incorrect` rubric for each question. There are two versions of each of the Incorrect rubrics.

Let's tidy things up a bit so the ids are more readable.

In [6]:
question_ids = {
    q_id: f"q_{str(q1).zfill(2)}"
    for (q_id, q1) in zip(set(j_df["question_id"]), count())
}

question_ids

{'fcf5ff56-5e98-4eb7-8df3-afb0544d9739': 'q_00',
 'c51b89a6-0219-4eee-bb89-b2b5168998f5': 'q_01',
 '379ba896-bb8f-440d-9d32-5dc9ca0297fe': 'q_02',
 'cb99dfb3-2788-4a10-b934-7ea8276b2b44': 'q_03',
 'b85b1a95-35ba-473e-a164-4602a4a13a2f': 'q_04',
 '0a8e8837-0a58-4e89-96c2-c44ae7281535': 'q_05',
 '509987fb-fce6-4d2f-98b8-bb4ba3761aae': 'q_06',
 'dad43e50-3167-41d6-996c-5b6e5f200c07': 'q_07',
 '278f349f-1552-41c4-bec2-1de41838f229': 'q_08',
 'bbb0e987-436a-46f3-b16d-34fd708f8236': 'q_09',
 '945f0e58-761c-4c89-af96-0261821fcf11': 'q_10',
 'e5e2e91d-9054-4996-a3bf-62518e06a07f': 'q_11',
 '52f6e329-eea6-423b-8d6a-047448d02c3f': 'q_12',
 '11be53c7-c020-445b-b3a4-409d4ba16347': 'q_13',
 'c8ee61ed-aa7c-44da-a43d-f862fa5cce8d': 'q_14',
 '48071573-9e44-4ae9-b08c-2b19b6ee58d6': 'q_15',
 '1f2f0773-54bb-4b72-963e-c3c946a1f53f': 'q_16',
 '18fab27c-7420-4b80-a5b4-cce94a9c315c': 'q_17',
 '1ed16c88-ff9d-488c-be13-6ba2be1d1cc0': 'q_18',
 'dee4136e-e922-4b83-8033-24350ea1610c': 'q_19',
 '06908246-ff47-414c-9db2-77df83e43aee': 'q_20',
 'b1a78d64-0171-4180-b564-1172fbb92608': 'q_21',
 '0235896f-1570-418a-a34d-7bc3ea0f82b9': 'q_22',
 '06cdfa3d-8d45-4fe3-85c8-505e1b1b4de2': 'q_23',
 '3a3b57d9-5af7-4515-9347-2cc1f91ffae1': 'q_24',
 'b1d2b0f3-f2d0-4be0-850f-1b7810acd965': 'q_25',
 '8e686080-6db7-473b-baa0-6f17412fae5c': 'q_26',
 'e6f0fdac-98cd-4ad5-a700-cb612f4ec827': 'q_27',
 'ecc59e41-4029-4d09-9a50-fb997d4daf0e': 'q_28',
 '0f036c26-4a47-48ba-b913-f27487286ac7': 'q_29',
 'c7a2c75a-980f-43c9-8366-490060bb7627': 'q_30',
 '8c1bd275-6ae7-4fd2-a2fb-8a965af31699': 'q_31',
 'b5fb6924-1da3-45b1-a386-68e95d80b057': 'q_32',
 '2f551477-6bc3-42bf-bee6-493eb83a8923': 'q_33',
 '72089129-da8d-4f2c-91ee-6ec1410a2721': 'q_34',
 'fabdb7c1-5afb-45cb-b0d2-dce923889ea8': 'q_35',
 '0f235f9a-64f8-4790-917d-23e0a15077c5': 'q_36',
 '5005b73d-b6bd-499c-8d6f-554785c4e523': 'q_37',
 'd14cc74c-805a-45f7-9ad3-2e9f19395ca0': 'q_38',
 '64636904-aab6-4e10-a4dc-39638117731a': 'q_39',
 '8a35dfaf-e9d0-466d-98b8-1e1b132bb450': 'q_40',
 '49441f3e-1d4b-4b06-9cd3-b6669884c2df': 'q_41',
 '3d62bda8-dc02-47aa-ae1e-dc0f5e2aef1b': 'q_42',
 '9f29fc63-85b9-4959-bb7e-dd3f169b862d': 'q_43',
 'ea3f9eac-c1d2-4bbc-8271-46786e9ccd20': 'q_44',
 'a400cdc0-ed2f-4adf-928d-816320717a92': 'q_45',
 'cfb7ac32-173c-4a66-9ee0-771a20eb93ed': 'q_46',
 '2dd5c077-0f51-41b0-9da0-0b59eb3328c3': 'q_47',
 '82aacab8-0c7f-4936-b93f-62c53670b5c3': 'q_48',
 'd9e775ff-b54e-4558-86eb-0251737ecdf1': 'q_49',
 'c7fac934-2a4b-49f0-b20b-568bb11557f2': 'q_50',
 '66703b48-f3b2-4853-82a0-00ba13379012': 'q_51',
 '0680d727-2e00-45e2-8ebc-0eea81f20937': 'q_52',
 '8144573c-97d6-484a-b68b-c16b7602fa7b': 'q_53',
 '33c179c8-ee50-4a7b-b139-8b2984356400': 'q_54',
 '9db508e5-9143-4cc1-a9a5-177237180d0b': 'q_55',
 'b3978794-9681-49bd-bc9b-d05bf8d226d8': 'q_56',
 '4ca6cd4c-9b4a-4226-89ec-14a4d8621968': 'q_57',
 'b835a560-6e0a-4dc2-a661-ce64a7d4eb39': 'q_58',
 'f97dc224-8c40-4a1e-be11-d71eeca0c510': 'q_59',
 '354d95b7-42b8-4e01-be2e-039149095d2d': 'q_60',
 'd1070d87-7bcb-4325-94b7-fc8370bd6ed5': 'q_61',
 '5f7bd982-606b-45e4-bf39-89db6714a621': 'q_62',
 '7e18c9c0-462a-4865-be25-1dd992b8af9f': 'q_63',
 '40c10a59-eeab-4673-b943-69e501cfef5f': 'q_64',
 'bd121004-afeb-4447-bb77-978e7502baa3': 'q_65',
 '186141c9-4307-4068-adc7-616b1f8c5e0a': 'q_66',
 '87ab08a3-0acb-4f5b-b1c8-927bb83c3842': 'q_67',
 'dddf3a9d-2f40-402c-b650-3db1b27128ca': 'q_68',
 '1e0b7fa1-1947-40eb-9ffa-b2a46853da49': 'q_69',
 '6e79e7db-57b6-444a-8cbc-a000932c6de8': 'q_70',
 '920df344-fe5c-4f48-ae64-a8458e8db40a': 'q_71',
 'c405c4a8-83f2-4ddf-b0cf-941a3356b251': 'q_72',
 'afdd3dad-858c-46e7-972e-d5909efbe9ce': 'q_73',
 '35d897f0-c1b4-422c-9a33-43e7da1ffe27': 'q_74',
 'b470d591-dc0c-41e1-afa7-4f212d6248e5': 'q_75',
 'e71649c1-57e4-4cf6-a5fe-c55b8568add3': 'q_76',
 '4b331fd2-8e92-4f74-90cd-615d90694463': 'q_77'}

In [7]:
response_ids = {
    r_id: f"r_{str(r1).zfill(4)}" for (r_id, r1) in zip(set(j_df["id"]), count())
}

response_ids

{'654462e4-1609-45cc-990c-aaff6e4e0d6b': 'r_0000',
 '5574aa4f-3e40-4939-aa1f-d8382f073330': 'r_0001',
 'a46214c9-49b1-4574-8c17-55c3d9443526': 'r_0002',
 '4f92a6aa-7d89-4223-b9e4-0e2a062c78c0': 'r_0003',
 'af4a4c5c-1c20-4e58-9092-1f9c39a3e620': 'r_0004',
 '574fb264-2f58-46c7-bff0-7b9413071f4a': 'r_0005',
 '04a4fee4-1dab-48d2-903b-a4159319d652': 'r_0006',
 '292b4ea4-4656-4a2b-9251-74b59c49f191': 'r_0007',
 '5a3751d4-8e92-461c-893d-2122852113d2': 'r_0008',
 '138bd7c9-9340-4ac6-99ec-4e5ed2ac80c5': 'r_0009',
 'fff59cf2-6900-4ef0-99c6-c40b8c1414b9': 'r_0010',
 'f846b367-a4ec-4f75-9530-10154d94e28b': 'r_0011',
 '31cde4be-b2b7-4d8d-8517-729d3267158b': 'r_0012',
 'd49e5db1-8757-4718-8b51-7ec94f328fc5': 'r_0013',
 'b3c04cc4-1af0-4275-91cc-55435df17851': 'r_0014',
 '6a4064d4-a436-4071-a2d1-ce74eab6ed6e': 'r_0015',
 'c16bd155-16b8-4919-8a59-6921130dfa59': 'r_0016',
 '8f24c48c-b28a-4fc9-9631-1f73557d31dc': 'r_0017',
 '61eb9c35-592a-40a9-aa6b-05f53b1469a5': 'r_0018',
 '112ebdb0-b1de-4ffb-9444-892a7967d29a': 'r_0019',
 '176eae37-44fb-4e37-b0fe-24e33baac1aa': 'r_0020',
 '03e172dd-8b95-4cc7-a796-bbafb1ae3734': 'r_0021',
 '246d4b21-3b38-4219-bae5-a63d1149bca2': 'r_0022',
 '20d8cef6-a722-4a37-9c0c-231cbcada357': 'r_0023',
 '98b191db-8b5f-43cc-91e3-b919b9daf0c5': 'r_0024',
 '54083a3f-fb25-446c-84ca-93886a269714': 'r_0025',
 'c70e6917-4e76-4acb-9472-c1c8d34abb14': 'r_0026',
 '45493a18-ca2b-42cd-9e75-ed44854a4c2a': 'r_0027',
 '561cb411-43e0-40bf-b348-893eb262e5a1': 'r_0028',
 '00cf9197-ada4-4740-947b-fd0ec5a1cae9': 'r_0029',
 '299925b9-35ab-4710-ba28-f4bd2e0d00d9': 'r_0030',
 '54972df0-4223-412c-b3a3-4aeb55e7b920': 'r_0031',
 '1b04942f-b5a5-4ead-b754-dccdd9ab20a9': 'r_0032',
 '95ecb28a-b82d-4b41-9ae2-2c7da7d6e5ea': 'r_0033',
 '341af1b0-bc71-444b-9ab1-41c2c50d263c': 'r_0034',
 '4174e18e-6ccc-4a2b-8f16-0d424e5b58e6': 'r_0035',
 'ae62e816-604b-40e2-a42c-4d853fcada32': 'r_0036',
 '61fb26ba-ef98-4d7d-b229-b2e32b179d6a': 'r_0037',
 'deca8ca9-7e61-4806-bd90-a3baca831e73': 'r_0038',
 '2bc006e9-5997-4dfa-a132-88361f838a4d': 'r_0039',
 'fdfc4a9c-73f5-41a4-82af-b67187ba96f1': 'r_0040',
 '14e648a8-97cf-4b3e-83eb-69a2273a28a5': 'r_0041',
 '3b8bf751-57bc-459f-b5f5-97bc74871101': 'r_0042',
 '396e4212-5bed-4bdc-aaa7-65d3a423ebdb': 'r_0043',
 '62178b9c-495f-4c75-b090-698e914661df': 'r_0044',
 'ca84b8e0-42cb-45e5-b378-3f8e5b7c9280': 'r_0045',
 'ceb01a02-e089-47cb-9396-5e6cbe5bc96d': 'r_0046',
 '6528ccd6-4a3d-4f20-a0d9-d63c48f0f14b': 'r_0047',
 '77000f3b-9714-4ed5-84d9-2cbe0a2be774': 'r_0048',
 'c58ce804-6521-4a5a-9894-b0e772002563': 'r_0049',
 '2a332bca-404f-4f54-8989-0c0a517764b8': 'r_0050',
 '7aeb8c3e-1978-47f2-99c1-86330c652b9b': 'r_0051',
 'c4cb5502-291d-4190-a103-290cf7106a53': 'r_0052',
 'cd2aba5b-7ba2-4b85-9aef-05f8a179014b': 'r_0053',
 '3667926b-d6ad-49e9-9cc8-e863c721be55': 'r_0054',
 '8b6732b3-c4c6-4183-808c-31cb97b21bd2': 'r_0055',
 '7066144f-2e73-4118-b9d8-1a4cf4e10ca6': 'r_0056',
 '0c68b2c3-9e0e-4474-9289-57710f7d84f3': 'r_0057',
 '9939bf51-97a1-4f9c-b0bc-195edf03da90': 'r_0058',
 'f9bfbace-813b-4a56-ab5a-a619a03d2499': 'r_0059',
 '349ffa37-591e-40f1-bdc5-0bac6609ec5e': 'r_0060',
 '2b374d89-d512-4c6f-a80e-ab2dda7c5d4d': 'r_0061',
 'ef55d855-2410-4eee-acda-d824fa7dae11': 'r_0062',
 'b3f61351-f871-49c6-bd41-2f98ad514a17': 'r_0063',
 'b744fa7e-642b-4a09-9c49-d5a37eebe512': 'r_0064',
 '0413e4f4-fb27-4fe4-86e3-37c092a2cd6b': 'r_0065',
 '29608bf6-1f21-4716-a11c-91c2513fc680': 'r_0066',
 '16bacf41-e95f-42a4-9da5-05024aff9b7c': 'r_0067',
 '3de45212-2555-4a3e-946c-695f76761e12': 'r_0068',
 '251607a5-b0d0-4a41-8ea7-99d299f450b4': 'r_0069',
 '250a194a-52ef-4410-963e-7d67e4645c6d': 'r_0070',
 'aca9d869-b18d-4075-9dcd-a0c5ddc89417': 'r_0071',
 '8463e761-2c90-4106-ab77-67b20b43ab91': 'r_0072',
 'fd9773e1-5553-4ae1-8c1d-c5b0830fb9ec': 'r_0073',
 '1e624e4a-dd79-48bf-9736-2e9a04a86819': 'r_0074',
 '8edec8d6-0384-4128-9a4e-4c158fcdafe7': 'r_0075',
 '3dddd7c1-0698-406f-b58d-5eb871a55660': 'r_0076',
 '242bb1be-0ec7-47ec-a2bf-fb50e53c0609': 'r_0077',
 '98fa8dc4-1c7e-4faa-b618-f553ce0b8a49': 'r_0078',
 'c9ee0e7e-1445-4d95-a5e5-52b90a1d6275': 'r_0079',
 'e119136c-20dd-4c88-9581-6a0fea6c45ee': 'r_0080',
 '7b942e9e-5abf-498c-b06f-572c37bcdc59': 'r_0081',
 '4110d8e8-335e-420d-9f72-bcdc476b6c9e': 'r_0082',
 '7fbb5cc0-58cc-4638-8ef7-2b57a68f2197': 'r_0083',
 '4c726cbe-3228-4840-9973-a7032b3ed3a3': 'r_0084',
 '139a75ab-16db-41bb-95bf-e4f0cb12bf76': 'r_0085',
 '92c68c41-c245-48cc-b552-f3b7a2556f14': 'r_0086',
 '20481677-e5c0-476c-a669-a9e20d0344fd': 'r_0087',
 '456f5879-dd70-4bbe-946f-39ee48febe12': 'r_0088',
 '73d2a251-e95c-4549-bcd2-3b8d196e0586': 'r_0089',
 'cc0aa02d-398f-428d-8a73-67b7e087a92f': 'r_0090',
 'c68f7dd8-478b-427b-bbcd-d2b477199918': 'r_0091',
 'db8b4e43-2bf9-4f39-a461-e463200f1546': 'r_0092',
 '4e1b89d1-a045-47ac-8175-6040eaec409b': 'r_0093',
 'c3be1510-d0a4-48ca-b432-4cbfd3e44c4c': 'r_0094',
 'f8499164-999d-4710-bf79-14861e1de49c': 'r_0095',
 'bed596a2-f018-4ba4-b73a-70e7b2309ed5': 'r_0096',
 'f0c6e473-dd08-4fee-b305-2cd03ed323a3': 'r_0097',
 'd31857fa-90a8-4fef-9550-94fab84370be': 'r_0098',
 '8f7ba5ea-ae45-4493-bba5-f766b830d256': 'r_0099',
 'b7e92aae-155d-4137-a5ac-07a39cb4f010': 'r_0100',
 '89c5933b-1083-4f3b-8e42-3df9c9c3f625': 'r_0101',
 'b570cf0d-d29d-4add-bc9a-53156bb68003': 'r_0102',
 'aafd1510-6a59-469f-8466-a73b7586b4c1': 'r_0103',
 '35e2aec7-bfca-42dd-aaaa-6addf37409df': 'r_0104',
 'a39726e8-7cc7-483d-98e3-d366728de840': 'r_0105',
 '665c8ab4-a386-4324-9d32-147cb27a5b2b': 'r_0106',
 '10ad94dd-a70f-44ba-91e6-6acd25ebd096': 'r_0107',
 '94d3211f-5d65-47fe-9234-a72535aff5e7': 'r_0108',
 '1fd88233-767b-42e7-9edc-8babbb9f4e71': 'r_0109',
 'a4d97e5f-b2cf-484f-855b-ef248aa5e287': 'r_0110',
 'e78122dd-9f3c-456e-a546-fc905b023807': 'r_0111',
 '634d118f-ced7-4d2a-82cd-4d28d8bc1be9': 'r_0112',
 '5b0dd8af-2478-4c33-920a-08591fe6e16c': 'r_0113',
 'c4d71b0d-b34a-4724-adfe-55b8d87ef20c': 'r_0114',
 '4cf98df5-8d79-4144-aeea-37df3bec5de5': 'r_0115',
 '128d8a30-7639-4abd-8da7-7e3129084c2a': 'r_0116',
 '00b40f3f-d788-4d0e-a769-62bada6e15c0': 'r_0117',
 '4037cfd7-1fd3-453d-aebe-662c3133358b': 'r_0118',
 '343e85e6-d4e8-40c4-ac7e-985d2af97560': 'r_0119',
 '4473c205-c08c-4ea5-b796-98b333498b44': 'r_0120',
 'bca7ca26-8389-46f0-817f-bb0007f94054': 'r_0121',
 'f4addedd-7586-4a1b-930c-d3d65c898fea': 'r_0122',
 '624295fa-2875-413d-b4c1-72a7bf9ede9f': 'r_0123',
 '8b8d8c0f-cebb-46fd-be2f-faef8ce23c19': 'r_0124',
 'aedfb78e-6b6e-4fda-9c2e-51e508465484': 'r_0125',
 'af7adfb6-b00d-4a1e-890a-8a882c17c67c': 'r_0126',
 'e959a593-0c81-493d-bee7-22a0f62f4b88': 'r_0127',
 '11e483f8-9c48-4d87-83e5-9c5f414b6c2c': 'r_0128',
 '6550b62c-cc65-458d-a609-a7a38c45cbca': 'r_0129',
 '064fe2dd-a941-431b-9647-dd1676a82d03': 'r_0130',
 '2ead52ec-c35c-4c29-8b7a-c8b5b54e4b14': 'r_0131',
 'bb5d85b7-a5ba-41b8-be21-8a0b23a63672': 'r_0132',
 '9fde2a66-c96c-47ba-9c0e-2c5049577ada': 'r_0133',
 '3eb8ef28-15c1-4080-9969-959ee7c084db': 'r_0134',
 'c22b4baa-838e-4993-b410-8cf865c52550': 'r_0135',
 '6803005e-c4d5-4ce5-b7f8-cd4f14eadb7e': 'r_0136',
 '07901a78-5440-4c22-ad32-44cd9c845073': 'r_0137',
 'ffde913f-268e-4108-9e73-d38fcfe2519c': 'r_0138',
 '5245d22c-9410-4974-8987-980d8f6be725': 'r_0139',
 '4c0659cd-d9ae-4485-a216-74ebb5972b6c': 'r_0140',
 'f4aab1a2-a8d1-4937-a825-e4325d57769d': 'r_0141',
 '0a839767-36d3-4da7-8b50-c8f9dfcc5d92': 'r_0142',
 '61dd77d6-7b42-4e87-9d0f-ef7b3b6ffc4d': 'r_0143',
 '9750dbeb-d8b4-4a73-b803-3ed134cf1263': 'r_0144',
 'c84ad2df-3bbf-49da-82b5-8cde299055ff': 'r_0145',
 'cbf734e9-c2eb-4e95-9eb9-9444b03f59a8': 'r_0146',
 '898dbe58-73a0-4f06-b2ca-96c8263fbb46': 'r_0147',
 '530bbe81-db5f-4bb3-b856-095e1147aba7': 'r_0148',
 '10f7b37f-71fe-41d9-a3a7-28690be48ece': 'r_0149',
 'af488940-639d-4bec-bab0-15717b25c829': 'r_0150',
 '947a1750-fc1d-4e8d-95a0-427ec584b146': 'r_0151',
 '12747721-2bff-4217-9c93-135b165d6a9d': 'r_0152',
 '4fd7e9f2-6ed2-4805-abc1-84f6444f2d7c': 'r_0153',
 '381f3e80-3c55-415b-9e92-267e3b437812': 'r_0154',
 '6f9b8f08-1db0-4f82-8614-479d6354276a': 'r_0155',
 '177ea85c-76b5-4cb9-97c0-5fbf31ec04f6': 'r_0156',
 '76cc188d-f2ba-4088-92f0-2451ef8c15c6': 'r_0157',
 '28cb2cc2-d386-4c5a-a348-4dd5ccf1e809': 'r_0158',
 'c1918925-7ad5-466a-a97c-ae439a44079b': 'r_0159',
 'c66aa950-42a7-4b94-8aaf-d8229a55a909': 'r_0160',
 'dd349581-a6a3-4eb8-b837-47bb4b8aa5c3': 'r_0161',
 '35431ac0-fbae-40ac-98bf-8364d952998e': 'r_0162',
 'a8a8fbb5-618b-4578-9d87-ab494dfc6e41': 'r_0163',
 '6e90a4c4-fc8e-4c11-bc6d-fc06f162c3ee': 'r_0164',
 'ce6c82bf-8031-4507-9ab8-73c21978a46b': 'r_0165',
 '336fec76-18e9-4d87-a65c-3e1264fa60c8': 'r_0166',
 '69a4f686-14f4-4a0a-8464-62214ea4faf1': 'r_0167',
 'fdc69526-62a0-40d1-92a1-1bedec67a49b': 'r_0168',
 'b46a9cfc-1635-426a-aa40-afa601b704f5': 'r_0169',
 '4cda1a35-54f3-4d38-8fc8-1d83c2d2a711': 'r_0170',
 'dccb8f88-8661-4e7b-ac12-c69d5dc555e3': 'r_0171',
 '8c66d345-0718-4ce7-bd5d-5ff6acdc65c2': 'r_0172',
 'd9e08643-71ae-4228-a2b4-22a36683159c': 'r_0173',
 '62a3a48c-9e17-4a14-b957-6bbe64178970': 'r_0174',
 'd792e6ea-0f4d-40e1-98cd-2692ed0053de': 'r_0175',
 '5b927c05-ad9a-4424-adbe-c6613b3f1fb0': 'r_0176',
 'd8478f05-edb9-4486-a06b-b12c54572ff0': 'r_0177',
 'e4d9c6e1-ed55-468a-9101-89218a989852': 'r_0178',
 '1a8c7e44-a67f-4730-88bb-02f9dc659e83': 'r_0179',
 'f6d1be0c-93b4-48ba-ba47-89d0148ab1d3': 'r_0180',
 'b1dec204-60c9-4faf-a3d7-86a122404626': 'r_0181',
 '6e71f130-6832-424b-a28f-5d407c23cf3d': 'r_0182',
 '44502915-e001-4dd4-b282-839aa4f24314': 'r_0183',
 '77ad3feb-cb37-48c2-a780-8c46bfde9686': 'r_0184',
 '458c549b-d58b-4cc0-a169-7d42a4646954': 'r_0185',
 '2b190bf4-c4f1-4e55-a6d9-ea748516b8b8': 'r_0186',
 '35c2bd42-0cf4-4830-b58f-e5699cf4249c': 'r_0187',
 'af5b0203-69fa-4940-ad0a-92fbfd64fed6': 'r_0188',
 '0f995bc0-f31f-4ffb-a3c0-4549c0108b61': 'r_0189',
 '6e9d0aac-80a1-4639-9c9b-5f7a441e878d': 'r_0190',
 '9e83cc53-d4d4-45f1-b64c-f0ea85aa4d33': 'r_0191',
 '7909ad25-8738-4474-b652-938bb32a2042': 'r_0192',
 'bfd02304-0474-4efe-bba7-9ef40546c85b': 'r_0193',
 '1050a0ab-4cb8-4bec-b30e-52b960e2d318': 'r_0194',
 '5aaeaacb-c7eb-431c-b00e-885a7c2604ba': 'r_0195',
 'd70ccb2f-f82d-41f6-a32b-c0a3f74ced29': 'r_0196',
 'd32eef49-5215-4661-9e87-bc709e11a95d': 'r_0197',
 'f1478477-dc5b-463b-98c6-a1670e56ced3': 'r_0198',
 'b3d640ec-c1ff-413d-83bf-9af38859eba1': 'r_0199',
 '028c7ad0-af71-48a2-a554-15101dcc9d96': 'r_0200',
 'b022a5d7-770e-42aa-b266-cff9ff76b3ea': 'r_0201',
 '1a8b7ba6-cd24-472c-84ee-176d2157cfad': 'r_0202',
 '3495934b-0de1-4ec4-87d7-782694eb63a0': 'r_0203',
 '66b89a55-37f4-44dd-9b00-266d0f98bf57': 'r_0204',
 '2ab707fb-c241-4009-b9c6-5feb42b22790': 'r_0205',
 'fd6359a0-b708-46c1-bb58-b3ae29a6bbdb': 'r_0206',
 '58e3b923-9298-44c8-a8ba-e105b249b6df': 'r_0207',
 '80539cd0-06d8-4450-a788-3448ab64d2dc': 'r_0208',
 'eaff108b-8b77-4ec4-9e12-a4a06a801249': 'r_0209',
 '80a24b01-e897-4b7e-830b-e3ca888071cf': 'r_0210',
 '83f3bec6-4f4a-41d5-a7e5-9407fd4816a5': 'r_0211',
 '6583203f-4220-4f65-8223-feef6fa93b2a': 'r_0212',
 '0ee64f49-38c8-4e1a-9dae-4dd30aaf4625': 'r_0213',
 'bc2a0f86-ec14-42c3-86a3-124d7ff08740': 'r_0214',
 'b9d42119-1b77-4521-955a-b132e1573a28': 'r_0215',
 '0146e0a6-2ccc-4efb-936c-42e1c5862832': 'r_0216',
 'aa862a26-fb91-400f-aedc-c24a25adf948': 'r_0217',
 '45b4d477-e934-4cb2-82d6-b268ba89ae07': 'r_0218',
 'baf20171-9e73-4445-a66e-4a265a6149fd': 'r_0219',
 '42050413-55fb-48da-af85-6eee35ba49f3': 'r_0220',
 '85481be7-eb49-4552-a114-90b4d8a3d1b7': 'r_0221',
 'fe059af7-1e9b-40dd-936d-bb47e571bada': 'r_0222',
 '1f0ba569-d714-4040-9a07-ec17ea4769c7': 'r_0223',
 '41ee5559-dcc7-4552-9e36-b212d787637d': 'r_0224',
 '1d6bf1b0-7a8c-4a50-8030-78d099fe1d22': 'r_0225',
 'c7fb2179-3f83-4986-bdc7-8c7a53ba9966': 'r_0226',
 'a5fa29df-520b-409d-9e03-12f72e556cbe': 'r_0227',
 '66295ab2-0ed1-4843-a75b-f9e71323cffb': 'r_0228',
 '78519adc-6281-41c0-b039-707cf6c5a1b4': 'r_0229',
 '33087892-f6e9-42de-8832-c1e5543dc4bf': 'r_0230',
 '460ee11a-20ae-4b55-a327-dafe656a3e04': 'r_0231',
 'a18cb73f-68bf-4e60-82d0-2371f8332ae8': 'r_0232',
 'e51675ac-f3b1-42f9-ab4a-3be5c7bad350': 'r_0233',
 'ed2b9b5a-d239-483b-8bf3-900abc5afc24': 'r_0234',
 '7fae508f-c7b0-40fc-8479-04ae7bc0d756': 'r_0235',
 '37821369-f453-4d51-98d4-9ae040ce4bea': 'r_0236',
 '42d0ca37-d75a-492d-a465-a7cea50c95ae': 'r_0237',
 '33716472-8000-4b61-aaa4-2b15491ddeaf': 'r_0238',
 'e020322b-1b00-41d4-a093-d68c075a80f1': 'r_0239',
 'd08ae218-ad99-4ae8-bd97-146148fda812': 'r_0240',
 'c38b9994-0c36-421a-a151-e91c34c0871a': 'r_0241',
 '97a3f561-c248-4928-ba9b-6c5ff7058b05': 'r_0242',
 '0fedf53d-f567-46ba-adb3-cf390d23772b': 'r_0243',
 '21597c3a-5dcf-427a-8508-590914ff8a7a': 'r_0244',
 'a935723c-010e-4601-b8f4-284e7342b601': 'r_0245',
 '726a3bab-0290-4137-aa29-34e3e5b4273e': 'r_0246',
 'c363f331-e22b-4649-8066-d1cf99451995': 'r_0247',
 '1b67776f-3e1a-466d-8c42-f0a5290cbce4': 'r_0248',
 '352ca2b9-94ff-4405-8f3b-543cc161fd36': 'r_0249',
 'd4b916f8-eaa9-4eb4-9356-cf79ca9f82c1': 'r_0250',
 '6f80d72d-8665-4a4d-873f-f5fd2eedf596': 'r_0251',
 'a248bde8-d526-4bdd-8f9f-8391a5ef3988': 'r_0252',
 '17bdae3c-1020-40bf-b329-04c7eb37b670': 'r_0253',
 'c3096724-79c2-4f18-be34-e2a3bc798b20': 'r_0254',
 'effd99d9-ad16-4048-a1df-d70ab1f64151': 'r_0255',
 '81389a26-65ff-499a-90cd-2b67e231438c': 'r_0256',
 '04f6bdc9-5bee-418f-bbaa-c5a209b726ea': 'r_0257',
 '867d6970-ea1d-466f-8d70-76a22438396e': 'r_0258',
 '9955dfc6-0d88-435d-a870-ec8a6b1fa824': 'r_0259',
 '7c84e6d5-22b7-41ac-9b6b-dda373a53f4b': 'r_0260',
 '80ad146b-7213-4c08-9051-6a41d1afa0d9': 'r_0261',
 '659094ae-3233-4a20-9da7-200b3eed9738': 'r_0262',
 'e1da8961-d96f-4b5c-80f2-915f31fb3419': 'r_0263',
 '90b7723a-79e6-4303-a908-ff92d5a0911f': 'r_0264',
 '68a06cbb-115c-4d73-a988-c18ed16e9c03': 'r_0265',
 '2e46f474-864f-41c5-9a9e-076fbd686789': 'r_0266',
 'e4626193-99d6-4a6d-86f9-1542dad1d092': 'r_0267',
 'cac468f9-17ab-45a3-b48e-e3319045a1c4': 'r_0268',
 '1b32b507-9f6d-47da-b1ea-6be776079277': 'r_0269',
 '7b12f769-5870-4511-bc61-34f51e3be2eb': 'r_0270',
 'cc5eb2b0-4b4e-4601-81df-e048ff93376e': 'r_0271',
 '19662d11-a07a-4967-a753-6f4fa0a147b4': 'r_0272',
 'd5fdf9aa-ab86-496a-8c7d-441fab08fe88': 'r_0273',
 '555e4bb2-a56c-4336-a358-3ad9e6af474b': 'r_0274',
 '0016f77d-3efb-4396-8328-e514772e7ee9': 'r_0275',
 'bfd724a3-9471-49f3-8901-bfb504393e9b': 'r_0276',
 'c2d45b8a-ffc0-47f9-af2d-f9e3a17233be': 'r_0277',
 '492d9564-5ce6-4120-8aee-dfd756d8d99b': 'r_0278',
 '32aefb99-4b32-4de8-8974-76922883910e': 'r_0279',
 '93bc4a11-a29d-4808-8f24-4cf48267ce98': 'r_0280',
 'ef7280c9-0039-44a3-960b-9890415d47ad': 'r_0281',
 '740d696f-b342-4ce8-870d-0a82c7b8eee7': 'r_0282',
 'a1eea9f1-ef8d-4a1f-af77-50de48022e51': 'r_0283',
 '2b0fe955-f5e0-430d-9939-231960944404': 'r_0284',
 '6db21ee2-d999-4446-9809-6bf6868ca715': 'r_0285',
 '333d77cd-7f0d-48f1-a49d-9e5b3913aec8': 'r_0286',
 '200a46a4-06f8-400a-bd08-324515921be2': 'r_0287',
 '0f903507-c071-4e78-a9c6-fb54dcdb7972': 'r_0288',
 '66c7871c-95a5-4138-afc4-32c36e886d99': 'r_0289',
 'e4209989-7efb-41b8-83fe-3b5a35a0c79c': 'r_0290',
 'caa97c5c-1c9d-4f72-a4a1-961c6e8cddd3': 'r_0291',
 '7d3e3263-668f-4283-ab26-edd6d4c43be1': 'r_0292',
 '2ad779c4-a8de-4f25-9db8-31209e79d558': 'r_0293',
 '5297689c-7ae5-48fa-84bd-c9b7cf834e07': 'r_0294',
 '546dbc81-38bb-4ef0-a50e-2475a66c7ea4': 'r_0295',
 'b71ff839-1669-4253-bfb0-2cc4894f076a': 'r_0296',
 'b03deef2-af5f-4e2b-be66-26297ed098a1': 'r_0297',
 '0c925b66-45e8-4465-b0c2-4a6dd2d4b493': 'r_0298',
 '35172d3f-33db-44a9-b304-3072ee81ca62': 'r_0299',
 '076a212d-aa18-4267-baec-4e9cd49301bd': 'r_0300',
 '93753b7d-6e06-4a29-bca8-ab994bb32c26': 'r_0301',
 'ecc03d0e-96d5-4f7d-b4f1-1f72b86da9d4': 'r_0302',
 'aea2baa8-719a-4cbb-ac27-465eb4f75d3f': 'r_0303',
 '0c0eef32-6b36-434a-beec-9a5133798dfd': 'r_0304',
 '5ede6d47-08e4-4cef-abfe-772fb0d23c6b': 'r_0305',
 '2c452422-edf4-4325-85c8-0b214cea8548': 'r_0306',
 'd3d52e46-fd8d-4c25-9310-cc48de0a305e': 'r_0307',
 'e8aa99b5-fd81-4fe4-9b2e-0c3830631afc': 'r_0308',
 '99ce86a7-9ef5-4b2a-bc62-9f267f44f8ab': 'r_0309',
 '8c014dac-cf76-4a24-9a28-c27f47bbfaf9': 'r_0310',
 '77b3a36c-dc5e-466a-b85b-44bba5abbb8f': 'r_0311',
 '81f36f9c-b091-4547-aa82-3a3b618e8f92': 'r_0312',
 'f3a4bcea-139c-4674-b65f-adbb9da12d57': 'r_0313',
 'eebfcbe1-5353-4b2a-945e-4c3657264ae4': 'r_0314',
 '3c43cefd-b8d8-4219-9b54-566f8f99f2a4': 'r_0315',
 '81da2154-0139-4d0f-92bc-e8347e019805': 'r_0316',
 'b561266f-7522-45ec-be7d-1e58529e28ee': 'r_0317',
 '038a450b-cb66-4c9c-b0d3-86c6b64a6537': 'r_0318',
 '320aef94-6727-4289-8b11-203d4c990c42': 'r_0319',
 '4d5feedd-d765-4da8-b11d-fd89e27d8928': 'r_0320',
 'c0b536a3-8c85-44dd-8072-d6c257fc9376': 'r_0321',
 '908ae32f-d1d0-4d79-9b2d-81cffb85e9ad': 'r_0322',
 '2aa15a74-0439-49b6-bf8a-d7776076d801': 'r_0323',
 '635dd51a-a511-43b8-980e-2d012533549f': 'r_0324',
 'e096cb09-24aa-408e-8905-9b3f1ac81b35': 'r_0325',
 '2dbf6466-f07f-4f65-86ac-180a21748c30': 'r_0326',
 '636dd149-f8d7-46c8-a423-286eb5f82c60': 'r_0327',
 '0a591b0b-e654-4c27-98c2-cd783ec541e1': 'r_0328',
 '8334ac14-eda3-4683-91cb-06e31df8ffc0': 'r_0329',
 'a08525b7-f121-43d7-912f-dc80cb778922': 'r_0330',
 '355ab524-64a3-4daa-ab57-47ffa76fd463': 'r_0331',
 '26f0153f-057f-487b-9e9f-c5321790d0d3': 'r_0332',
 'd50a6cbf-75b5-4bf5-893e-2245d3b1048a': 'r_0333',
 'b2a5cbb0-cdf0-4063-bf5e-2066406b408f': 'r_0334',
 '62e30064-5d7f-4c5a-a040-823a29099791': 'r_0335',
 '1fb1b684-1ab3-4e73-a4c2-80254b8d4b28': 'r_0336',
 '3f880c47-e5cd-41cd-bf6d-ab2de8656d42': 'r_0337',
 '79daa138-9f33-4594-b421-d22ace419bfb': 'r_0338',
 'e2387c49-6b82-4bec-856c-56249d3276be': 'r_0339',
 '0b8eecc3-d333-4215-89d9-58ddc840226b': 'r_0340',
 '474ab544-a31d-4267-bdb2-830eed76bf5f': 'r_0341',
 'a658e378-4321-43af-9b29-36e4c0dea4cf': 'r_0342',
 '519c4580-e06d-4b7f-aeb2-152e35b4430f': 'r_0343',
 '20ae7aa0-4aa3-4567-821d-f16138402bd7': 'r_0344',
 'fe57254b-29e7-45f0-9872-082d4c48d12d': 'r_0345',
 '038fa5ca-d20b-423d-b320-068dea63b21d': 'r_0346',
 'd0d4d8e1-c384-418c-938f-53d0b5918bf2': 'r_0347',
 '87d0d421-4e90-4479-84fc-75b1112fb750': 'r_0348',
 '31098f3f-d7af-49dc-aa48-90fa77584814': 'r_0349',
 '6905eb11-951f-4670-a593-1a3016a2d106': 'r_0350',
 'ae680822-8e19-4efd-8b3c-dae1272b273a': 'r_0351',
 '654641b5-93fd-4cf7-b01a-8311c238f40d': 'r_0352',
 '9be05bd7-e29e-45ec-9a35-c22893799805': 'r_0353',
 'e4033e01-e7b1-4c48-b5ab-c1fc51112782': 'r_0354',
 'f6dd033c-4989-40fe-8863-84a063fdeca3': 'r_0355',
 '3f3872d9-8403-4a34-8349-349e36612d2a': 'r_0356',
 '0fddf788-815b-45dd-b776-a6e0e18e590d': 'r_0357',
 '44c1980e-d723-41c0-ae95-8363d2ec5963': 'r_0358',
 'ea6ae0f6-1d5f-4a58-861b-0b90a9c25e59': 'r_0359',
 '3c7c75d3-07a6-4773-9a60-9e7990103538': 'r_0360',
 '9641ca26-cdd5-4112-9f50-7a999a957442': 'r_0361',
 'c307a522-09e7-419a-b507-e370f60a081f': 'r_0362',
 '5a92813e-5b38-413a-b35d-4760acfd3c9a': 'r_0363',
 'b4c74730-57d8-4313-ba16-d22b7de488bf': 'r_0364',
 '744fb846-5a25-48e0-ae77-d5824d24faf1': 'r_0365',
 'a6e82e1a-75d4-42e7-815f-b9c7325745b2': 'r_0366',
 '67eabc08-4277-49e8-aab8-37b8851bd35e': 'r_0367',
 'cc1a551b-0eaf-4b5d-9a08-6609232197b1': 'r_0368',
 'ceb7f5a3-9503-404f-97a0-21a3b809f9a3': 'r_0369',
 '91c1e4ab-2785-4f97-acae-a641cc016194': 'r_0370',
 'cf2310cc-d866-4b09-826b-926068dcee9a': 'r_0371',
 '5ee45899-44dc-420b-957a-2f22814873f0': 'r_0372',
 '602ca6b7-6e9d-4ab5-b1c3-9b45132a8f8f': 'r_0373',
 'a26cb744-dbdb-461f-b3f0-e8eb58a3bb62': 'r_0374',
 '6239fc4f-619d-4ac6-a71c-4d1f79f40d7c': 'r_0375',
 'ee273915-5bfc-49d4-aa7d-278e9010a5ac': 'r_0376',
 'de359885-645a-4539-943d-f4415496d423': 'r_0377',
 '2edcf0da-e5cb-4c85-a132-826084aedac4': 'r_0378',
 '3993a871-dd89-40e0-aa6d-2ee88ea59d1f': 'r_0379',
 '810fd95c-2962-4d0a-bbf4-af97b40586e1': 'r_0380',
 'e009e5ab-93e1-428b-a230-3db0c5ca3dee': 'r_0381',
 'f1497e73-b166-4194-a8c6-caa494d15244': 'r_0382',
 '1992fd17-7e8c-46dc-8c59-2b459a0cd9e7': 'r_0383',
 '803dcbb7-ebd8-40c7-9916-a8581b7f7987': 'r_0384',
 '4a15b5fc-bdb1-4be7-afc6-982d75c83d92': 'r_0385',
 '39da49d9-859e-4ab5-a70a-570eca6e7c76': 'r_0386',
 '41f2b109-b885-4715-8424-e58656dffb5c': 'r_0387',
 '861fe5aa-278c-4f2f-a575-c6a1eb0e35c1': 'r_0388',
 '74177341-7da6-4478-a6e6-baa9f9037652': 'r_0389',
 '802dcfc1-3248-43f0-a3c8-5f9f0cb36090': 'r_0390',
 'be43e46c-b849-4abd-b423-8f0f8ba5185b': 'r_0391',

In [10]:
id_mapper = pmap(question_ids).update(response_ids)
id_mapper['084bbcf2-f51e-4b15-8c6e-d648a2b2cc73']

'r_0996'

I'm going to convert the score to lower case as it'll make everything easier in clingo.

In [16]:
# Note to students: don't write code like this!

bea_2way_data_df = (
    j_df.rename(
        {
            "id": "original_response_id",
            "question_id": "original_question_id",
            "answer": "response",
            "score": "capitalised_score",
        },
        axis="columns",
    )
    .assign(
        response_id=j_df["id"].map(id_mapper),
        question_id=j_df["question_id"].map(id_mapper),
        correct=j_df["rubric"].apply(lambda x: x["Correct"]),
        incorrect_1=j_df["rubric"].apply(lambda x: x["Incorrect"][0]),
        incorrect_2=j_df["rubric"].apply(lambda x: x["Incorrect"][1]),
        
        
        score=j_df["score"]
        .str.lower()
        
         )
    .drop(["rubric", "capitalised_score"], axis="columns")
)

bea_2way_data_df.head()

,original_response_id,original_question_id,question,response,partition,response_id,question_id,correct,incorrect_1,incorrect_2,score
0,73b0b485-5e89-40d8-ae68-4a650d4670c4,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,Bei einem höheren Zerteilungsgrad ( hier das Z...,train,r_7726,q_71,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,incorrect
1,0c46f560-fcb4-4ea4-a540-cc2b96512b1c,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Das Größte apfelstück , also das mildem gering...",train,r_0724,q_71,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,correct
2,467514d6-45d6-4f33-a1aa-dab58cadb9a7,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,verderben schneller\n,train,r_3209,q_71,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,incorrect
3,b570cf0d-d29d-4add-bc9a-53156bb68003,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,Durch zerteilen der Äpfel wird dessen oberfläc...,train,r_0102,q_71,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,correct
4,64d40458-107c-403e-bc30-f51ff3b09495,920df344-fe5c-4f48-ae64-a8458e8db40a,Beurteile das Zerteilen der Äpfel hinsichlich ...,"Je größer die Oberfläche vom Apfel ist , desto...",train,r_6205,q_71,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,Die Schüler:innen beurteilen die Verderblichke...,incorrect

In [31]:
questions_df = bea_2way_data_df[
    [
        "original_question_id",
        "question_id",
        "question",
        "correct",
        "incorrect_1",
        "incorrect_2",
    ]
]

questions_df = questions_df.assign(
    correct_id=questions_df["question_id"].replace(r"q(.*)", r"c\1", regex=True),
    incorrect_1_id=questions_df["question_id"].replace(
        r"q(.*)", r"i\1", regex=True
    ),
    incorrect_2_id=questions_df["question_id"].replace(r"q(.*)", r"j\1", regex=True),
)

questions_df = questions_df.drop_duplicates().sort_values(
    "question_id", ignore_index=True
)
questions_df.head()

,original_question_id,question_id,question,correct,incorrect_1,incorrect_2,correct_id,incorrect_1_id,incorrect_2_id
0,fcf5ff56-5e98-4eb7-8df3-afb0544d9739,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,"Die SuS erklären, dass durch die unterschiedli...","Die SuS erklären nicht, dass dadurch die Mögli...","Die SuS erklären, dass durch die unterschiedli...",c_00,i_00,j_00
1,c51b89a6-0219-4eee-bb89-b2b5168998f5,q_01,Begründe deine Auswahl.,Die Schüler:innen stellen einen Zusammenhang z...,Die Schüler:innen stellen keinen Zusammenhang ...,Die Schüler:innen stellen einen Zusammenhang z...,c_01,i_01,j_01
2,379ba896-bb8f-440d-9d32-5dc9ca0297fe,q_02,Formuliere selbst eine Fragestellung.,Die SuS beschreiben die durchschnittliche Gesc...,Die SuS beschreiben weder die durchschnittlich...,Die SuS beschreiben entweder die durchschnittl...,c_02,i_02,j_02
3,cb99dfb3-2788-4a10-b934-7ea8276b2b44,q_03,Beschreibe auf Basis Deines Vorwissens die Erk...,"Die Schüler:innen erläutern den Vorteil, dass ...",Die Schüler:innen erläutern den erweiterten Bl...,"Die Schüler:innen erläuten den Vorteil, dass d...",c_03,i_03,j_03
4,b85b1a95-35ba-473e-a164-4602a4a13a2f,q_04,In dem Video siehst du die abstrakte Funktions...,Die SuS beschreiben die Funktionsweise eines D...,Die SuS beschreiben die Funktionsweise nicht k...,"Die SuS beschreiben nur einen Teil, entweder d...",c_04,i_04,j_04

In [32]:
responses_df = bea_2way_data_df[
    [
        "original_response_id",
        "response_id",
        "question_id",
        "response",
        "score",
        "partition",
    ]
].sort_values(["question_id", "partition", "response_id"], ignore_index=True)


responses_df.head()

,original_response_id,response_id,question_id,response,score,partition
0,e78122dd-9f3c-456e-a546-fc905b023807,r_0111,q_00,Im Winter ist weniger Strahlung weil die Sonne...,incorrect,train
1,4cf98df5-8d79-4144-aeea-37df3bec5de5,r_0115,q_00,Es kann im Süden und Sommer mehr elektrische E...,incorrect,train
2,6550b62c-cc65-458d-a609-a7a38c45cbca,r_0129,q_00,da im sommer mehr die somme scheint gibt es au...,incorrect,train
3,e4d9c6e1-ed55-468a-9101-89218a989852,r_0178,q_00,im Sommer gewinnt man die meiste Energie wobei...,incorrect,train
4,7d3e3263-668f-4283-ab26-edd6d4c43be1,r_0292,q_00,Im Winter ist am wenigsten Energie da im Winte...,incorrect,train

## Part 2: Extract lemmata with SpaCy

We will use SpaCy to convert the sentences into a usable form.

In [33]:
import spacy
import contextualSpellCheck

In [34]:
nlp = spacy.load("de_core_news_md")

# The spell check is causing issues at the moment. I'll return to this later...
# contextualSpellCheck.add_to_pipe(nlp)

In [35]:
de = nlp("junge reicht auch langsam mal")
de

junge reicht auch langsam mal

Don't need to be particularly finnicky with this in the first instance. We have essentially four types of sentence: question, correct answer, incorrect "answer", and response. We've indexed them differently, so we can just (?) bung them all into a big DataFrame:

In [36]:
# Again, stern note to students: don't write code like this!!

text_df = pd.concat(
    [
        questions_df[["question_id", "question"]].rename(
            {"question_id": "id", "question": "text"}, axis="columns"
        ),
        questions_df[["correct_id", "correct"]].rename(
            {"correct": "text", "correct_id": "id"}, axis="columns"
        ),
        questions_df[["incorrect_1_id", "incorrect_1"]].rename(
            {"incorrect_1": "text", "incorrect_1_id": "id"}, axis="columns"
        ),
        questions_df[["incorrect_2_id", "incorrect_2"]].rename(
            {"incorrect_2": "text", "incorrect_2_id": "id"}, axis="columns"
        ),
        responses_df[["response_id", "response"]].rename(
            {"response_id": "id", "response": "text"}, axis="columns"
        ),
    ],
    ignore_index=True,
)

text_df

          id                                               text
0       q_00  Erläutere die Auswirkungen der jahreszeitabhän...
1       q_01                            Begründe deine Auswahl.
2       q_02              Formuliere selbst eine Fragestellung.
3       q_03  Beschreibe auf Basis Deines Vorwissens die Erk...
4       q_04  In dem Video siehst du die abstrakte Funktions...
...      ...                                                ...
8206  r_7866                                   er wird größer\n
8207  r_1396  Nein , weil sich gar nichts in der Spanne von ...
8208  r_4071  Weil dadurch es zwei identische x und y Werte ...
8209  r_6273                                           Weil ,\n
8210  r_6877  Da der Differenzquotient die Steigerung zwisch...

[8211 rows x 2 columns]

OK, so now we can apply SpaCy to each of the texts to get the appropriate data:

In [37]:
text_df = text_df.assign(spacy=text_df["text"].apply(nlp))
text_df

,id,text,spacy
0,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,"(Erläutere, die, Auswirkungen, der, jahreszeit..."
1,q_01,Begründe deine Auswahl.,"(Begründe, deine, Auswahl, .)"
2,q_02,Formuliere selbst eine Fragestellung.,"(Formuliere, selbst, eine, Fragestellung, .)"
3,q_03,Beschreibe auf Basis Deines Vorwissens die Erk...,"(Beschreibe, auf, Basis, Deines, Vorwissens, d..."
4,q_04,In dem Video siehst du die abstrakte Funktions...,"(In, dem, Video, siehst, du, die, abstrakte, F..."
...,...,...,...
8206,r_7866,er wird größer\n,"(er, wird, größer, \n)"
8207,r_1396,"Nein , weil sich gar nichts in der Spanne von ...","(Nein, ,, weil, sich, gar, nichts, in, der, Sp..."
8208,r_4071,Weil dadurch es zwei identische x und y Werte ...,"(Weil, dadurch, es, zwei, identische, x, und, ..."
8209,r_6273,"Weil ,\n","(Weil, ,, \n)"
8210,r_6877,Da der Differenzquotient die Steigerung zwisch...,"(Da, der, Differenzquotient, die, Steigerung, ..."

I'm putting all the lemmata into lower case... I suspect this is naughty, but I'm going to see how it goes first.

In [38]:
text_df = text_df.explode("spacy", ignore_index=True)
text_df = text_df.assign(
    i=text_df["spacy"].apply(lambda x: x.i),
    lemma=text_df["spacy"].apply(lambda x: x.lemma_.lower()),
    word_text=text_df["spacy"].apply(lambda x: x.text),
)
text_df

,id,text,spacy,i,lemma,word_text
0,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,Erläutere,0,erläuter,Erläutere
1,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,die,1,der,die
2,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,Auswirkungen,2,auswirkung,Auswirkungen
3,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,der,3,der,der
4,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,jahreszeitabhängigen,4,jahreszeitabhängig,jahreszeitabhängigen
...,...,...,...,...,...,...
275450,r_6877,Da der Differenzquotient die Steigerung zwisch...,genau,18,genau,genau
275451,r_6877,Da der Differenzquotient die Steigerung zwisch...,aufeinander,19,aufeinander,aufeinander
275452,r_6877,Da der Differenzquotient die Steigerung zwisch...,liegen,20,liegen,liegen
275453,r_6877,Da der Differenzquotient die Steigerung zwisch...,.,21,--,.
275454,r_6877,Da der Differenzquotient die Steigerung zwisch...,\n,22,\n,\n

I think I'm also going to remove any cases where the lemma is just whitespace.

In [39]:
def whitespace_str(str_in):
    return all([c in whitespace for c in str_in])


assert whitespace_str(
    """    
                      
                                """
)
assert not whitespace_str("slkdjf  s")

In [40]:
text_df = text_df[-text_df["lemma"].apply(whitespace_str)]

-----------------------------

In [41]:
questions_df

,original_question_id,question_id,question,correct,incorrect_1,incorrect_2,correct_id,incorrect_1_id,incorrect_2_id
0,fcf5ff56-5e98-4eb7-8df3-afb0544d9739,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,"Die SuS erklären, dass durch die unterschiedli...","Die SuS erklären nicht, dass dadurch die Mögli...","Die SuS erklären, dass durch die unterschiedli...",c_00,i_00,j_00
1,c51b89a6-0219-4eee-bb89-b2b5168998f5,q_01,Begründe deine Auswahl.,Die Schüler:innen stellen einen Zusammenhang z...,Die Schüler:innen stellen keinen Zusammenhang ...,Die Schüler:innen stellen einen Zusammenhang z...,c_01,i_01,j_01
2,379ba896-bb8f-440d-9d32-5dc9ca0297fe,q_02,Formuliere selbst eine Fragestellung.,Die SuS beschreiben die durchschnittliche Gesc...,Die SuS beschreiben weder die durchschnittlich...,Die SuS beschreiben entweder die durchschnittl...,c_02,i_02,j_02
3,cb99dfb3-2788-4a10-b934-7ea8276b2b44,q_03,Beschreibe auf Basis Deines Vorwissens die Erk...,"Die Schüler:innen erläutern den Vorteil, dass ...",Die Schüler:innen erläutern den erweiterten Bl...,"Die Schüler:innen erläuten den Vorteil, dass d...",c_03,i_03,j_03
4,b85b1a95-35ba-473e-a164-4602a4a13a2f,q_04,In dem Video siehst du die abstrakte Funktions...,Die SuS beschreiben die Funktionsweise eines D...,Die SuS beschreiben die Funktionsweise nicht k...,"Die SuS beschreiben nur einen Teil, entweder d...",c_04,i_04,j_04
...,...,...,...,...,...,...,...,...,...
73,afdd3dad-858c-46e7-972e-d5909efbe9ce,q_73,Vergleiche mit Hinblick auf die Temperatur die...,Die MB-Verteilung wird aufgabenbezogen korrekt...,Die MB-Verteilung wird weder aufgabenbezogen k...,Die MB-Verteilung wird aufgabenbezogen korrekt...,c_73,i_73,j_73
74,35d897f0-c1b4-422c-9a33-43e7da1ffe27,q_74,Schau dir deine Hypothesen noch einmal an. Ent...,Die Erklärung ...\n... beschreibt das Vorhande...,Die Erklärung \n... beschreibt das Vorhandense...,Die Erklärung ...\n... beschreibt das Vorhande...,c_74,i_74,j_74
75,b470d591-dc0c-41e1-afa7-4f212d6248e5,q_75,Beschreibe die geschwindigkeitsbezogene Häufig...,Die MB-Verteilung wird aufgabenbezogen korrekt...,Die MB-Verteilung wird weder aufgabenbezogen k...,Die MB-Verteilung wird aufgabenbezogen korrekt...,c_75,i_75,j_75
76,e71649c1-57e4-4cf6-a5fe-c55b8568add3,q_76,Beschreibe Auffälligkeiten der dargestellten d...,Die Schüler:innen beschreiben die dargestellte...,Die Schüler:innen beschreiben die dargestellte...,Die Schüler:innen beschreiben die dargstellte ...,c_76,i_76,j_76
77,4b331fd2-8e92-4f74-90cd-615d90694463,q_77,"Erläutere, warum du ""Wahr"" oder ""Falsch"" angek...",Die SuS beschreiben den Verlauf der Sekante be...,Die SuS beschreiben weder den Verlauf der Seka...,Die SuS beschreiben entweder den Verlauf der S...,c_77,i_77,j_77

In [42]:
responses_df

,original_response_id,response_id,question_id,response,score,partition
0,e78122dd-9f3c-456e-a546-fc905b023807,r_0111,q_00,Im Winter ist weniger Strahlung weil die Sonne...,incorrect,train
1,4cf98df5-8d79-4144-aeea-37df3bec5de5,r_0115,q_00,Es kann im Süden und Sommer mehr elektrische E...,incorrect,train
2,6550b62c-cc65-458d-a609-a7a38c45cbca,r_0129,q_00,da im sommer mehr die somme scheint gibt es au...,incorrect,train
3,e4d9c6e1-ed55-468a-9101-89218a989852,r_0178,q_00,im Sommer gewinnt man die meiste Energie wobei...,incorrect,train
4,7d3e3263-668f-4283-ab26-edd6d4c43be1,r_0292,q_00,Im Winter ist am wenigsten Energie da im Winte...,incorrect,train
...,...,...,...,...,...,...
7894,1bd6d708-9b88-4033-a387-455a2b20fa07,r_7866,q_77,er wird größer\n,incorrect,train
7895,1e434c36-86f1-4338-be09-25d5a18479cf,r_1396,q_77,"Nein , weil sich gar nichts in der Spanne von ...",incorrect,trial
7896,541bfa0a-71f8-4ec3-8760-c3b2e495144d,r_4071,q_77,Weil dadurch es zwei identische x und y Werte ...,incorrect,trial
7897,4dd48587-e1f6-4ffb-87a7-16965d4cca82,r_6273,q_77,"Weil ,\n",incorrect,trial
7898,9a5ba033-9ded-438a-80a1-a357cfcadc0b,r_6877,q_77,Da der Differenzquotient die Steigerung zwisch...,incorrect,trial

Quickly drop the `spacy` column, as that isn't picklable.

In [43]:
text_df.drop("spacy", axis="columns")

,id,text,i,lemma,word_text
0,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,0,erläuter,Erläutere
1,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,1,der,die
2,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,2,auswirkung,Auswirkungen
3,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,3,der,der
4,q_00,Erläutere die Auswirkungen der jahreszeitabhän...,4,jahreszeitabhängig,jahreszeitabhängigen
...,...,...,...,...,...
275449,r_6877,Da der Differenzquotient die Steigerung zwisch...,17,punkt,Punkte
275450,r_6877,Da der Differenzquotient die Steigerung zwisch...,18,genau,genau
275451,r_6877,Da der Differenzquotient die Steigerung zwisch...,19,aufeinander,aufeinander
275452,r_6877,Da der Differenzquotient die Steigerung zwisch...,20,liegen,liegen
275453,r_6877,Da der Differenzquotient die Steigerung zwisch...,21,--,.

There's one other wrinkle: some of the lemmata contain quotation marks, which screws up the training file. As an interim hacky solution, I'll simply swap any instances of `"` for `'`. I think that the `"` appear in code, so it's not a sensible switch, but it'll do for the moment.

In [44]:
text_df = text_df.drop("lemma", axis="columns").assign(
    lemma=text_df["lemma"].str.replace('"', "'")
)

text_df.query(
    """
              `word_text`.str.contains('"')"""
).sort_values("word_text")

,id,text,spacy,i,word_text,lemma
81,q_05,Öffne das Material für deine Gruppe! Schaue di...,"""",18,"""",--
160432,r_4999,"( a ) Durch den Begriff "" Gleichgewicht "" hat ...","""",8,"""",--
160462,r_4999,"( a ) Durch den Begriff "" Gleichgewicht "" hat ...","""",38,"""",--
160464,r_4999,"( a ) Durch den Begriff "" Gleichgewicht "" hat ...","""",40,"""",--
179531,r_4166,Vegleichende Versuchsbeobachtungen Ansatz A An...,"""",75,"""",--
...,...,...,...,...,...,...
253306,r_2527,Beantwortung der Impulsfrage Mögliche Darstell...,"id=""MathJax-Element-1-Frame",18,"id=""MathJax-Element-1-Frame",id='mathjax-element-1-fram
252459,r_0919,Beantwortung der Impulsfrage Mögliche Darstell...,"role=""presentation",28,"role=""presentation",role='presentation
253312,r_2527,Beantwortung der Impulsfrage Mögliche Darstell...,"role=""presentation",24,"role=""presentation",role='presentation
253308,r_2527,Beantwortung der Impulsfrage Mögliche Darstell...,"tabindex=""0",20,"tabindex=""0",tabindex='0
252455,r_0919,Beantwortung der Impulsfrage Mögliche Darstell...,"tabindex=""0",24,"tabindex=""0",tabindex='0

OK, and I think that those are in the format that I can export them.

In [45]:
with open("bea_2way_data.pickle", "wb") as fOut:
    pickle.dump(
        {
            "questions": questions_df,
            "responses": responses_df,
            "text": text_df.drop("spacy", axis="columns"),
        },
        fOut,
    )