I need to check Aisling's results against the actual list, because it seems as though a couple of the training cases have slipped in.

3 way, without theory

In [4]:
import pandas as pd

In [5]:
test_data_df=pd.read_json('/Users/alistair.willis/repos/bea-2026/aislings_results/LLM_submission_results/3-way/unseen_answers_3-way_with_theory_submission.json')

test_data_df.head()

,id,question_id,score
0,e9cdbae8-5d14-40aa-83d7-076d222ec5d8,33385739-7e9d-4aa6-9118-62e6772f7eb1,Correct
1,cfebe550-47f6-41c5-9f5d-e872370398d6,33385739-7e9d-4aa6-9118-62e6772f7eb1,Correct
2,2a3180f5-8391-4811-8fa5-ad052b2dc72f,33385739-7e9d-4aa6-9118-62e6772f7eb1,Correct
3,29fd2f0e-4a3a-4727-b94e-11fc5efe8f4b,33385739-7e9d-4aa6-9118-62e6772f7eb1,Incorrect
4,070c149e-7da4-4338-a1b7-80342df4cdc8,33385739-7e9d-4aa6-9118-62e6772f7eb1,Partially correct

In [6]:
aisling_df=pd.read_json('/Users/alistair.willis/repos/bea-2026/aislings_results/LLM_submission_results/3-way/unseen_answers_3-way_trained_submission.json')

aisling_df.head()

,id,question_id,score
0,e9cdbae8-5d14-40aa-83d7-076d222ec5d8,33385739-7e9d-4aa6-9118-62e6772f7eb1,Correct
1,cfebe550-47f6-41c5-9f5d-e872370398d6,33385739-7e9d-4aa6-9118-62e6772f7eb1,Correct
2,2a3180f5-8391-4811-8fa5-ad052b2dc72f,33385739-7e9d-4aa6-9118-62e6772f7eb1,Correct
3,29fd2f0e-4a3a-4727-b94e-11fc5efe8f4b,33385739-7e9d-4aa6-9118-62e6772f7eb1,Incorrect
4,070c149e-7da4-4338-a1b7-80342df4cdc8,33385739-7e9d-4aa6-9118-62e6772f7eb1,Partially correct

In [7]:
import json

In [24]:
with open('/Users/alistair.willis/repos/bea-2026/aislings_results/LLM_submission_results/3-way/unseen_answers_3-way_with_theory_submission.json') as fIn:
    aisling_dict=json.load(fIn)

a_dict={(a['id'], a['question_id']):a['score'] for a in aisling_dict}
a_dict

{('e9cdbae8-5d14-40aa-83d7-076d222ec5d8',
  '33385739-7e9d-4aa6-9118-62e6772f7eb1'): 'Correct',
 ('cfebe550-47f6-41c5-9f5d-e872370398d6',
  '33385739-7e9d-4aa6-9118-62e6772f7eb1'): 'Correct',
 ('2a3180f5-8391-4811-8fa5-ad052b2dc72f',
  '33385739-7e9d-4aa6-9118-62e6772f7eb1'): 'Correct',
 ('29fd2f0e-4a3a-4727-b94e-11fc5efe8f4b',
  '33385739-7e9d-4aa6-9118-62e6772f7eb1'): 'Incorrect',
 ('070c149e-7da4-4338-a1b7-80342df4cdc8',
  '33385739-7e9d-4aa6-9118-62e6772f7eb1'): 'Partially correct',
 ('f535351b-2e8e-41b8-8fc1-bf45acb1673e',
  '33385739-7e9d-4aa6-9118-62e6772f7eb1'): 'Partially correct',
 ('994b6d97-ff75-4ca7-8c2b-1bc986fed601',
  '33385739-7e9d-4aa6-9118-62e6772f7eb1'): 'Partially correct',
 ('b9fa0922-5dcc-401f-b1a6-467fe6ee35f7',
  '33385739-7e9d-4aa6-9118-62e6772f7eb1'): 'Partially correct',
 ('fde636a8-65e2-4a04-a8fb-2ea55b280b46',
  '33385739-7e9d-4aa6-9118-62e6772f7eb1'): 'Partially correct',
 ('cfb872dc-feb5-4d52-ada8-da96373baf4a',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Correct',
 ('17cf8db1-dee7-4bb6-9091-61ff2d7f0d0a',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('58811a0d-05c5-4f04-b36c-af2c544ed002',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Incorrect',
 ('6e8ec776-b684-4919-84ee-0bc91922a835',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('922b7e3e-2c18-43ea-aa00-94fac69e5aea',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('ba59c171-8f73-4323-96dc-8a63cbcece11',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('2022d4dd-e109-4fe7-b885-4c4fddfb5ff3',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Correct',
 ('7e39bd3a-e1ae-4f49-8dd0-59c64c349000',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Correct',
 ('9ba38f68-6686-4fb9-8646-a8140ee81c04',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Incorrect',
 ('42c75bd0-290a-48ed-8f81-e51a6b47c978',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('517e0e82-0af5-4e9d-86e1-31014f238093',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Incorrect',
 ('f1abad10-d744-45f4-98b4-dabf6ae1cab4',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('d4b8efaa-f1dc-46b8-b367-81c1a43da0fa',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('481041f4-66cb-424d-85f7-e666653154fa',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Incorrect',
 ('7a44145f-c2b7-4271-9bd1-1f0ab08fb10b',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Incorrect',
 ('b840bec6-6e4a-4e67-bc97-1868fa523522',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('f2dc856a-229f-4689-8fed-eab9e70b35ec',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('9ccf0bc0-5d1b-489f-ac20-a4cc65394cd1',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('590239e9-d362-42db-a18e-233065c9c5a5',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('84994386-e7d7-46f6-800a-5d888a1535dc',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('c4102d10-2fc5-4f22-b3c8-b352fb2160e3',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Correct',
 ('790b15ce-7629-4caa-9b16-7539f11a596a',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('ae26a0a8-f484-47a5-bfe5-728c199b0171',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Correct',
 ('1ca62370-4c86-479f-8051-69e8b5873593',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Incorrect',
 ('107f897f-ea4f-4ea4-9964-2fcd0e093790',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('8368eca5-0fb3-440a-9761-4bc52d981fec',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Incorrect',
 ('5337a913-d637-4400-b636-75ba6759496d',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Incorrect',
 ('98ad1bea-3bb0-46e9-8b69-b1168e80b981',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Incorrect',
 ('075238be-a1e2-4bac-8af0-5ea6d8cdbe9c',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('9a8815cd-c771-4aa0-a125-e324aa63708c',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Incorrect',
 ('90a7ba20-07af-41b0-a469-836210df916b',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Incorrect',
 ('f07d9d91-b247-4ceb-91c6-aeb039adf56b',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('1c0c09ba-763f-4a69-91f0-6ce3c898756b',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Correct',
 ('695ad4dd-1d89-42ec-b628-d35543d31470',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Incorrect',
 ('16f3b447-3b13-425d-8bb6-ab32945f9cfa',
  '6cc84feb-e8e1-4561-8057-452dce98bd65'): 'Partially correct',
 ('2cdeb333-b3e9-402f-8f2c-7041d70e6b6c',
  '93ed3f79-b3e9-41d2-8984-d8e2fa2143e8'): 'Partially correct',
 ('9e847043-5c25-4583-b9bf-e3411d3a9a44',
  '93ed3f79-b3e9-41d2-8984-d8e2fa2143e8'): 'Partially correct',
 ('64098d97-7168-4829-9ec6-e39df0bd5c5f',
  '93ed3f79-b3e9-41d2-8984-d8e2fa2143e8'): 'Partially correct',
 ('e0d41fbd-fd73-4d24-900a-854cbcf80d3a',
  '93ed3f79-b3e9-41d2-8984-d8e2fa2143e8'): 'Correct',
 ('5a7b66f3-7042-4b8d-81e8-59d10b67e1d9',
  '93ed3f79-b3e9-41d2-8984-d8e2fa2143e8'): 'Partially correct',
 ('a6ee4411-1a5b-4e90-b695-7a41ec6c8009',
  '93ed3f79-b3e9-41d2-8984-d8e2fa2143e8'): 'Correct',
 ('700a633d-6022-4b2d-b9d4-f41f1498eabd',
  '93ed3f79-b3e9-41d2-8984-d8e2fa2143e8'): 'Partially correct',
 ('c4e69014-2447-4703-aec5-181efc8750d7',
  '93ed3f79-b3e9-41d2-8984-d8e2fa2143e8'): 'Partially correct',
 ('d15e7faa-90df-4f6f-8bf6-ff9fdd1c2c7c',
  '93ed3f79-b3e9-41d2-8984-d8e2fa2143e8'): 'Incorrect',
 ('1cfc8a72-d1c9-45ca-832f-e8614ebbe6a4',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Incorrect',
 ('96a8452f-6e35-4fbc-9f4f-28b712dca672',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Correct',
 ('6888fdaa-7c51-424d-9b8f-63b141a1ed15',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Correct',
 ('b2202b7e-aa44-4516-aa0c-d3084659d088',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Partially correct',
 ('ad362fdc-e283-4ae0-a528-96ae224118ac',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Correct',
 ('be12fc5f-7df4-4618-aedf-088ec46262c8',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Incorrect',
 ('af7d54d8-b36c-49c6-a8f8-70d8177ac8b5',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Correct',
 ('660e0b02-2fbe-4a27-91ea-5e567f9b1653',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Incorrect',
 ('59cd071d-a701-410d-a187-217eaeb8e778',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Correct',
 ('2af7509f-4ae6-4af8-90b8-4a38501a636c',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Correct',
 ('972664df-9e26-496e-a4bc-3ca818c1d0bd',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Correct',
 ('4b13b1dd-9c4d-43a4-b077-e9a32ca727bb',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Correct',
 ('52982f00-2074-4c91-b6e7-f52ed8524ad5',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Incorrect',
 ('d53432b8-6381-4ed6-946b-9714bec89e91',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Incorrect',
 ('c9b5941d-c5b9-4cea-b475-7c39db2051ee',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Incorrect',
 ('03601bcc-1394-4da6-be30-04659679e476',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Incorrect',
 ('0fad170d-fd60-43af-8683-5a63c1debe34',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Correct',
 ('974c798e-0aff-4a34-94ba-9d5a91fa4941',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Incorrect',
 ('46379d68-2e4f-45ef-9f0d-25aa8806276b',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Incorrect',
 ('dc860c46-1254-47a1-b396-2d4a8da4fb46',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Partially correct',
 ('1e6c4605-cc29-471e-be95-5125b454a55c',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Correct',
 ('87f0b7cd-4bb6-4e4f-9b26-9cc55301d4d6',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Incorrect',
 ('80297005-dce6-4f30-b2b8-653aa55db1c7',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Incorrect',
 ('94996886-6502-43b3-936b-ed27aa0ff75a',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Partially correct',
 ('8207a3c9-34ac-4a0d-9a96-0900b64987ca',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Incorrect',
 ('7de399d1-1661-4059-86c6-2656b4f62b3c',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Correct',
 ('f3317c7f-c702-44d2-a16d-13952ce24184',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Partially correct',
 ('00bf4a5f-940b-4eb2-b3ff-f6fec4d35152',
  'f5537007-c811-4910-8a18-aaa3e61c39f2'): 'Incorrect',
 ('16b09c28-596d-43f5-825d-07caa2ed4b96',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('1b3acdd1-d641-427c-8503-9fdf48f327dc',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('ce783000-5012-436f-b9de-e6a91c04c186',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('aa42c53f-4dad-4a0a-9893-ef12caee433c',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('0a5bde52-f348-4b6a-bac0-8d79f0520f60',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('2fa9e297-5745-4bbc-b0ba-a824892e576a',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('713b9474-25e2-4bab-8718-69e30bd4f761',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('7b699ef0-0417-4242-bf22-ed98d9a39296',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('20accfb3-fee2-4fb5-8063-0a5e83057530',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('8c063d54-3364-449d-8d5c-6e90448cae73',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('3837cea5-9f8f-4a8c-85ac-b53cf1d8418e',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('f6ddc616-3faa-468c-8886-401b9cdc00a2',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('e5635636-f340-4bcc-a00a-8efd803ac35d',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('b34d4710-c500-480b-bcf1-1f9dda13b127',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('e35a8c5f-edcd-43f1-b934-357872806c9c',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('a67c1b83-de46-4b7d-bd9e-8e71bf848319',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('297f2fc2-a249-4ded-bb65-fd86d304bf13',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('ead48ee8-0cc4-40a1-81c5-8671d4b8d5e2',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('f28a2ac0-3508-40cd-ac21-2f53f604f4b6',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('17542720-993c-4a17-8b7d-ecd5e0fc4ac5',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('3f30cebe-c88a-40c0-bae2-0f1788e5d8f0',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('7b3be8e0-4770-4d5d-95af-ef198f0611b5',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('52fa3f44-831b-40bc-9fe4-f50b8ccfebf3',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('9cf5b59f-d3a3-4f24-91cc-7aad01d71a88',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('7e794b33-e0ff-4dfa-9dcd-2d837212e055',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('96fd2d62-443e-4725-a7c3-4815ce58fac7',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('a8639ab4-f8ab-4416-a49b-2ddb448b5758',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('3fd950d9-668e-4e9a-b1b8-ea5530edfb4b',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('e5729d94-e56b-40cd-a6b6-4773ee0589f7',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('d6c49d0f-4b8e-445e-9b62-4b22749c5cac',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('ae670d08-ab28-4266-bbbf-5fd757cd1051',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('e69cf5f9-3e9f-4909-8aad-24a5ccd166c8',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('145e3da9-80fd-463e-9232-69c8c3e750b2',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('334b22c2-5b81-4116-b873-cfed4f3958be',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('01ff5c87-188b-4969-a477-9853fd274a93',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('0f61e04a-ae0f-42d6-bc0a-b3ed04567369',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('e6babb6d-a9ef-4374-8928-d21ce92d3a82',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('d6bc722e-25c0-4eef-bce7-92eafd22be21',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('36b0c628-306a-4b5d-836a-c4646b6a88a3',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('3023cf88-367a-4333-b538-4236d4422fd3',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('db8656a9-d3c9-4733-9758-7619f61383b3',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('6fa9e1cb-a876-4a6f-a4e4-f978ff203f3e',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('692266f9-fb79-4b11-b4fc-95857650db9f',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Incorrect',
 ('4fc2176a-c7fa-44a3-813e-23c6f0538e00',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('514f815e-84fe-4357-8538-e2fd06f47327',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('4239882a-ca00-46ae-8e6c-243e1bc44e4f',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('8096c26a-3ddd-4660-83eb-f0dfc8cfba7f',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('728c2fe3-4ea5-4705-9d04-5be06ee827cc',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('7c9e7805-47b6-4e70-b334-9c23f217591c',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('f4bf0db5-55d9-4514-8786-8820eae17c17',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('3695325b-6807-49b5-ad2b-c098a2494c79',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Partially correct',
 ('bc5ac6f2-585f-4efe-b16d-8ca5c3c84f47',
  '1731b1ff-c4a1-4c37-83e7-47ba9f3b37fe'): 'Correct',
 ('6b3f0f82-124e-45d6-8150-c2754a9180e5',
  'da9e0a6a-7fd4-47ad-aa6a-a0f91fda560e'): 'Incorrect',
 ('c8727481-a383-459c-bc2e-67e4634c1b32',
  'da9e0a6a-7fd4-47ad-aa6a-a0f91fda560e'): 'Partially correct',
 ('b4b2c291-428c-4714-8f9a-85580a1464e0',
  'da9e0a6a-7fd4-47ad-aa6a-a0f91fda560e'): 'Partially correct',
 ('046c6daf-b79e-405b-9972-cac97e8e59c1',
  'da9e0a6a-7fd4-47ad-aa6a-a0f91fda560e'): 'Partially correct',
 ('975acae9-cab4-4d90-a4e5-062db37899de',
  'da9e0a6a-7fd4-47ad-aa6a-a0f91fda560e'): 'Incorrect',
 ('ed37bb23-d4b3-4de3-a0c9-54806a199888',
  'da9e0a6a-7fd4-47ad-aa6a-a0f91fda560e'): 'Correct',
 ('b3cfc49a-53bc-4677-a304-ea5624f0159a',
  'da9e0a6a-7fd4-47ad-aa6a-a0f91fda560e'): 'Correct',
 ('b4aadf17-90ba-4ec6-8784-3aa796ef627f',
  'da9e0a6a-7fd4-47ad-aa6a-a0f91fda560e'): 'Correct',
 ('512ff181-4949-420e-923a-9e9f82d79e16',
  'da9e0a6a-7fd4-47ad-aa6a-a0f91fda560e'): 'Incorrect',
 ('b36371a0-715d-4fb2-9c4d-62571c22b684',
  'da9e0a6a-7fd4-47ad-aa6a-a0f91fda560e'): 'Incorrect',
 ('d3b3ca07-aaf8-4663-a201-a6098a103af8',
  'da9e0a6a-7fd4-47ad-aa6a-a0f91fda560e'): 'Partially correct',
 ('582e60dc-1fcc-471b-98a6-f219e49f746c',
  'da9e0a6a-7fd4-47ad-aa6a-a0f91fda560e'): 'Incorrect',
 ('99269035-8a08-4f81-9651-f2367d07706b',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('06b9de7e-168c-4ab7-9daf-f7acbc218e23',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('2ef37350-eb9f-4a6c-8f60-33432445bae9',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Correct',
 ('4fe494ad-9b25-406b-9c4e-233e45ac5bac',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('ebee69de-ce2f-43e5-8e20-1e7948ae6578',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('af1604ce-bdf3-4648-8adc-ebc7ff5ed7a7',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('3721a413-1d37-4327-8f05-594a2d0998dd',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('3ddb8d28-74df-4b14-925d-6e0f4e3895e2',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Partially correct',
 ('9f90c98e-feba-43da-820c-9898b9ed09dd',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('109a007f-399f-46b7-9ed5-985293ff035e',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Correct',
 ('28aef082-5b01-4241-be18-7d9c4a54d86d',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('63eec053-a4fc-4168-b680-759ef93b7811',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('f0660344-09c4-48e6-b339-3ac5a4f35b36',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('927b5d13-03f8-40e6-8736-09698012fd25',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('40bfcfa2-0046-4bf3-a9b1-b6d7dbb6edd6',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('ef0f57ef-234b-4aeb-9339-d9a410d7a30b',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('8e421605-8050-4e60-b9a3-5b0cbe52c031',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('8e409206-520e-48da-ac1f-026c9d8eb6bb',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Partially correct',
 ('ebea8a7f-0220-454a-a185-044cfcc2c0b5',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Partially correct',
 ('4db18f8e-d033-483d-906a-48a331cbd73f',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('d9e8cde6-aa64-4331-ae68-a0ea7f3d88b3',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Correct',
 ('b692b42a-41ea-48be-9c1a-9bc8fd9e7181',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Partially correct',
 ('a10f4f29-864c-4364-988f-1087cf4b92e2',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('3613227b-bb84-497a-9c2f-cf9fa807f82c',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('2dab6a9c-acc0-4ec3-8f92-bc6affb86a44',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Partially correct',
 ('4f0eefb8-bbf9-4cd5-b6b6-22875da82ce1',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('bae80eb2-26b8-4df7-b97f-295712eb0b45',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Partially correct',
 ('77db95f8-6d28-4b72-b437-58cf9f3e2b96',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('5dbd60dd-1070-4ab6-9ebd-ccae3de31f49',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('de85a06d-9506-4c3c-991c-0c3ff9181a6b',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Partially correct',
 ('2c5d597c-0ad7-49b6-bce4-be83a8e1778e',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('66f4e079-157a-49d4-a09a-bd7fba63e364',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('af2c7bf9-68c9-4453-b937-bfd1173d7da0',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('a1b7fc1a-5690-45cb-bd04-bdefdb530e07',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('05ecd9aa-b8b5-40d5-84dc-3caa79a3e6cb',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('ecab91ce-3968-4b54-b587-782e887dc5b7',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('4d9f9358-e4eb-46c7-91f3-10b2d9726a30',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('2a84ca78-3eec-44df-b635-897072ea71ca',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('6c1546f4-a612-408c-b327-d8d7aefecf7f',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Correct',
 ('b7a12402-0265-4359-ad42-3e84da5ca31a',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Correct',
 ('60798c85-47f6-439c-a9b2-ca2b5962cc12',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('b22d3f9b-7380-4258-b9f7-4ec0e514c675',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('a9fe63d7-2587-4c87-8744-e69b421bbf35',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Partially correct',
 ('86f0aa59-b513-413e-b7c7-64e94296e768',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('c722070d-b64e-4da8-ae97-4a894182ecc4',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('8978639f-8242-4188-bd2d-29fd98888796',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('846b4265-f222-42d9-a2a5-49ecfe31bff6',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Correct',
 ('97a44862-3d5e-4300-9be1-ab375daaa538',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('d660a7cf-c05c-4077-b894-82ab0488bc91',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('9f33d2cf-da6a-4109-bfd3-34c76656027d',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('7364b6e3-2fd5-4b6d-b509-49da4321e223',
  '442a4171-9f3a-40b2-b4b5-7c023bbfd4c4'): 'Incorrect',
 ('d7e861a0-85cf-4587-b433-377a02ce8082',
  '7f600524-3002-4fff-8536-ccbdac8d8a93'): 'Incorrect',
 ('d9680fbf-b5af-4c21-a36b-66eaa8002d82',
  '7f600524-3002-4fff-8536-ccbdac8d8a93'): 'Partially correct',
 ('fb0f8df9-48b6-405b-9d13-cad493db2f32',
  '7f600524-3002-4fff-8536-ccbdac8d8a93'): 'Partially correct',
 ('0a4d4ae0-51f1-4df4-8e00-bf187b120aff',

In [25]:
with open('/Users/alistair.willis/repos/bea-2026/BEA Shared Task 2026 on Rubric-based Short Answer Scoring for German/test_data/3_way/3way_unseen_answers_eval.json') as fIn:
    test_dict=json.load(fIn)
test_dict

[{'id': 'e9cdbae8-5d14-40aa-83d7-076d222ec5d8',
  'question_id': '33385739-7e9d-4aa6-9118-62e6772f7eb1',
  'question': 'Erläutere...\n(a) wie dieser Mitschüler zu dieser falschen Aussage gelangen könnte.\n(b) wie Du ihn davon überzeugen würdest, dass diese Aussage nicht korrekt ist (z.B. mit welchen Versuchsdaten).',
  'answer': 'Der Schüler hat das Gleichgewicht der Konzentration von Alkohol und Carbonsäure und Ester falsch verstanden und den Alkohol aus der Gleichung gestrichen , außerdem stellt sich ein Gleichgewicht der Konzentrationen ein und nicht gleiche Konzentrationen .\nMit den Daten des vorausgehenden Versuchvideos , sollte man ihn überzeugen können .\n',
  'rubric': {'Incorrect': 'Die Schüler:innen erläutern weder das Zustandekommen möglicher Fehlinterpretationen, noch beziehen sie die Daten mit ein.',
   'Partially correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten, ohne jedoch konkrete Daten mit einzubeziehen.',
   'Correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten und beziehen konkrete Daten mit ein.'}},
 {'id': 'cfebe550-47f6-41c5-9f5d-e872370398d6',
  'question_id': '33385739-7e9d-4aa6-9118-62e6772f7eb1',
  'question': 'Erläutere...\n(a) wie dieser Mitschüler zu dieser falschen Aussage gelangen könnte.\n(b) wie Du ihn davon überzeugen würdest, dass diese Aussage nicht korrekt ist (z.B. mit welchen Versuchsdaten).',
  'answer': 'Er ist davon ausgegangen das der Alkohol komplett verbraucht wird und keine Rückreaktion stattfinden .\nSehen kann man das in den Tabellen aus der ersten Seite und da sieht man , dass die beiden Edukte in gleicher Konzentration vorliegen dennoch das Produkt in erhöhter Konzentration .\n',
  'rubric': {'Incorrect': 'Die Schüler:innen erläutern weder das Zustandekommen möglicher Fehlinterpretationen, noch beziehen sie die Daten mit ein.',
   'Partially correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten, ohne jedoch konkrete Daten mit einzubeziehen.',
   'Correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten und beziehen konkrete Daten mit ein.'}},
 {'id': '2a3180f5-8391-4811-8fa5-ad052b2dc72f',
  'question_id': '33385739-7e9d-4aa6-9118-62e6772f7eb1',
  'question': 'Erläutere...\n(a) wie dieser Mitschüler zu dieser falschen Aussage gelangen könnte.\n(b) wie Du ihn davon überzeugen würdest, dass diese Aussage nicht korrekt ist (z.B. mit welchen Versuchsdaten).',
  'answer': '( a ) Der Mitschüler hat in diesem Fall den Begriff des Gleichgewichtes etwas falsch interpretiert .\nGleichgewicht bedeutet in diesem Fall , dass sich die Konzentrationen an Edukten und Produkten irgendwann nicht mehr verändert .\nEs stellen sich konstante Konzentrationsverhältnisse ein , aber nicht die Werte der Konzentrationen sind gleich . ( b ) Um den Mitschüler zu überzeugen , können ihm Reaktionsergebnisse gezeigt werden , wie bspw. ein Graph gezeigt werden ( der von den vorherigen Seiten ) .\nMan könnte den Versuch aber auch versuchen zu visualisieren .\n',
  'rubric': {'Incorrect': 'Die Schüler:innen erläutern weder das Zustandekommen möglicher Fehlinterpretationen, noch beziehen sie die Daten mit ein.',
   'Partially correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten, ohne jedoch konkrete Daten mit einzubeziehen.',
   'Correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten und beziehen konkrete Daten mit ein.'}},
 {'id': '29fd2f0e-4a3a-4727-b94e-11fc5efe8f4b',
  'question_id': '33385739-7e9d-4aa6-9118-62e6772f7eb1',
  'question': 'Erläutere...\n(a) wie dieser Mitschüler zu dieser falschen Aussage gelangen könnte.\n(b) wie Du ihn davon überzeugen würdest, dass diese Aussage nicht korrekt ist (z.B. mit welchen Versuchsdaten).',
  'answer': 'Keine ahnung wie er darauf kommt , denn es ist relativ offensichtlich , dass die Konzentration der Carbonsäure sinkt und die vom Ester steigt .\nLeider bin ich schlecht im erklären und weiss nicht wie ich es dem weiss machen soll .\n',
  'rubric': {'Incorrect': 'Die Schüler:innen erläutern weder das Zustandekommen möglicher Fehlinterpretationen, noch beziehen sie die Daten mit ein.',
   'Partially correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten, ohne jedoch konkrete Daten mit einzubeziehen.',
   'Correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten und beziehen konkrete Daten mit ein.'}},
 {'id': '070c149e-7da4-4338-a1b7-80342df4cdc8',
  'question_id': '33385739-7e9d-4aa6-9118-62e6772f7eb1',
  'question': 'Erläutere...\n(a) wie dieser Mitschüler zu dieser falschen Aussage gelangen könnte.\n(b) wie Du ihn davon überzeugen würdest, dass diese Aussage nicht korrekt ist (z.B. mit welchen Versuchsdaten).',
  'answer': 'a ) Da die Carbonsäure-Konzentration sinkt und die Konzentration des Ester steigt , sollten die sich irgendwo in der Mitte treffen . b ) Die beiden Konzentrationen verändern sich ab einem bestimmten Zeitpunkt so wenig , dass sie nicht aufeinander treffen würden .\n',
  'rubric': {'Incorrect': 'Die Schüler:innen erläutern weder das Zustandekommen möglicher Fehlinterpretationen, noch beziehen sie die Daten mit ein.',
   'Partially correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten, ohne jedoch konkrete Daten mit einzubeziehen.',
   'Correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten und beziehen konkrete Daten mit ein.'}},
 {'id': 'f535351b-2e8e-41b8-8fc1-bf45acb1673e',
  'question_id': '33385739-7e9d-4aa6-9118-62e6772f7eb1',
  'question': 'Erläutere...\n(a) wie dieser Mitschüler zu dieser falschen Aussage gelangen könnte.\n(b) wie Du ihn davon überzeugen würdest, dass diese Aussage nicht korrekt ist (z.B. mit welchen Versuchsdaten).',
  'answer': 'Ich verstehe seine Aussage nicht .\nEine chemischer Gleichgewicht ist wenn die Edukte ( beide ) und die Produkte eine konstante Konzentration haben , da durch das Steigen der Eduktteilchen sinken die wirksamen Zusammenstöße der Edukte aber die der Produkte steigen bis zu der Einstellzeit in der die Produkte und Edukte genauso viele Teilchen gebildeten haben .\n',
  'rubric': {'Incorrect': 'Die Schüler:innen erläutern weder das Zustandekommen möglicher Fehlinterpretationen, noch beziehen sie die Daten mit ein.',
   'Partially correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten, ohne jedoch konkrete Daten mit einzubeziehen.',
   'Correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten und beziehen konkrete Daten mit ein.'}},
 {'id': '994b6d97-ff75-4ca7-8c2b-1bc986fed601',
  'question_id': '33385739-7e9d-4aa6-9118-62e6772f7eb1',
  'question': 'Erläutere...\n(a) wie dieser Mitschüler zu dieser falschen Aussage gelangen könnte.\n(b) wie Du ihn davon überzeugen würdest, dass diese Aussage nicht korrekt ist (z.B. mit welchen Versuchsdaten).',
  'answer': '( a ) Er ist verwirrt durch den Begriff Gleichgewicht und bezihet das auf Konzentration . ( b ) Ihm die vorrausgegangenen Versuche zeigen .\n',
  'rubric': {'Incorrect': 'Die Schüler:innen erläutern weder das Zustandekommen möglicher Fehlinterpretationen, noch beziehen sie die Daten mit ein.',
   'Partially correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten, ohne jedoch konkrete Daten mit einzubeziehen.',
   'Correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten und beziehen konkrete Daten mit ein.'}},
 {'id': 'b9fa0922-5dcc-401f-b1a6-467fe6ee35f7',
  'question_id': '33385739-7e9d-4aa6-9118-62e6772f7eb1',
  'question': 'Erläutere...\n(a) wie dieser Mitschüler zu dieser falschen Aussage gelangen könnte.\n(b) wie Du ihn davon überzeugen würdest, dass diese Aussage nicht korrekt ist (z.B. mit welchen Versuchsdaten).',
  'answer': 'konzentration ist gleich , carbonsäure sinkt und ester steigt , er nimmt an , dass sich die beiden konzentrationen in der mitte treffen wie das gleichgewicht -- &gt; irrtum vom gleichgewicht\n',
  'rubric': {'Incorrect': 'Die Schüler:innen erläutern weder das Zustandekommen möglicher Fehlinterpretationen, noch beziehen sie die Daten mit ein.',
   'Partially correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten, ohne jedoch konkrete Daten mit einzubeziehen.',
   'Correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten und beziehen konkrete Daten mit ein.'}},
 {'id': 'fde636a8-65e2-4a04-a8fb-2ea55b280b46',
  'question_id': '33385739-7e9d-4aa6-9118-62e6772f7eb1',
  'question': 'Erläutere...\n(a) wie dieser Mitschüler zu dieser falschen Aussage gelangen könnte.\n(b) wie Du ihn davon überzeugen würdest, dass diese Aussage nicht korrekt ist (z.B. mit welchen Versuchsdaten).',
  'answer': 'a ) weil er Edukte und Produkte verwechselt hat und die Konzentration der jeweiligen Seite gleich ist , aber nicht auf Edukt und Produkt Seite . b ) Da die Hinreaktion schneller abläuft , als die Rückreaktion sind immer mehr Produkte vorhanden , als Edukte .\nDas bedeutet , dass auch die Konzentration auf der Produktseite beim Ester höher ist , als auf der Eduktseite .\n',
  'rubric': {'Incorrect': 'Die Schüler:innen erläutern weder das Zustandekommen möglicher Fehlinterpretationen, noch beziehen sie die Daten mit ein.',
   'Partially correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten, ohne jedoch konkrete Daten mit einzubeziehen.',
   'Correct': 'Die Schüler:innen erläutern das Zustandekommen möglicher Fehlinterpretationen mit der Annahme gleicher Entitäten und beziehen konkrete Daten mit ein.'}},
 {'id': 'cfb872dc-feb5-4d52-ada8-da96373baf4a',
  'question_id': '6cc84feb-e8e1-4561-8057-452dce98bd65',
  'question': 'Beschreibe auf Grundlage Deiner oben getroffenen Auswahl in eigenen Worten, was Du allgemein unter der Reaktionsgeschwindigkeit chemischer Reaktionen verstehst.',
  'answer': 'Im Allgemeinen beschreibt die Reaktionsgeschwindigkeit die Beziehung zwischen zeitlicher Dauer und Stoffreichem sowie energetischem Umsatz .\nSie gibt also an wie schnell eine Reaktion abläuft .\n',
  'rubric': {'Incorrect': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit nicht.',
   'Partially correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoffumsatz pro Zeit.',
   'Correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoff- und Energieumsatz pro Zeit.'}},
 {'id': '17cf8db1-dee7-4bb6-9091-61ff2d7f0d0a',
  'question_id': '6cc84feb-e8e1-4561-8057-452dce98bd65',
  'question': 'Beschreibe auf Grundlage Deiner oben getroffenen Auswahl in eigenen Worten, was Du allgemein unter der Reaktionsgeschwindigkeit chemischer Reaktionen verstehst.',
  'answer': 'Die Reaktionsgeschwindigkeit beschreibt die menge an reagierenden Teilchen pro Zeit .\n',
  'rubric': {'Incorrect': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit nicht.',
   'Partially correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoffumsatz pro Zeit.',
   'Correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoff- und Energieumsatz pro Zeit.'}},
 {'id': '58811a0d-05c5-4f04-b36c-af2c544ed002',
  'question_id': '6cc84feb-e8e1-4561-8057-452dce98bd65',
  'question': 'Beschreibe auf Grundlage Deiner oben getroffenen Auswahl in eigenen Worten, was Du allgemein unter der Reaktionsgeschwindigkeit chemischer Reaktionen verstehst.',
  'answer': 'Unter einer Reaktionsgeschwindigkeit verstehe Ich wie der Name bereits verrät , die Zeit die eine Reaktion brauch .\n',
  'rubric': {'Incorrect': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit nicht.',
   'Partially correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoffumsatz pro Zeit.',
   'Correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoff- und Energieumsatz pro Zeit.'}},
 {'id': '6e8ec776-b684-4919-84ee-0bc91922a835',
  'question_id': '6cc84feb-e8e1-4561-8057-452dce98bd65',
  'question': 'Beschreibe auf Grundlage Deiner oben getroffenen Auswahl in eigenen Worten, was Du allgemein unter der Reaktionsgeschwindigkeit chemischer Reaktionen verstehst.',
  'answer': 'Der Prozes von Edukte zu Produkt\n',
  'rubric': {'Incorrect': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit nicht.',
   'Partially correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoffumsatz pro Zeit.',
   'Correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoff- und Energieumsatz pro Zeit.'}},
 {'id': '922b7e3e-2c18-43ea-aa00-94fac69e5aea',
  'question_id': '6cc84feb-e8e1-4561-8057-452dce98bd65',
  'question': 'Beschreibe auf Grundlage Deiner oben getroffenen Auswahl in eigenen Worten, was Du allgemein unter der Reaktionsgeschwindigkeit chemischer Reaktionen verstehst.',
  'answer': 'Der Umsatz des Eduktes innerhalb der Zeit x = Reaktionsgeschwindigkeit\n',
  'rubric': {'Incorrect': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit nicht.',
   'Partially correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoffumsatz pro Zeit.',
   'Correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoff- und Energieumsatz pro Zeit.'}},
 {'id': 'ba59c171-8f73-4323-96dc-8a63cbcece11',
  'question_id': '6cc84feb-e8e1-4561-8057-452dce98bd65',
  'question': 'Beschreibe auf Grundlage Deiner oben getroffenen Auswahl in eigenen Worten, was Du allgemein unter der Reaktionsgeschwindigkeit chemischer Reaktionen verstehst.',
  'answer': 'Die Reaktionsgeschwindigkeit gibt an wie schnell oder langsam eine Reaktion abläuft .\nDie Reaktionsgeschwindigkeit ist von mehreren Faktoren abhängig\n',
  'rubric': {'Incorrect': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit nicht.',
   'Partially correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoffumsatz pro Zeit.',
   'Correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoff- und Energieumsatz pro Zeit.'}},
 {'id': '2022d4dd-e109-4fe7-b885-4c4fddfb5ff3',
  'question_id': '6cc84feb-e8e1-4561-8057-452dce98bd65',
  'question': 'Beschreibe auf Grundlage Deiner oben getroffenen Auswahl in eigenen Worten, was Du allgemein unter der Reaktionsgeschwindigkeit chemischer Reaktionen verstehst.',
  'answer': 'Sowohl zeitliche Dauer des Ablaufs als auch die Dauer der Energieauf / abgabe\n',
  'rubric': {'Incorrect': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit nicht.',
   'Partially correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoffumsatz pro Zeit.',
   'Correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoff- und Energieumsatz pro Zeit.'}},
 {'id': '7e39bd3a-e1ae-4f49-8dd0-59c64c349000',
  'question_id': '6cc84feb-e8e1-4561-8057-452dce98bd65',
  'question': 'Beschreibe auf Grundlage Deiner oben getroffenen Auswahl in eigenen Worten, was Du allgemein unter der Reaktionsgeschwindigkeit chemischer Reaktionen verstehst.',
  'answer': 'Unter der Reaktionsgeschwindigkeit verstehe ich , die Geschwindigkeit einer Reaktion gemessen an Beobachtungen und am Energieumsatz ,\n',
  'rubric': {'Incorrect': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit nicht.',
   'Partially correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoffumsatz pro Zeit.',
   'Correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoff- und Energieumsatz pro Zeit.'}},
 {'id': '9ba38f68-6686-4fb9-8646-a8140ee81c04',
  'question_id': '6cc84feb-e8e1-4561-8057-452dce98bd65',
  'question': 'Beschreibe auf Grundlage Deiner oben getroffenen Auswahl in eigenen Worten, was Du allgemein unter der Reaktionsgeschwindigkeit chemischer Reaktionen verstehst.',
  'answer': 'Ich verstehe das in verbindung mit der zeitlichen Dauer\n',
  'rubric': {'Incorrect': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit nicht.',
   'Partially correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoffumsatz pro Zeit.',
   'Correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoff- und Energieumsatz pro Zeit.'}},
 {'id': '42c75bd0-290a-48ed-8f81-e51a6b47c978',
  'question_id': '6cc84feb-e8e1-4561-8057-452dce98bd65',
  'question': 'Beschreibe auf Grundlage Deiner oben getroffenen Auswahl in eigenen Worten, was Du allgemein unter der Reaktionsgeschwindigkeit chemischer Reaktionen verstehst.',
  'answer': 'Die Zeit die zwischen dem Anfang ( Edukt ) und dem Ende ( Produkt ) einer Reaktion liegt .\nDiese kann wie oben beschrieben , verschieden lange dauern bzw. ablaufen .\n',
  'rubric': {'Incorrect': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit nicht.',
   'Partially correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoffumsatz pro Zeit.',
   'Correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoff- und Energieumsatz pro Zeit.'}},
 {'id': '517e0e82-0af5-4e9d-86e1-31014f238093',
  'question_id': '6cc84feb-e8e1-4561-8057-452dce98bd65',
  'question': 'Beschreibe auf Grundlage Deiner oben getroffenen Auswahl in eigenen Worten, was Du allgemein unter der Reaktionsgeschwindigkeit chemischer Reaktionen verstehst.',
  'answer': 'Unter Reaktionsgeschwindigkeit versteht man die vergangenen Zeit einer Reaktion von Beginn bis Ende einer Reaktion\n',
  'rubric': {'Incorrect': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit nicht.',
   'Partially correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoffumsatz pro Zeit.',
   'Correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoff- und Energieumsatz pro Zeit.'}},
 {'id': 'f1abad10-d744-45f4-98b4-dabf6ae1cab4',
  'question_id': '6cc84feb-e8e1-4561-8057-452dce98bd65',
  'question': 'Beschreibe auf Grundlage Deiner oben getroffenen Auswahl in eigenen Worten, was Du allgemein unter der Reaktionsgeschwindigkeit chemischer Reaktionen verstehst.',
  'answer': 'Die Reaktionsgeschwindigkeit beschreibt wie lange ein Prozess dauert bis er reagiert , wie z. B ein Hefeteig braucht um zu gären und aufzugehen , damit seine Fülle erreicht ist .\nZudem die Reaktionsgeschwindigkeit bei der Explosion sehr schnell , dabei ist die Reaktion gleich geschehen .\n',
  'rubric': {'Incorrect': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit nicht.',
   'Partially correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoffumsatz pro Zeit.',
   'Correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoff- und Energieumsatz pro Zeit.'}},
 {'id': 'd4b8efaa-f1dc-46b8-b367-81c1a43da0fa',
  'question_id': '6cc84feb-e8e1-4561-8057-452dce98bd65',
  'question': 'Beschreibe auf Grundlage Deiner oben getroffenen Auswahl in eigenen Worten, was Du allgemein unter der Reaktionsgeschwindigkeit chemischer Reaktionen verstehst.',
  'answer': 'Reaktionsgeschwindigkeit gibt an wie schnell die Reaktionen ablaufen , damit inbegriffen wie schnell aus einem Produkt das Edukt wird oder umgesetzt wird\n',
  'rubric': {'Incorrect': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit nicht.',
   'Partially correct': 'Die Schüler:innen definieren die Reaktionsgeschwindigkeit als Stoffumsatz pro Zeit.',

In [26]:
for u in test_dict:
    u.update({'score':a_dict[(u['id'], u['question_id'])]})

In [27]:
with open('submission1.json', 'w') as fOut:
    json.dump(test_dict, fOut)